/* GENERATED by mote bake from coin.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound coin = mote_sfx_bake(mote, &coin_sfx); */
#ifndef MOTE_SFX_coin_H
#define MOTE_SFX_coin_H
#include "mote_api.h"

static const MoteSfx coin_sfx = {
    0,  /* wave */
    0.5,0,0,0, 0.38,0,
    0,0, 0,0.05,0.3,0.18,
    0.9,0,0, 0,0, 0,0, 0.4,0.32,
};

#endif
