/* GENERATED by mote bake from draft.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound draft = mote_sfx_bake(mote, &draft_sfx); */
#ifndef MOTE_SFX_draft_H
#define MOTE_SFX_draft_H
#include "mote_api.h"

static const MoteSfx draft_sfx = {
    0,  /* wave */
    0.2,0,0.05,0, 0.32,0,
    0,0, 0,0.05,0.35,0.14,
    0.85,0,0, 0,0, 0,0, 0.5,0.3,
};

#endif
