/* GENERATED by mote bake from food.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound food = mote_sfx_bake(mote, &food_sfx); */
#ifndef MOTE_SFX_food_H
#define MOTE_SFX_food_H
#include "mote_api.h"

static const MoteSfx food_sfx = {
    3,  /* wave */
    0.14,0,-0.12,0, 0.5,0,
    0,0, 0,0.05,0.1,0.1,
    0.35,0,0.15, 0,0, 0,0, 0,0,
};

#endif
