/* GENERATED by mote bake from gem.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound gem = mote_sfx_bake(mote, &gem_sfx); */
#ifndef MOTE_SFX_gem_H
#define MOTE_SFX_gem_H
#include "mote_api.h"

static const MoteSfx gem_sfx = {
    2,  /* wave */
    0.68,0,0.1,0, 0.5,0,
    0,0, 0,0.06,0.3,0.2,
    1,0,0, 0,0, 0,0, 0.25,0.42,
};

#endif
