/* GENERATED by mote bake from key.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound key = mote_sfx_bake(mote, &key_sfx); */
#ifndef MOTE_SFX_key_H
#define MOTE_SFX_key_H
#include "mote_api.h"

static const MoteSfx key_sfx = {
    0,  /* wave */
    0.5,0,0.06,0, 0.45,0,
    0,0, 0,0.05,0.25,0.12,
    1,0,0, 0,0, 0,0, 0.3,0.5,
};

#endif
