/* GENERATED by mote bake from locked.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound locked = mote_sfx_bake(mote, &locked_sfx); */
#ifndef MOTE_SFX_locked_H
#define MOTE_SFX_locked_H
#include "mote_api.h"

static const MoteSfx locked_sfx = {
    1,  /* wave */
    0.16,0.05,-0.18,0, 0.5,0,
    0,0, 0,0.08,0.1,0.12,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
