/* GENERATED by mote bake from lose.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound lose = mote_sfx_bake(mote, &lose_sfx); */
#ifndef MOTE_SFX_lose_H
#define MOTE_SFX_lose_H
#include "mote_api.h"

static const MoteSfx lose_sfx = {
    1,  /* wave */
    0.3,0.04,-0.14,0, 0.5,0,
    0,0, 0,0.3,0.1,0.4,
    0.5,-0.05,0.2, 0,0, 0,0, 0,0,
};

#endif
