/* GENERATED by mote bake from row.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound row = mote_sfx_bake(mote, &row_sfx); */
#ifndef MOTE_SFX_row_H
#define MOTE_SFX_row_H
#include "mote_api.h"

static const MoteSfx row_sfx = {
    0,  /* wave */
    0.38,0,0.1,0, 0.5,0,
    0,0, 0,0.22,0.35,0.3,
    1,0,0, 0,0, 0,0, 0.3,0.32,
};

#endif
