/* GENERATED by mote bake from star.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound star = mote_sfx_bake(mote, &star_sfx); */
#ifndef MOTE_SFX_star_H
#define MOTE_SFX_star_H
#include "mote_api.h"

static const MoteSfx star_sfx = {
    0,  /* wave */
    0.52,0,0.14,0, 0.5,0,
    0,0, 0,0.1,0.3,0.25,
    1,0,0, 0,0, 0,0, 0.34,0.4,
};

#endif
