/* GENERATED by mote bake from tick.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound tick = mote_sfx_bake(mote, &tick_sfx); */
#ifndef MOTE_SFX_tick_H
#define MOTE_SFX_tick_H
#include "mote_api.h"

static const MoteSfx tick_sfx = {
    0,  /* wave */
    0.6,0,0,0, 0.5,0,
    0,0, 0,0.012,0.05,0.035,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
