/* GENERATED by mote bake from unlock.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound unlock = mote_sfx_bake(mote, &unlock_sfx); */
#ifndef MOTE_SFX_unlock_H
#define MOTE_SFX_unlock_H
#include "mote_api.h"

static const MoteSfx unlock_sfx = {
    0,  /* wave */
    0.18,0,0.22,0, 0.3,0,
    0,0, 0,0.03,0.3,0.12,
    0.8,0,0, 0,0, 0,0, 0,0,
};

#endif
