/* GENERATED by mote bake from unlock.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound unlock = mote_sfx_bake(mote, &unlock_sfx); */
#ifndef MOTE_SFX_unlock_H
#define MOTE_SFX_unlock_H
#include "mote_api.h"

static const MoteSfx unlock_sfx = {
    0,  /* wave */
    0.24,0,0.22,0, 0.35,0,
    0,0, 0,0.04,0.25,0.12,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
