/* GENERATED by mote bake from win.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound win = mote_sfx_bake(mote, &win_sfx); */
#ifndef MOTE_SFX_win_H
#define MOTE_SFX_win_H
#include "mote_api.h"

static const MoteSfx win_sfx = {
    0,  /* wave */
    0.3,0,0.16,0.02, 0.5,0,
    0,0, 0.02,0.4,0.4,0.5,
    1,0,0, 0,0, 0,0, 0.36,0.28,
};

#endif
