/* GENERATED by mote bake from beep.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound beep = mote_sfx_bake(mote, &beep_sfx); */
#ifndef MOTE_SFX_beep_H
#define MOTE_SFX_beep_H
#include "mote_api.h"

static const MoteSfx beep_sfx = {
    0,  /* wave */
    0.3,0,0,0, 0.5,0,
    0,0, 0,0.1,0.2,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
