/* GENERATED by mote bake from boost.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boost = mote_sfx_bake(mote, &boost_sfx); */
#ifndef MOTE_SFX_boost_H
#define MOTE_SFX_boost_H
#include "mote_api.h"

static const MoteSfx boost_sfx = {
    1,  /* wave */
    0.22,0.85,0.28,0, 0.5,0,
    0,0, 0.03,0.28,0.3,0.34,
    0.9,0.05,0.1, 0,0, 0,0, 0,0,
};

#endif
