/* GENERATED by mote bake from drift.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound drift = mote_sfx_bake(mote, &drift_sfx); */
#ifndef MOTE_SFX_drift_H
#define MOTE_SFX_drift_H
#include "mote_api.h"

static const MoteSfx drift_sfx = {
    3,  /* wave */
    0.5,0,0,0, 0.5,0,
    0,0, 0.02,0.1,0,0.12,
    0.4,0,0.3, 0.15,0, 0,0, 0,0,
};

#endif
