/* GENERATED by mote bake from go.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound go = mote_sfx_bake(mote, &go_sfx); */
#ifndef MOTE_SFX_go_H
#define MOTE_SFX_go_H
#include "mote_api.h"

static const MoteSfx go_sfx = {
    0,  /* wave */
    0.52,0,0,0, 0.5,0,
    0,0, 0,0.2,0.3,0.22,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
