/* GENERATED by mote bake from hit.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound hit = mote_sfx_bake(mote, &hit_sfx); */
#ifndef MOTE_SFX_hit_H
#define MOTE_SFX_hit_H
#include "mote_api.h"

static const MoteSfx hit_sfx = {
    3,  /* wave */
    0.345161,0.0136182,-0.351797,0.0441602, 0,-0.0852539,
    0.0105176,0.0775293, 0,0.145371,0.60126,0.306138,
    0.615273,-0.160771,0.134629, 0.0792773,-0.0254883, -0.197871,0.142109, 0,-0.0204004,
};

#endif
