/* GENERATED by mote bake from item.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound item = mote_sfx_bake(mote, &item_sfx); */
#ifndef MOTE_SFX_item_H
#define MOTE_SFX_item_H
#include "mote_api.h"

static const MoteSfx item_sfx = {
    0,  /* wave */
    0.768546,0,0,0, 0.5,0,
    0,0, 0,0.0446625,0.420538,0.41748,
    1,0,0, 0,0, 0,0, 0.602936,0.4974,
};

#endif
