/* GENERATED by mote bake from lap.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound lap = mote_sfx_bake(mote, &lap_sfx); */
#ifndef MOTE_SFX_lap_H
#define MOTE_SFX_lap_H
#include "mote_api.h"

static const MoteSfx lap_sfx = {
    2,  /* wave */
    0.55,0,0,0, 0.5,0,
    0,0, 0,0.12,0.3,0.4,
    1,0,0, 0,0, 0,0, 0.5,0.35,
};

#endif
