/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound shell = mote_sfx_bake(mote, &shell_sfx); */
#ifndef MOTE_SFX_shell_H
#define MOTE_SFX_shell_H
#include "mote_api.h"

static const MoteSfx shell_sfx = {
    1,  /* wave */
    0.343134,0,0.255823,0, 0.5,0,
    0,0, 0,0.27576,0,0.225085,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
