#!/usr/bin/env python3
"""Extract the flight-path coordinate tables from the original Thumbalaga Python
modules and emit them as C `static const Pt NAME[]` arrays into src/paths.h.

These are GAME-LOGIC data (enemy entry/dive/challenge curves), not editable
Studio assets — generated here purely to avoid hand-transcribing ~60 lists.

Run:  python3 tools/gen_paths.py <src Thumbalaga dir>
"""
import ast, os, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    os.path.expanduser("~/thumby-color/TinyCircuits-Thumby-Color-Games/Thumbalaga")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "paths.h")

MODULES = ["dive.py", "entry_patterns.py", "transforms.py", "challenge.py"]

def is_pt_list(node):
    """True if node is a list/tuple of 2-element (int,int) tuples."""
    if not isinstance(node, (ast.List, ast.Tuple)):
        return False
    if not node.elts:
        return False
    for e in node.elts:
        if not isinstance(e, (ast.Tuple, ast.List)) or len(e.elts) != 2:
            return False
    return True

def as_int(n):
    if isinstance(n, ast.UnaryOp) and isinstance(n.op, ast.USub):
        return -as_int(n.operand)
    if isinstance(n, ast.Constant):
        return int(n.value)
    raise ValueError("non-int coord")

out = ["/* GENERATED by tools/gen_paths.py from the original Thumbalaga Python —",
       " * enemy flight-path tables (entry / dive / challenge / transform curves). */",
       "#ifndef THUMBALAGA_PATHS_H",
       "#define THUMBALAGA_PATHS_H",
       "typedef struct { int16_t x, y; } Pt;",
       ""]

names = []
for m in MODULES:
    tree = ast.parse(open(os.path.join(SRC, m)).read())
    for stmt in tree.body:
        if not isinstance(stmt, ast.Assign) or len(stmt.targets) != 1:
            continue
        tgt = stmt.targets[0]
        if not isinstance(tgt, ast.Name):
            continue
        if not is_pt_list(stmt.value):
            continue
        name = tgt.id
        try:
            pts = [(as_int(e.elts[0]), as_int(e.elts[1])) for e in stmt.value.elts]
        except ValueError:
            continue
        body = ",".join("{%d,%d}" % (x, y) for x, y in pts)
        out.append("static const Pt %s[] = {%s};" % (name, body))
        out.append("#define %s_N %d" % (name, len(pts)))
        names.append(name)

out += ["", "#endif"]
open(OUT, "w").write("\n".join(out) + "\n")
print("wrote %s — %d path tables: %s" % (OUT, len(names), ", ".join(names)))
