/* GENERATED by mote bake (img2tex) from badge_narrow.png — do not edit. */
#ifndef MOTE_IMG_badge_narrow_H
#define MOTE_IMG_badge_narrow_H
#include "mote_2d.h"

static const uint16_t badge_narrow_pal[12] = { 0x001b,0xdedb,0xdefb,0xe71c,0xe73c,0xf800,0xf802,0xf803,0xf806,0xf81f,0xf862,0xf8e3 };
static const uint8_t badge_narrow_idx[50] = {
  153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,145,34,41,34,33,150,34,89,85,85,150,43,89,34,34,
  151,163,89,85,85,152,36,89,34,34,146,34,41,146,9,153,0,153,
};
static const MoteImage badge_narrow_img = { 0, 10, 10, 0xF81F, 0, 1, badge_narrow_idx, badge_narrow_pal };  /* 4bpp indexed, 12 colours */
#define badge_narrow_W 10
#define badge_narrow_H 10

#endif