/* GENERATED by mote bake (img2tex) from badge_shields.png — do not edit. */
#ifndef MOTE_IMG_badge_shields_H
#define MOTE_IMG_badge_shields_H
#include "mote_2d.h"

static const uint16_t badge_shields_pal[6] = { 0x001b,0xb81b,0xdefb,0xf800,0xf81f,0xffe0 };
static const uint8_t badge_shields_idx[128] = {
  68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,17,17,17,20,85,0,85,84,34,34,34,36,
  0,0,0,68,21,17,81,20,5,0,80,84,51,0,51,4,85,0,85,68,81,85,21,20,0,0,0,84,51,34,51,36,
  5,85,80,68,81,17,21,20,0,0,0,84,51,34,51,36,5,0,80,68,21,17,81,68,85,0,85,68,35,51,50,68,
  64,0,4,68,65,17,20,68,69,0,84,68,66,51,36,68,68,0,68,68,68,17,68,68,68,85,68,68,68,34,68,68,
};
static const MoteImage badge_shields_img = { 0, 32, 8, 0xF81F, 0, 1, badge_shields_idx, badge_shields_pal };  /* 4bpp indexed, 6 colours */
#define badge_shields_W 32
#define badge_shields_H 8

#endif