/* GENERATED by mote bake (img2tex) from life_icon.png — do not edit. */
#ifndef MOTE_IMG_life_icon_H
#define MOTE_IMG_life_icon_H
#include "mote_2d.h"

static const uint16_t life_icon_pal[4] = { 0x035b,0xdefb,0xf800,0xf81f };
static const uint8_t life_icon_idx[18] = {
  51,19,51,51,19,51,33,17,35,33,33,35,16,16,19,18,18,19,
};
static const MoteImage life_icon_img = { 0, 6, 6, 0xF81F, 0, 1, life_icon_idx, life_icon_pal };  /* 4bpp indexed, 4 colours */
#define life_icon_W 6
#define life_icon_H 6

#endif