/* GENERATED by mote bake (img2tex) from player.png — do not edit. */
#ifndef MOTE_IMG_player_H
#define MOTE_IMG_player_H
#include "mote_2d.h"

static const uint16_t player_pal[4] = { 0x035b,0xdefb,0xf800,0xf81f };
static const uint8_t player_idx[72] = {
  51,51,49,51,51,51,51,51,49,51,51,51,51,51,17,19,51,51,51,35,17,19,35,51,51,35,17,19,35,51,35,19,
  17,19,19,35,35,16,18,16,19,35,19,1,33,33,3,19,17,17,17,17,17,19,17,18,17,18,17,19,17,34,17,18,
  33,19,19,51,49,51,51,19,
};
static const MoteImage player_img = { 0, 12, 12, 0xF81F, 0, 1, player_idx, player_pal };  /* 4bpp indexed, 4 colours */
#define player_W 12
#define player_H 12

#endif