/* GENERATED by mote bake (img2tex) from player_captured.png — do not edit. */
#ifndef MOTE_IMG_player_captured_H
#define MOTE_IMG_player_captured_H
#include "mote_2d.h"

static const uint16_t player_captured_pal[4] = { 0x035b,0xbddb,0xf800,0xf81f };
static const uint8_t player_captured_idx[72] = {
  51,51,50,51,51,51,51,51,50,51,51,51,51,51,34,35,51,51,51,19,34,35,19,51,51,19,34,35,19,51,19,35,
  34,35,35,19,19,32,33,32,35,19,35,2,18,18,3,35,34,34,34,34,34,35,34,33,34,33,34,35,34,17,34,33,
  18,35,35,51,50,51,51,35,
};
static const MoteImage player_captured_img = { 0, 12, 12, 0xF81F, 0, 1, player_captured_idx, player_captured_pal };  /* 4bpp indexed, 4 colours */
#define player_captured_W 12
#define player_captured_H 12

#endif