/* GENERATED by mote bake (img2tex) from anchor.png — do not edit. */
#ifndef MOTE_IMG_anchor_H
#define MOTE_IMG_anchor_H
#include "mote_2d.h"

static const uint16_t anchor_pal[9] = { 0x2966,0x4a4a,0x630d,0x632d,0x8411,0x8c72,0xb5b7,0xef5c,0xf81f };
static const uint8_t anchor_idx[144] = {
  136,136,0,0,136,136,136,0,17,17,0,136,128,1,17,17,16,8,128,17,83,17,17,8,1,21,51,49,17,16,1,19,
  51,49,17,16,1,17,51,17,17,16,1,17,17,17,17,16,128,17,17,17,17,8,128,1,17,17,16,8,136,0,17,17,
  0,136,136,136,0,0,136,136,136,136,119,119,136,136,136,119,34,34,119,136,135,114,34,34,39,120,135,34,100,34,34,120,
  114,38,68,66,34,39,114,36,68,66,34,39,114,34,68,34,34,39,114,34,34,34,34,39,135,34,34,34,34,120,135,114,
  34,34,39,120,136,119,34,34,119,136,136,136,119,119,136,136,
};
static const MoteImage anchor_img = { 0, 12, 24, 0xF81F, 0, 1, anchor_idx, anchor_pal };  /* 4bpp indexed, 9 colours */
#define anchor_W 12
#define anchor_H 24

#endif