/* GENERATED by mote bake (img2tex) from anchor.png — do not edit. */
#ifndef MOTE_IMG_anchor_H
#define MOTE_IMG_anchor_H
#include "mote_2d.h"

static const uint16_t anchor_pal[9] = { 0x52ab,0x630d,0x7bf1,0x8411,0x9cf5,0xb5b7,0xc63a,0xef5c,0xf81f };
static const uint8_t anchor_idx[144] = {
  136,136,0,0,136,136,136,0,34,34,0,136,128,2,34,34,32,8,128,34,100,34,34,8,2,38,68,66,34,32,2,36,
  68,66,34,32,2,34,68,34,34,32,2,34,34,34,34,32,128,34,34,34,34,8,128,2,34,34,32,8,136,0,34,34,
  0,136,136,136,0,0,136,136,136,136,119,119,136,136,136,119,17,17,119,136,135,113,17,17,23,120,135,17,83,17,17,120,
  113,21,51,49,17,23,113,19,51,49,17,23,113,17,51,17,17,23,113,17,17,17,17,23,135,17,17,17,17,120,135,113,
  17,17,23,120,136,119,17,17,119,136,136,136,119,119,136,136,
};
static const MoteImage anchor_img = { 0, 12, 24, 0xF81F, 0, 1, anchor_idx, anchor_pal };  /* 4bpp indexed, 9 colours */
#define anchor_W 12
#define anchor_H 24

#endif