/* GENERATED by mote bake from bounce.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound bounce = mote_sfx_bake(mote, &bounce_sfx); */
#ifndef MOTE_SFX_bounce_H
#define MOTE_SFX_bounce_H
#include "mote_api.h"

static const MoteSfx bounce_sfx = {
    0,  /* wave */
    0.17,0,0.26,-0.05, 0.45,0,
    0.25,0.4, 0,0.12,0.25,0.28,
    0.8,0,0.2, 0,0, 0,0, 0,0,
};

#endif
