/* GENERATED by mote bake from checkpoint.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound checkpoint = mote_sfx_bake(mote, &checkpoint_sfx); */
#ifndef MOTE_SFX_checkpoint_H
#define MOTE_SFX_checkpoint_H
#include "mote_api.h"

static const MoteSfx checkpoint_sfx = {
    2,  /* wave */
    0.38,0,0.06,0, 0.5,0,
    0,0, 0,0.12,0.3,0.22,
    1,0,0, 0,0, 0,0, 0.5,0.35,
};

#endif
