/* GENERATED by mote bake from grab.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound grab = mote_sfx_bake(mote, &grab_sfx); */
#ifndef MOTE_SFX_grab_H
#define MOTE_SFX_grab_H
#include "mote_api.h"

static const MoteSfx grab_sfx = {
    0,  /* wave */
    0.46,0,0.12,0, 0.35,0,
    0,0, 0,0.03,0.25,0.09,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
