/* GENERATED by mote bake from record.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound record = mote_sfx_bake(mote, &record_sfx); */
#ifndef MOTE_SFX_record_H
#define MOTE_SFX_record_H
#include "mote_api.h"

static const MoteSfx record_sfx = {
    2,  /* wave */
    0.4,0,0.02,0, 0.5,0,
    0,0, 0,0.18,0.2,0.3,
    1,0,0, 0,0, 0,0, 0.42,0.5,
};

#endif
