/* GENERATED by mote bake from release.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound release = mote_sfx_bake(mote, &release_sfx); */
#ifndef MOTE_SFX_release_H
#define MOTE_SFX_release_H
#include "mote_api.h"

static const MoteSfx release_sfx = {
    3,  /* wave */
    0.3,0,-0.14,0, 0.5,0,
    0,0, 0,0.06,0,0.2,
    0.42,0,0.4, 0,0, 0,0, 0,0,
};

#endif
