/* GENERATED by mote bake from efire.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound efire = mote_sfx_bake(mote, &efire_sfx); */
#ifndef MOTE_SFX_efire_H
#define MOTE_SFX_efire_H
#include "mote_api.h"

static const MoteSfx efire_sfx = {
    0,  /* wave */
    0.27,0,-0.22,0, 0.5,0,
    0,0, 0,0.04,0.3,0.13,
    1,0,0, 0.02,0, 0,0, 0,0,
};

#endif
