/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound miss = mote_sfx_bake(mote, &miss_sfx); */
#ifndef MOTE_SFX_miss_H
#define MOTE_SFX_miss_H
#include "mote_api.h"

static const MoteSfx miss_sfx = {
    3,  /* wave */
    0.28,0,-0.12,0, 0.5,0,
    0,0, 0,0.1,0.3,0.38,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
