/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wall = mote_sfx_bake(mote, &wall_sfx); */
#ifndef MOTE_SFX_wall_H
#define MOTE_SFX_wall_H
#include "mote_api.h"

static const MoteSfx wall_sfx = {
    0,  /* wave */
    0.28,0,-0.18,0, 0.5,0,
    0,0, 0,0.01,0.3,0.09,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
