/* GENERATED by obj2mesh from examples/hulls/assets/beacon.obj — do not edit. */
#ifndef MOTE_MESH_beacon_H
#define MOTE_MESH_beacon_H
#include "mote_mesh.h"

static const MeshVert beacon_verts[10] = {
    { -64,   0, -64},    {  64,   0, -64},    {  64,   0,  64},    { -64,   0,  64},
    {   0, 127,   0},    { -64,   0, -64},    { -64,   0,  64},    {  64,   0,  64},
    {  64,   0, -64},    {   0,-127,   0},
};
static const MeshFace beacon_faces[12] = {
    {  0,  1,  2,    0,-127,   0, 0x9CD4},
    {  0,  2,  3,    0,-127,   0, 0x9CD4},
    {  1,  0,  4,    0,  57,-114, 0x9CD4},
    {  2,  1,  4,  114,  57,   0, 0x9CD4},
    {  3,  2,  4,    0,  57, 114, 0x9CD4},
    {  0,  3,  4, -114,  57,   0, 0x9CD4},
    {  5,  6,  7,    0, 127,   0, 0x9CD4},
    {  5,  7,  8,    0, 127,   0, 0x9CD4},
    {  6,  5,  9, -114, -57,   0, 0x9CD4},
    {  7,  6,  9,    0, -57, 114, 0x9CD4},
    {  8,  7,  9,  114, -57,   0, 0x9CD4},
    {  5,  8,  9,    0, -57,-114, 0x9CD4},
};
static const Mesh beacon_mesh = { beacon_verts, beacon_faces, 10, 12, 6.000000f, 6.000000f, 0 };

#endif
