/* GENERATED by obj2mesh from examples/hulls/assets/canister.obj — do not edit. */
#ifndef MOTE_MESH_canister_H
#define MOTE_MESH_canister_H
#include "mote_mesh.h"

static const MeshVert canister_verts[8] = {
    {-127,-102,-102},    { 127,-102,-102},    { 127, 102,-102},    {-127, 102,-102},
    {-127,-102, 102},    { 127,-102, 102},    { 127, 102, 102},    {-127, 102, 102},
};
static const MeshFace canister_faces[12] = {
    {  4,  5,  6,    0,   0, 127, 0x9CD4},
    {  4,  6,  7,    0,   0, 127, 0x9CD4},
    {  1,  0,  3,    0,   0,-127, 0x9CD4},
    {  1,  3,  2,    0,   0,-127, 0x9CD4},
    {  5,  1,  2,  127,   0,   0, 0x9CD4},
    {  5,  2,  6,  127,   0,   0, 0x9CD4},
    {  0,  4,  7, -127,   0,   0, 0x9CD4},
    {  0,  7,  3, -127,   0,   0, 0x9CD4},
    {  7,  6,  2,    0, 127,   0, 0x9CD4},
    {  7,  2,  3,    0, 127,   0, 0x9CD4},
    {  0,  1,  5,    0,-127,   0, 0x9CD4},
    {  0,  5,  4,    0,-127,   0, 0x9CD4},
};
static const Mesh canister_mesh = { canister_verts, canister_faces, 8, 12, 1.000000f, 1.509967f, 0 };

#endif
