/* GENERATED by mote bake from random.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound random = mote_sfx_bake(mote, &random_sfx); */
#ifndef MOTE_SFX_random_H
#define MOTE_SFX_random_H
#include "mote_api.h"

static const MoteSfx random_sfx = {
    2,  /* wave */
    0.240051,0,0.19314,0, 0.20755,0.119067,
    0.355087,0.485834, 0.105548,0.287866,0.47821,0.208353,
    0.302344,0,0.830414, 0,0, 0,0, 0.323682,0.053125,
};

#endif
