/* GENERATED by mote bake from denied.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound denied = mote_sfx_bake(mote, &denied_sfx); */
#ifndef MOTE_SFX_denied_H
#define MOTE_SFX_denied_H
#include "mote_api.h"

static const MoteSfx denied_sfx = {
    0,  /* wave */
    0.13,0,-0.02,0, 0.3,0,
    0,0, 0,0.08,0.1,0.1,
    0.8,0,0, 0,0, 0,0, 0,0,
};

#endif
