/* GENERATED by mote bake from denied.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound denied = mote_sfx_bake(mote, &denied_sfx); */
#ifndef MOTE_SFX_denied_H
#define MOTE_SFX_denied_H
#include "mote_api.h"

static const MoteSfx denied_sfx = {
    2,  /* wave */
    0.16,0,-0.08,0, 0.5,0,
    0,0, 0,0.08,0.15,0.14,
    0.8,0,0, 0,0, 0,0, 0.5,-0.3,
};

#endif
