/* GENERATED by mote bake from fuse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound fuse = mote_sfx_bake(mote, &fuse_sfx); */
#ifndef MOTE_SFX_fuse_H
#define MOTE_SFX_fuse_H
#include "mote_api.h"

static const MoteSfx fuse_sfx = {
    1,  /* wave */
    0.22,0,0.34,0, 0.5,0,
    0,0, 0.02,0.2,0.25,0.36,
    0.65,0,0.3, 0,0, 0.25,0.04, 0,0,
};

#endif
