/* GENERATED by mote bake from fuse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound fuse = mote_sfx_bake(mote, &fuse_sfx); */
#ifndef MOTE_SFX_fuse_H
#define MOTE_SFX_fuse_H
#include "mote_api.h"

static const MoteSfx fuse_sfx = {
    2,  /* wave */
    0.3,0,0,0, 0.5,0,
    0,0, 0,0.2,0.4,0.45,
    0.9,0,0, 0,0, 0,0, 0.5,0.3,
};

#endif
