/* GENERATED by mote bake from gate.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound gate = mote_sfx_bake(mote, &gate_sfx); */
#ifndef MOTE_SFX_gate_H
#define MOTE_SFX_gate_H
#include "mote_api.h"

static const MoteSfx gate_sfx = {
    2,  /* wave */
    0.4,0,0.08,0, 0.5,0,
    0.25,0.7, 0.02,0.3,0.2,0.45,
    1,0,0, 0,0, 0.15,0.03, 0.4,0.5,
};

#endif
