/* GENERATED by mote bake from gate.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound gate = mote_sfx_bake(mote, &gate_sfx); */
#ifndef MOTE_SFX_gate_H
#define MOTE_SFX_gate_H
#include "mote_api.h"

static const MoteSfx gate_sfx = {
    2,  /* wave */
    0.24,0,0.04,0, 0.5,0,
    0.3,0.4, 0.05,0.4,0.15,0.55,
    0.8,0,0, 0,0, 0.2,0.02, 0,0,
};

#endif
