/* GENERATED by mote bake from hurt.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound hurt = mote_sfx_bake(mote, &hurt_sfx); */
#ifndef MOTE_SFX_hurt_H
#define MOTE_SFX_hurt_H
#include "mote_api.h"

static const MoteSfx hurt_sfx = {
    3,  /* wave */
    0.2,0,-0.16,0, 0.5,0,
    0,0, 0,0.05,0.4,0.18,
    0.4,-0.06,0.2, 0,0, 0,0, 0,0,
};

#endif
