/* GENERATED by mote bake from pickup.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound pickup = mote_sfx_bake(mote, &pickup_sfx); */
#ifndef MOTE_SFX_pickup_H
#define MOTE_SFX_pickup_H
#include "mote_api.h"

static const MoteSfx pickup_sfx = {
    2,  /* wave */
    0.45,0,0,0, 0.5,0,
    0,0, 0,0.06,0.1,0.2,
    1,0,0, 0,0, 0,0, 0.55,0.45,
};

#endif
