/* GENERATED by mote bake from shot_pulse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_pulse = mote_sfx_bake(mote, &shot_pulse_sfx); */
#ifndef MOTE_SFX_shot_pulse_H
#define MOTE_SFX_shot_pulse_H
#include "mote_api.h"

static const MoteSfx shot_pulse_sfx = {
    1,  /* wave */
    0.32,0,-0.34,0, 0.5,0,
    0,0, 0,0.05,0.3,0.15,
    0.6,-0.08,0.2, 0,0, 0,0, 0,0,
};

#endif
