/* GENERATED by mote bake from shot_venom.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_venom = mote_sfx_bake(mote, &shot_venom_sfx); */
#ifndef MOTE_SFX_shot_venom_H
#define MOTE_SFX_shot_venom_H
#include "mote_api.h"

static const MoteSfx shot_venom_sfx = {
    2,  /* wave */
    0.34,0,0,0, 0.5,0,
    0.15,0.7, 0,0.05,0.2,0.15,
    0.8,0,0, 0,0, 0,0, 0.25,-0.35,
};

#endif
