/* GENERATED by mote bake from shot_pulse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_pulse = mote_sfx_bake(mote, &shot_pulse_sfx); */
#ifndef MOTE_SFX_shot_pulse_H
#define MOTE_SFX_shot_pulse_H
#include "mote_api.h"

static const MoteSfx shot_pulse_sfx = {
    2,  /* wave */
    0.34,0,-0.22,0, 0.5,0,
    0,0, 0,0.04,0.35,0.12,
    0.9,0,0, 0,0, 0,0, 0,0,
};

#endif
