/* GENERATED by mote bake from shot_heavy.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_heavy = mote_sfx_bake(mote, &shot_heavy_sfx); */
#ifndef MOTE_SFX_shot_heavy_H
#define MOTE_SFX_shot_heavy_H
#include "mote_api.h"

static const MoteSfx shot_heavy_sfx = {
    1,  /* wave */
    0.25,0,-0.15,0, 0.5,0,
    0,0, 0,0.08,0.3,0.18,
    0.7,-0.1,0.2, 0,0, 0.1,-0.02, 0,0,
};

#endif
