/* GENERATED by mote bake from shot_void.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_void = mote_sfx_bake(mote, &shot_void_sfx); */
#ifndef MOTE_SFX_shot_void_H
#define MOTE_SFX_shot_void_H
#include "mote_api.h"

static const MoteSfx shot_void_sfx = {
    2,  /* wave */
    0.22,0,-0.06,0, 0.5,0,
    0.2,0.3, 0,0.06,0.2,0.18,
    0.6,0,0, 0,0, 0.3,-0.05, 0,0,
};

#endif
