/* GENERATED by mote bake from shot_fire.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_fire = mote_sfx_bake(mote, &shot_fire_sfx); */
#ifndef MOTE_SFX_shot_fire_H
#define MOTE_SFX_shot_fire_H
#include "mote_api.h"

static const MoteSfx shot_fire_sfx = {
    3,  /* wave */
    0.18,0,-0.06,0, 0.5,0,
    0,0, 0,0.08,0.3,0.22,
    0.3,-0.04,0.2, 0,0, 0,0, 0,0,
};

#endif
