/* GENERATED by mote bake from shot_plasma.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_plasma = mote_sfx_bake(mote, &shot_plasma_sfx); */
#ifndef MOTE_SFX_shot_plasma_H
#define MOTE_SFX_shot_plasma_H
#include "mote_api.h"

static const MoteSfx shot_plasma_sfx = {
    2,  /* wave */
    0.52,0,-0.1,0, 0.5,0,
    0.15,0.5, 0,0.06,0.15,0.14,
    1,0,0, 0,0, 0.08,-0.01, 0.3,0.35,
};

#endif
