/* GENERATED by mote bake from shot_pulse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_pulse = mote_sfx_bake(mote, &shot_pulse_sfx); */
#ifndef MOTE_SFX_shot_pulse_H
#define MOTE_SFX_shot_pulse_H
#include "mote_api.h"

static const MoteSfx shot_pulse_sfx = {
    2,  /* wave */
    0.36,0,-0.1,0, 0.5,0,
    0,0, 0,0.05,0.3,0.11,
    0.85,0,0, 0,0, 0,0, 0.7,0.25,
};

#endif
