/* GENERATED by mote bake from combo.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound combo = mote_sfx_bake(mote, &combo_sfx); */
#ifndef MOTE_SFX_combo_H
#define MOTE_SFX_combo_H
#include "mote_api.h"

static const MoteSfx combo_sfx = {
    1,  /* wave */
    0.5,0,0,0, 0.5,0,
    0,0, 0,0.04,0.25,0.16,
    1,0,0, 0,0, 0,0, 0.7,0.7,
};

#endif
