/* GENERATED by mote bake from die.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound die = mote_sfx_bake(mote, &die_sfx); */
#ifndef MOTE_SFX_die_H
#define MOTE_SFX_die_H
#include "mote_api.h"

static const MoteSfx die_sfx = {
    1,  /* wave */
    0.34,0,-0.3,0, 0.5,0,
    0,0, 0.02,0.08,0.1,0.34,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
