/* GENERATED by mote bake from brick.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound brick = mote_sfx_bake(mote, &brick_sfx); */
#ifndef MOTE_SFX_brick_H
#define MOTE_SFX_brick_H
#include "mote_api.h"

static const MoteSfx brick_sfx = {
    3,  /* wave */
    0.46,0,-0.3,0, 0.5,0,
    0,0, 0,0.01,0.3,0.13,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
