/* GENERATED by mote bake from lose.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound lose = mote_sfx_bake(mote, &lose_sfx); */
#ifndef MOTE_SFX_lose_H
#define MOTE_SFX_lose_H
#include "mote_api.h"

static const MoteSfx lose_sfx = {
    3,  /* wave */
    0.22,0,-0.15,0, 0.5,0,
    0,0, 0,0.12,0.3,0.45,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
