/* GENERATED by mote bake from paddle.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound paddle = mote_sfx_bake(mote, &paddle_sfx); */
#ifndef MOTE_SFX_paddle_H
#define MOTE_SFX_paddle_H
#include "mote_api.h"

static const MoteSfx paddle_sfx = {
    0,  /* wave */
    0.44,0,-0.22,0, 0.5,0,
    0,0, 0,0.01,0.4,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
