/* GENERATED by mote bake from powerup.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound powerup = mote_sfx_bake(mote, &powerup_sfx); */
#ifndef MOTE_SFX_powerup_H
#define MOTE_SFX_powerup_H
#include "mote_api.h"

static const MoteSfx powerup_sfx = {
    1,  /* wave */
    0.3,0,0.22,0, 0.5,0,
    0.22,0.4, 0,0.12,0.2,0.22,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
