/* GENERATED by mote bake from wall.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wall = mote_sfx_bake(mote, &wall_sfx); */
#ifndef MOTE_SFX_wall_H
#define MOTE_SFX_wall_H
#include "mote_api.h"

static const MoteSfx wall_sfx = {
    0,  /* wave */
    0.3,0,-0.16,0, 0.5,0,
    0,0, 0,0.01,0.3,0.09,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
