/* GENERATED by stl2mesh from examples/chess/assets/king_cross.stl — do not edit. */
#ifndef MOTE_MESH_king_cross_H
#define MOTE_MESH_king_cross_H
#include "mote_mesh.h"

static const MeshVert king_cross_v0[16]={{-4,105,-4},{4,127,-4},{4,105,-4},{-4,127,-4},{4,127,4},{4,105,4},{-4,127,4},{-4,105,4},{-11,115,-4},{11,123,-4},{11,115,-4},{-11,123,-4},{11,123,4},{11,115,4},{-11,123,4},{-11,115,4},};
static const MeshFace king_cross_f0[24]={
  {0,1,2, 0,0,-127},
  {0,3,1, 0,0,-127},
  {2,4,5, 127,0,0},
  {2,1,4, 127,0,0},
  {5,6,7, 0,0,127},
  {5,4,6, 0,0,127},
  {7,3,0, -127,0,0},
  {7,6,3, -127,0,0},
  {3,4,1, 0,127,0},
  {3,6,4, 0,127,0},
  {7,2,5, 0,-127,0},
  {7,0,2, 0,-127,0},
  {8,9,10, 0,0,-127},
  {8,11,9, 0,0,-127},
  {10,12,13, 127,0,0},
  {10,9,12, 127,0,0},
  {13,14,15, 0,0,127},
  {13,12,14, 0,0,127},
  {15,11,8, -127,0,0},
  {15,14,11, -127,0,0},
  {11,12,9, 0,127,0},
  {11,14,12, 0,127,0},
  {15,10,13, 0,-127,0},
  {15,8,10, 0,-127,0},
};
static const Mesh king_cross_chunks[1]={
  {king_cross_v0,king_cross_f0,0,16,24,0xE6F8,1.600000f,1.601562f,0},
};
#define king_cross_NCHUNKS 1
#define king_cross_TRIS 24
static const MoteModel king_cross = { king_cross_chunks, king_cross_NCHUNKS, king_cross_TRIS };  /* draw with mote_model_draw(mote, &king_cross, pos) */

#endif
