/* GENERATED by mote bake (img2tex) from ammo.png — do not edit. */
#ifndef MOTE_IMG_ammo_H
#define MOTE_IMG_ammo_H
#include "mote_2d.h"

static const uint16_t ammo_pal[7] = { 0x5aa9,0xaa86,0xc618,0xf809,0xf81f,0xfd00,0xff9d };
static const uint8_t ammo_idx[96] = {
  68,68,68,98,68,68,68,68,68,68,100,68,68,68,70,32,68,68,68,100,68,70,36,68,68,68,65,36,68,68,54,68,
  68,66,4,68,68,68,20,68,66,99,83,68,98,4,66,100,66,97,68,68,38,53,52,68,70,36,64,38,38,22,68,68,
  68,67,100,68,68,64,36,68,65,98,68,68,68,70,36,68,68,66,100,68,68,36,68,68,68,66,68,68,68,70,68,68,
};
static const MoteImage ammo_img = { 0, 24, 8, 0xF81F, 0, 1, ammo_idx, ammo_pal };  /* 4bpp indexed, 7 colours */
#define ammo_W 24
#define ammo_H 8

#endif