/* GENERATED by mote bake (img2tex) from chest_wood.png — do not edit. */
#ifndef MOTE_IMG_chest_wood_H
#define MOTE_IMG_chest_wood_H
#include "mote_2d.h"

static const uint16_t chest_wood_pal[7] = { 0x194a,0x5aa9,0xaa86,0xc618,0xf81f,0xfd00,0xff9d };
static const uint8_t chest_wood_idx[64] = {
  68,68,68,68,68,70,52,68,68,51,17,68,66,33,18,36,70,82,34,20,32,0,0,2,53,34,34,33,32,0,0,2,
  48,6,48,0,32,0,0,2,18,35,18,32,18,33,18,32,18,34,34,32,18,34,34,32,1,17,0,0,1,17,0,0,
};
static const MoteImage chest_wood_img = { 0, 16, 8, 0xF81F, 0, 1, chest_wood_idx, chest_wood_pal };  /* 4bpp indexed, 7 colours */
#define chest_wood_W 16
#define chest_wood_H 8

#endif