/* GENERATED by mote bake (img2tex) from items_scroll_bomb.png — do not edit. */
#ifndef MOTE_IMG_items_scroll_bomb_H
#define MOTE_IMG_items_scroll_bomb_H
#include "mote_2d.h"

static const uint16_t items_scroll_bomb_pal[8] = { 0x194a,0x5aa9,0xaa86,0xc618,0xf809,0xf81f,0xfe75,0xff9d };
static const uint8_t items_scroll_bomb_idx[128] = {
  85,82,34,37,85,85,85,115,34,34,34,37,85,85,87,49,34,38,102,85,85,85,82,53,86,102,98,85,85,85,37,85,
  86,34,102,101,83,114,85,85,86,102,98,101,55,39,85,85,85,98,102,101,82,115,85,85,85,102,101,85,85,53,85,85,
  85,85,83,69,85,0,0,52,85,85,53,85,80,112,0,5,85,0,0,85,7,119,0,0,80,119,0,5,0,112,0,0,
  80,112,0,5,0,0,0,0,80,0,0,5,0,0,0,0,80,0,0,5,80,0,0,5,85,0,0,85,85,0,0,85,
};
static const MoteImage items_scroll_bomb_img = { 0, 16, 16, 0xF81F, 0, 1, items_scroll_bomb_idx, items_scroll_bomb_pal };  /* 4bpp indexed, 8 colours */
#define items_scroll_bomb_W 16
#define items_scroll_bomb_H 16

#endif