/*
 * chess — 3D chess on Mote. Board state + AI come from the vendored Chal engine
 * (chal.c). Pieces are STL models (tools/gen_chess_stl.py -> stl2mesh -> the *.h
 * here), drawn as MoteModels and tinted per side at draw time; the king & queen
 * are two parts so their topper takes a contrasting colour. You play White (near
 * side); Black is the Chal search. Moves animate (lift, glide, drop). Orbit the
 * camera with LB/RB + the shoulder modifiers.
 *
 * Controls: D-pad = move cursor · A = pick up / drop · B = cancel selection
 *           LB/RB = orbit camera · UP/DOWN while holding B = pitch/zoom · MENU = quit
 *
 * Style note — uses scene_camera(), so objects are added at WORLD coordinates
 * (no v3_sub(pos, cam) anywhere), and mote_draw_ex() builds the MoteObject.
 */
#include "mote_api.h"
#include "chal.h"
#include "mote_build.h"
#include <math.h>

#include "icon.h"
MOTE_GAME_MODULE();
#ifdef MOTE_MODULE_BUILD
#include "mote_module.h"
MOTE_MODULE_HEADER();
#endif

/* Piece geometry: STL models generated by tools/gen_chess_stl.py and baked with
 * tools/stl2mesh (origin kept at the base). The king & queen are two parts so the
 * topper takes the inverted colour; STL carries no colour, so the game tints each
 * part per side at draw time (mote_model_draw_tint). */
#include "pawn.h"
#include "knight.h"
#include "bishop.h"
#include "rook.h"
#include "queen_body.h"
#include "queen_crown.h"
#include "king_body.h"
#include "king_cross.h"

#define TAU 6.2831853f

/* Chal time hook, routed through mote->micros (chal.c calls chess_time_ms). */
int64_t chess_time_ms(void) {
    return (int64_t)(mote->micros() / 1000ull);
}

/* ============================================================
 * Staunton pieces — baked STL models, tinted per side
 * ============================================================ */

/* Clamp 0..1 float RGB to an RGB565 colour. */
static uint16_t shade(float r, float g, float b) {
    int R = (int)(r * 255), G = (int)(g * 255), B = (int)(b * 255);
    if (R > 255) R = 255;
    if (G > 255) G = 255;
    if (B > 255) B = 255;
    return MOTE_RGB565(R, G, B);
}

/* Per-type body + optional topper, indexed by CHAL_PAWN..CHAL_KING (1..6). The
 * king/queen toppers are separate models so they can take a contrasting colour. */
static const MoteModel *piece_body[7] = {
    0, &pawn, &knight, &bishop, &rook, &queen_body, &king_body,
};
static const MoteModel *piece_top[7] = {
    0, 0, 0, 0, 0, &queen_crown, &king_cross,
};

/* Body colour for a side; the topper takes the inverted colour. */
static uint16_t side_colour(int color) {
    return color == CHAL_WHITE ? shade(0.88f, 0.86f, 0.76f)    /* ivory    */
                               : shade(0.26f, 0.22f, 0.26f);   /* charcoal */
}
static uint16_t accent_colour(int color) { return side_colour(color ^ 1); }

/* Draw a piece: body in its side colour, plus the king/queen topper inverted.
 * Both parts baked with origin kept at the base, so they overlay at one position. */
static void draw_piece(int type, int color, Vec3 pos, Mat3 basis) {
    mote_model_draw_tint(mote, piece_body[type], pos, basis, 1.0f, side_colour(color));
    if (piece_top[type])
        mote_model_draw_tint(mote, piece_top[type], pos, basis, 1.0f, accent_colour(color));
}

/* ============================================================
 * Board (9x9 vertex grid -> 64 coloured quads) + square highlights
 * ============================================================ */
static MeshVert board_verts[81];
static MeshFace board_faces[128];
static uint16_t board_fcol[128];     /* per-face colour (alternating squares) */
static Mesh     board_mesh;

static void build_board(void) {
    for (int r = 0; r <= 8; r++) {
        for (int f = 0; f <= 8; f++) {
            MeshVert *v = &board_verts[r * 9 + f];
            v->x = (int8_t)((f - 4) * 127 / 4);
            v->y = 0;
            v->z = (int8_t)((r - 4) * 127 / 4);
        }
    }

    int nf = 0;
    for (int r = 0; r < 8; r++) {
        for (int f = 0; f < 8; f++) {
            int a = r * 9 + f, b = a + 1, c = a + 9, d = c + 1;
            uint16_t col = ((r + f) & 1) ? shade(0.20f, 0.42f, 0.28f)
                                         : shade(0.74f, 0.78f, 0.66f);
            board_fcol[nf] = col; board_faces[nf++] = (MeshFace){(uint8_t)a, (uint8_t)c, (uint8_t)b, 0, 127, 0};
            board_fcol[nf] = col; board_faces[nf++] = (MeshFace){(uint8_t)b, (uint8_t)c, (uint8_t)d, 0, 127, 0};
        }
    }

    board_mesh.verts = board_verts;
    board_mesh.faces = board_faces;
    board_mesh.face_colors = board_fcol;
    board_mesh.nverts = 81;
    board_mesh.nfaces = nf;
    board_mesh.scale = 4.0f;
    board_mesh.bound_r = 7.0f;
}

/* Flat square-ring highlight (a box around a square) — cursor + selection. */
static MeshVert cursor_verts[8], select_verts[8];
static MeshFace cursor_faces[8], select_faces[8];
static Mesh     cursor_mesh, select_mesh;

static void build_frame(MeshVert *v, MeshFace *f, Mesh *m, uint16_t col) {
    int8_t outer = (int8_t)(0.47f * 127);
    int8_t inner = (int8_t)(0.36f * 127);
    int8_t y     = (int8_t)(0.03f * 127);

    v[0] = (MeshVert){(int8_t)-outer, y, (int8_t)-outer};
    v[1] = (MeshVert){outer,          y, (int8_t)-outer};
    v[2] = (MeshVert){outer,          y, outer};
    v[3] = (MeshVert){(int8_t)-outer, y, outer};
    v[4] = (MeshVert){(int8_t)-inner, y, (int8_t)-inner};
    v[5] = (MeshVert){inner,          y, (int8_t)-inner};
    v[6] = (MeshVert){inner,          y, inner};
    v[7] = (MeshVert){(int8_t)-inner, y, inner};

    int nf = 0;
    for (int i = 0; i < 4; i++) {
        int j = (i + 1) & 3;
        int o0 = i, o1 = j, i0 = 4 + i, i1 = 4 + j;
        f[nf++] = (MeshFace){(uint8_t)o0, (uint8_t)i1, (uint8_t)o1, 0, 127, 0};
        f[nf++] = (MeshFace){(uint8_t)o0, (uint8_t)i0, (uint8_t)i1, 0, 127, 0};
    }

    m->verts = v;
    m->faces = f;
    m->nverts = 8;
    m->nfaces = 8;
    m->color = col;
    m->scale = 1.0f;
    m->bound_r = 0.9f;
}

/* ============================================================
 * Game state
 * ============================================================ */

static void *dyn_buffer, *tt_buffer;

static chal_move_info_t legal_moves[220];
static int legal_move_count;

static int cursor_file = 4, cursor_rank = 6;   /* rank 7 = white back row */
static int has_selection = 0;
static int select_file, select_rank;

enum { ST_PLAYER, ST_ANIM, ST_THINK, ST_SEARCH, ST_OVER };
static int state = ST_PLAYER;

static int result = 0;                 /* 0 none, 1 white mates, 2 black mates, 3 draw */

/* camera orbit */
static float cam_yaw = 0.0f, cam_pitch = 0.85f, cam_dist = 11.0f, gallery_spin = 0.0f;
static int   showing_gallery = 0;

/* move animation */
static float anim_t;
static Vec3  anim_from, anim_to;
static int   anim_type, anim_color, anim_active, anim_to_rank, anim_to_file;

static Vec3 square_world(int rank, int file) {
    return v3((float)(file - 4) + 0.5f, 0.0f, (float)(rank - 4) + 0.5f);
}

/* Convert (rank, file) to the engine's 0x88 square index. */
static uint8_t to_sq88(int rank, int file) {
    return (uint8_t)(((7 - rank) << 4) | file);
}

static void refresh_moves(void) {
    legal_move_count = chal_get_legal_moves(legal_moves, 220);
}

static void check_end(void) {
    if (chal_is_checkmate())      result = (chal_get_side() == CHAL_WHITE) ? 2 : 1;
    else if (chal_is_stalemate()) result = 3;
    if (result) state = ST_OVER;
}

static void start_anim(int from_rank, int from_file, int to_rank, int to_file,
                       int type, int color) {
    anim_from = square_world(from_rank, from_file);
    anim_to = square_world(to_rank, to_file);
    anim_type = type;
    anim_color = color;
    anim_t = 0.0f;
    anim_active = 1;
    anim_to_rank = to_rank;
    anim_to_file = to_file;
}

static void g_init(void) {
    mote->scene_set_background(MOTE_RGB565(36, 42, 60));
    mote->scene_set_sun(v3_norm(v3(0.4f, 1.0f, 0.3f)));

    dyn_buffer = mote->alloc((uint32_t)chal_get_dynamic_size());
    chal_set_dynamic_buffer(dyn_buffer);
    chal_init();

    int tt_count = 256;
    tt_buffer = mote->alloc((uint32_t)(tt_count * chal_get_tt_entry_size()));
    chal_set_tt(tt_buffer, tt_count);
    chal_new_game();

    build_board();                 /* pieces are baked STL models (see piece_body/piece_top) */
    refresh_moves();
    build_frame(cursor_verts, cursor_faces, &cursor_mesh, shade(1.0f, 0.92f, 0.30f));   /* cursor: yellow */
    build_frame(select_verts, select_faces, &select_mesh, shade(0.35f, 0.65f, 1.0f));   /* selection: blue */
}

static Vec3 cam_pos, cam_target;
static Mat3 cam_basis;
static const Mat3 ROT180 = {{ {-1,0,0}, {0,1,0}, {0,0,-1} }};

/* Find a legal move from->to; writes its promotion piece. Returns 1 if found. */
static int find_move(int from_rank, int from_file, int to_rank, int to_file, int *promo) {
    uint8_t from = to_sq88(from_rank, from_file);
    uint8_t to = to_sq88(to_rank, to_file);
    for (int i = 0; i < legal_move_count; i++) {
        if (legal_moves[i].from == from && legal_moves[i].to == to) {
            *promo = legal_moves[i].promo;
            return 1;
        }
    }
    return 0;
}

/* Read the piece on a square; writes type/color. Returns 0 if empty. */
static int piece_at(int rank, int file, int *type, int *color) {
    int p = chal_get_piece(rank, file);
    if (!p) return 0;
    *type = p & 7;
    *color = p >> 3;
    return 1;
}

static void play(int from_rank, int from_file, int to_rank, int to_file, int promo) {
    int type, color;
    piece_at(from_rank, from_file, &type, &color);
    chal_play_move(to_sq88(from_rank, from_file), to_sq88(to_rank, to_file), promo);
    start_anim(from_rank, from_file, to_rank, to_file, type, color);
    refresh_moves();
    state = ST_ANIM;
}

/* Pick the mesh basis for a piece (white knights face the other way). */
static Mat3 piece_basis(int type, int color) {
    return (type == CHAL_KNIGHT && color == CHAL_WHITE) ? ROT180 : m3_identity();
}

static void g_update(float dt) {
    const MoteInput *in = mote->input();

    /* Camera: hold LB + D-pad UP/DOWN = ZOOM; hold RB + D-pad = PAN (LR yaw,
     * UD pitch). Hold BOTH shoulders to peek the piece gallery. */
    int lb = mote_pressed(in, MOTE_BTN_LB);
    int rb = mote_pressed(in, MOTE_BTN_RB);
    int gallery = lb && rb;
    showing_gallery = gallery;

    if (!gallery && lb) {
        if (mote_pressed(in, MOTE_BTN_UP))    cam_dist -= 9.0f * dt;   /* zoom */
        if (mote_pressed(in, MOTE_BTN_DOWN))  cam_dist += 9.0f * dt;
        if (mote_pressed(in, MOTE_BTN_LEFT))  cam_yaw  -= 1.6f * dt;   /* pan L/R */
        if (mote_pressed(in, MOTE_BTN_RIGHT)) cam_yaw  += 1.6f * dt;
    }
    if (!gallery && rb) {
        if (mote_pressed(in, MOTE_BTN_LEFT))  cam_yaw   -= 1.6f * dt;
        if (mote_pressed(in, MOTE_BTN_RIGHT)) cam_yaw   += 1.6f * dt;
        if (mote_pressed(in, MOTE_BTN_UP))    cam_pitch += 1.1f * dt;
        if (mote_pressed(in, MOTE_BTN_DOWN))  cam_pitch -= 1.1f * dt;
    }
    cam_pitch = mote_clampf(cam_pitch, 0.18f, 1.45f);
    cam_dist = mote_clampf(cam_dist, 4.5f, 20.0f);
    gallery_spin += dt * 0.8f;

    if (state == ST_PLAYER && !lb && !rb) {
        /* file L/R is screen-relative: at the default view +x (file 7) is screen-left */
        if (mote_just_pressed(in, MOTE_BTN_LEFT)  && cursor_file < 7) cursor_file++;
        if (mote_just_pressed(in, MOTE_BTN_RIGHT) && cursor_file > 0) cursor_file--;
        if (mote_just_pressed(in, MOTE_BTN_UP)    && cursor_rank > 0) cursor_rank--;
        if (mote_just_pressed(in, MOTE_BTN_DOWN)  && cursor_rank < 7) cursor_rank++;

        if (mote_just_pressed(in, MOTE_BTN_A)) {
            int type, color;
            if (!has_selection) {
                if (piece_at(cursor_rank, cursor_file, &type, &color) && color == CHAL_WHITE) {
                    has_selection = 1;
                    select_file = cursor_file;
                    select_rank = cursor_rank;
                }
            } else {
                int promo;
                if (find_move(select_rank, select_file, cursor_rank, cursor_file, &promo)) {
                    has_selection = 0;
                    play(select_rank, select_file, cursor_rank, cursor_file, promo);
                } else if (piece_at(cursor_rank, cursor_file, &type, &color) && color == CHAL_WHITE) {
                    select_file = cursor_file;
                    select_rank = cursor_rank;
                } else {
                    has_selection = 0;
                }
            }
        }
    }

    if (gallery) {   /* ---- piece gallery ---- */
        cam_pos = v3(0, 1.7f, 5.6f);
        cam_target = v3(0, 0.42f, 0);
        Vec3 fwd = v3_norm(v3_sub(cam_target, cam_pos));
        Vec3 right = v3_norm(v3_cross(v3(0, 1, 0), fwd));
        cam_basis.r[0] = right;
        cam_basis.r[1] = v3_cross(fwd, right);
        cam_basis.r[2] = fwd;
        mote->scene_camera(&cam_basis, cam_pos, 62.0f);

        Mat3 spin;
        float cs = cosf(gallery_spin), sn = sinf(gallery_spin);
        spin.r[0] = v3(cs, 0, sn);
        spin.r[1] = v3(0, 1, 0);
        spin.r[2] = v3(-sn, 0, cs);

        int order[6] = {CHAL_PAWN, CHAL_KNIGHT, CHAL_BISHOP, CHAL_ROOK, CHAL_QUEEN, CHAL_KING};
        for (int i = 0; i < 6; i++) {
            Vec3 pos = v3((i - 2.5f) * 1.28f, 0, 0);
            draw_piece(order[i], CHAL_WHITE, pos, spin);
        }
        return;
    }

    if (state == ST_ANIM) {
        anim_t += dt / 0.45f;
        if (anim_t >= 1.0f) {
            anim_active = 0;
            check_end();
            if (state != ST_OVER)
                state = (anim_color == CHAL_WHITE) ? ST_THINK : ST_PLAYER;
        }
    } else if (state == ST_THINK) {
        state = ST_SEARCH;            /* render one "thinking" frame first */
    } else if (state == ST_SEARCH) {
        chal_move_info_t m = chal_search_best_move(6, 700);
        if (m.from == 0x80) {
            check_end();
            state = ST_OVER;
        } else {
            int to_rank = 7 - (m.to >> 4), to_file = m.to & 7;
            int from_rank = 7 - (m.from >> 4), from_file = m.from & 7;
            play(from_rank, from_file, to_rank, to_file, m.promo);
        }
    }

    /* ---- camera (orbit around the board centre) ---- */
    cam_target = v3(0, 0.3f, 0);
    cam_pos = v3(cam_target.x + sinf(cam_yaw) * cosf(cam_pitch) * cam_dist,
                 cam_target.y + sinf(cam_pitch) * cam_dist,
                 cam_target.z + cosf(cam_yaw) * cosf(cam_pitch) * cam_dist);
    cam_basis = mote_camera_look(cam_pos, cam_target);

    mote->scene_camera(&cam_basis, cam_pos, 58.0f);

    /* board */
    mote_draw(mote, &board_mesh, v3(0, 0, 0));

    /* settled pieces (skip the one currently animating to its destination) */
    for (int r = 0; r < 8; r++) {
        for (int f = 0; f < 8; f++) {
            if (anim_active && r == anim_to_rank && f == anim_to_file) continue;
            int type, color;
            if (!piece_at(r, f, &type, &color)) continue;
            draw_piece(type, color, square_world(r, f), piece_basis(type, color));
        }
    }

    /* animating piece: lift in an arc and glide to its destination */
    if (anim_active) {
        float t = anim_t;
        float lift = sinf(t * 3.14159f) * 0.6f;
        Vec3 pos = v3(anim_from.x + (anim_to.x - anim_from.x) * t,
                      anim_from.y + lift,
                      anim_from.z + (anim_to.z - anim_from.z) * t);
        draw_piece(anim_type, anim_color, pos, piece_basis(anim_type, anim_color));
    }

    /* cursor + selection markers */
    if (state == ST_PLAYER) {
        mote_draw(mote, &cursor_mesh, square_world(cursor_rank, cursor_file));
        if (has_selection)
            mote_draw(mote, &select_mesh, square_world(select_rank, select_file));
    }
}

static void g_overlay(uint16_t *fb) {
    if (state == ST_OVER) {
        const char *msg = result == 1 ? "WHITE WINS" : result == 2 ? "BLACK WINS" : "DRAW";
        mote->text(fb, msg, 38, 58, MOTE_RGB565(255, 240, 120));
        return;
    }
    if (showing_gallery) {
        mote->text(fb, "PIECE GALLERY", 30, 4, MOTE_RGB565(230, 220, 160));
        mote->text(fb, "PAWN KNT BSH ROOK Q K", 2, 118, MOTE_RGB565(200, 210, 225));
        return;
    }
    if (state == ST_THINK || state == ST_SEARCH)
        mote->text(fb, "BLACK THINKING", 26, 4, MOTE_RGB565(230, 180, 120));
    else
        mote->text(fb, has_selection ? "A DROP  LB ZOOM RB PAN" : "A PICK  LB ZOOM RB PAN",
                   4, 4, MOTE_RGB565(210, 220, 235));
    if (chal_is_in_check() && state == ST_PLAYER)
        mote->text(fb, "CHECK", 48, 118, MOTE_RGB565(255, 90, 90));
}

static const MoteGameVtbl k_vtbl = {
    .init = g_init, .update = g_update, .overlay = g_overlay,
    .config = { .max_tris = 5100, .max_spheres = 8, .depth = 1 },   /* no physics, no splats */
};
static const MoteGameVtbl *mote_game_vtbl(void) { return &k_vtbl; }
