/* GENERATED by mote bake (img2tex) from ball.png — do not edit. */
#ifndef MOTE_IMG_ball_H
#define MOTE_IMG_ball_H
#include "mote_2d.h"

static const uint16_t ball_pal[7] = { 0x39ca,0x5331,0x6c53,0x8515,0x8d56,0xc6fa,0xf81f };
static const uint8_t ball_idx[25] = {
  102,102,102,102,99,66,6,98,84,66,6,36,68,32,97,52,33,6,1,33,6,102,0,6,96,
};
static const MoteImage ball_img = { 0, 7, 7, 0xF81F, 0, 1, ball_idx, ball_pal };  /* 4bpp indexed, 7 colours */
#define ball_W 7
#define ball_H 7

#endif