/* GENERATED by mote bake (img2tex) from banner2.png — do not edit. */
#ifndef MOTE_IMG_banner2_H
#define MOTE_IMG_banner2_H
#include "mote_2d.h"

static const uint16_t banner2_pal[6] = { 0x6acc,0x94f4,0xa575,0xae17,0xd73c,0xf81f };
static const uint8_t banner2_idx[91] = {
  0,34,34,34,34,34,32,0,34,34,34,34,34,5,0,34,34,34,34,34,5,0,34,34,34,34,34,32,0,34,34,34,
  34,34,32,0,36,34,34,34,36,32,0,34,50,34,34,50,0,80,2,35,34,35,32,5,85,0,34,50,50,0,85,85,
  80,2,36,32,5,85,85,85,0,18,0,85,85,85,85,80,0,5,85,85,85,85,85,0,85,85,85,
};
static const MoteImage banner2_img = { 0, 14, 13, 0xF81F, 0, 1, banner2_idx, banner2_pal };  /* 4bpp indexed, 6 colours */
#define banner2_W 14
#define banner2_H 13

#endif