/* GENERATED by mote bake (img2tex) from banner2h.png — do not edit. */
#ifndef MOTE_IMG_banner2h_H
#define MOTE_IMG_banner2h_H
#include "mote_2d.h"

static const uint16_t banner2h_pal[7] = { 0x6acc,0x8472,0x94f4,0xa575,0xae17,0xd73c,0xf81f };
static const uint8_t banner2h_idx[91] = {
  96,51,51,51,51,51,48,96,51,51,51,51,51,54,96,51,51,51,51,51,54,96,51,51,51,51,51,48,96,51,51,51,
  51,51,48,96,53,51,51,51,53,48,96,51,67,51,51,67,48,96,3,52,51,52,51,6,102,0,51,67,67,48,102,102,
  96,3,53,51,6,102,102,102,0,35,32,102,102,102,102,96,1,6,102,102,102,102,102,0,102,102,102,
};
static const MoteImage banner2h_img = { 0, 14, 13, 0xF81F, 0, 1, banner2h_idx, banner2h_pal };  /* 4bpp indexed, 7 colours */
#define banner2h_W 14
#define banner2h_H 13

#endif