/* GENERATED by mote bake from boom.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boom = mote_sfx_bake(mote, &boom_sfx); */
#ifndef MOTE_SFX_boom_H
#define MOTE_SFX_boom_H
#include "mote_api.h"

static const MoteSfx boom_sfx = {
    3,  /* wave */
    0.16,0,-0.12,0, 0.5,0,
    0,0, 0,0.16,0.5,0.42,
    0.6,-0.15,0.25, 0,0, 0.15,-0.02, 0,0,
};

#endif
