/* GENERATED by mote bake from bosshit.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound bosshit = mote_sfx_bake(mote, &bosshit_sfx); */
#ifndef MOTE_SFX_bosshit_H
#define MOTE_SFX_bosshit_H
#include "mote_api.h"

static const MoteSfx bosshit_sfx = {
    0,  /* wave */
    0.16,0,-0.1,0, 0.35,0,
    0,0, 0,0.08,0.5,0.18,
    0.6,0,0.15, 0,0, 0,0, 0,0,
};

#endif
