/* GENERATED by mote bake from boxh.anims — edit the .anims/sheet, not this. */
#ifndef MOTE_ANIM_boxh_H
#define MOTE_ANIM_boxh_H
#include "mote_anim.h"

static const uint16_t boxh_pal[7] = { 0x39ca,0xbb0d,0xd42f,0xdcf1,0xe5b3,0xefbe,0xf81f };
static const uint8_t boxh_idx[108] = {
  102,0,0,0,0,6,102,85,85,85,85,86,96,68,68,68,34,32,101,85,85,85,85,85,96,32,0,2,0,0,101,85,
  85,85,85,85,96,64,34,4,0,0,101,85,85,85,85,85,96,67,50,3,1,0,101,85,85,85,85,85,96,66,32,4,
  1,0,101,85,85,85,85,85,96,0,0,0,0,0,101,85,85,85,85,85,96,51,68,52,33,0,101,85,85,85,85,85,
  102,102,102,102,102,102,102,102,102,102,102,102,
};
static const MoteImage boxh_img = { 0, 24, 9, 0xF81F, 0, 1, boxh_idx, boxh_pal };  /* 4bpp indexed, 7 colours */
static const MoteAnimSheet boxh_sheet = { &boxh_img, 12, 9 };

static const MoteAnimFrame boxh_idle_fr[1] = {
  {0,100,0},
};
static const MoteAnimClip boxh_idle = { "idle", boxh_idle_fr, 1, 1, 0, 0 };

static const MoteAnimFrame boxh_hit_fr[1] = {
  {1,100,0},
};
static const MoteAnimClip boxh_hit = { "hit", boxh_hit_fr, 1, 0, 0, 0 };

#endif