/* GENERATED by mote bake from break.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound break = mote_sfx_bake(mote, &break_sfx); */
#ifndef MOTE_SFX_break_H
#define MOTE_SFX_break_H
#include "mote_api.h"

static const MoteSfx break_sfx = {
    3,  /* wave */
    0.3,0,-0.24,0, 0.5,0,
    0,0, 0,0.05,0.3,0.14,
    0.6,-0.12,0.1, 0,0, 0,0, 0,0,
};

#endif
