/* GENERATED by mote bake from cannon.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound cannon = mote_sfx_bake(mote, &cannon_sfx); */
#ifndef MOTE_SFX_cannon_H
#define MOTE_SFX_cannon_H
#include "mote_api.h"

static const MoteSfx cannon_sfx = {
    3,  /* wave */
    0.12,0,-0.08,0, 0.5,0,
    0,0, 0,0.08,0.6,0.26,
    0.5,-0.1,0.2, 0,0, 0,0, 0,0,
};

#endif
