/* GENERATED by mote bake from door.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound door = mote_sfx_bake(mote, &door_sfx); */
#ifndef MOTE_SFX_door_H
#define MOTE_SFX_door_H
#include "mote_api.h"

static const MoteSfx door_sfx = {
    1,  /* wave */
    0.11,0,0.06,0, 0.5,0,
    0.25,0.3, 0.05,0.2,0,0.22,
    0.55,0,0.1, 0,0, 0,0, 0,0,
};

#endif
