/* GENERATED by mote bake from floorup.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound floorup = mote_sfx_bake(mote, &floorup_sfx); */
#ifndef MOTE_SFX_floorup_H
#define MOTE_SFX_floorup_H
#include "mote_api.h"

static const MoteSfx floorup_sfx = {
    0,  /* wave */
    0.3,0,0.1,0, 0.45,0,
    0,0, 0,0.18,0.3,0.2,
    1,0,0, 0,0, 0,0, 0.28,0.09,
};

#endif
