/* GENERATED by mote bake from fuse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound fuse = mote_sfx_bake(mote, &fuse_sfx); */
#ifndef MOTE_SFX_fuse_H
#define MOTE_SFX_fuse_H
#include "mote_api.h"

static const MoteSfx fuse_sfx = {
    3,  /* wave */
    0.62,0,0,0, 0.5,0,
    0,0, 0,0.12,0,0.1,
    0.5,0,0.2, 0.3,0, 0,0, 0,0,
};

#endif
