/* GENERATED by mote bake from heart.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound heart = mote_sfx_bake(mote, &heart_sfx); */
#ifndef MOTE_SFX_heart_H
#define MOTE_SFX_heart_H
#include "mote_api.h"

static const MoteSfx heart_sfx = {
    2,  /* wave */
    0.42,0,0.22,0, 0.5,0,
    0,0, 0,0.1,0.2,0.24,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
