/* GENERATED by mote bake from hitpig.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound hitpig = mote_sfx_bake(mote, &hitpig_sfx); */
#ifndef MOTE_SFX_hitpig_H
#define MOTE_SFX_hitpig_H
#include "mote_api.h"

static const MoteSfx hitpig_sfx = {
    0,  /* wave */
    0.24,0,-0.2,0, 0.5,0,
    0,0, 0,0.05,0.5,0.14,
    0.7,-0.05,0.15, 0,0, 0,0, 0,0,
};

#endif
