/* GENERATED by mote bake from jump.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound jump = mote_sfx_bake(mote, &jump_sfx); */
#ifndef MOTE_SFX_jump_H
#define MOTE_SFX_jump_H
#include "mote_api.h"

static const MoteSfx jump_sfx = {
    0,  /* wave */
    0.32,0,0.18,0, 0.4,0,
    0,0, 0,0.06,0.2,0.1,
    0.9,0,0, 0,0, 0,0, 0,0,
};

#endif
