/* GENERATED by mote bake from kinghurt.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound kinghurt = mote_sfx_bake(mote, &kinghurt_sfx); */
#ifndef MOTE_SFX_kinghurt_H
#define MOTE_SFX_kinghurt_H
#include "mote_api.h"

static const MoteSfx kinghurt_sfx = {
    0,  /* wave */
    0.2,0,-0.26,0, 0.3,0,
    0,0, 0,0.08,0.4,0.2,
    0.75,0,0, 0,0, 0,0, 0,0,
};

#endif
