/* GENERATED by assets/extract_kp.py — sizes/anchors for the packed sheets.
 * Regenerate with: python3 assets/extract_kp.py (then mote bake). */
#ifndef KP_META_H
#define KP_META_H
/* king: cell 52x29, anchor=(26,22), ref body 18x13 */
#define KP_KING_CW   52
#define KP_KING_CH   29
#define KP_KING_AX   26
#define KP_KING_AY   22
#define KP_KING_BW   18
#define KP_KING_BH   13
/* kingpig: cell 20x15, anchor=(10,14), ref body 9x10 */
#define KP_KINGPIG_CW   20
#define KP_KINGPIG_CH   15
#define KP_KINGPIG_AX   10
#define KP_KINGPIG_AY   14
#define KP_KINGPIG_BW   9
#define KP_KINGPIG_BH   10
/* pig: cell 20x15, anchor=(10,14), ref body 9x8 */
#define KP_PIG_CW   20
#define KP_PIG_CH   15
#define KP_PIG_AX   10
#define KP_PIG_AY   14
#define KP_PIG_BW   9
#define KP_PIG_BH   8
/* pigbox: cell 16x16, anchor=(8,15), ref body 10x13 */
#define KP_PIGBOX_CW   16
#define KP_PIGBOX_CH   16
#define KP_PIGBOX_AX   8
#define KP_PIGBOX_AY   15
#define KP_PIGBOX_BW   10
#define KP_PIGBOX_BH   13
/* pigbomb: cell 14x14, anchor=(7,13), ref body 11x10 */
#define KP_PIGBOMB_CW   14
#define KP_PIGBOMB_CH   14
#define KP_PIGBOMB_AX   7
#define KP_PIGBOMB_AY   13
#define KP_PIGBOMB_BW   11
#define KP_PIGBOMB_BH   10
/* pighide: cell 14x11, anchor=(7,10), ref body 9x8 */
#define KP_PIGHIDE_CW   14
#define KP_PIGHIDE_CH   11
#define KP_PIGHIDE_AX   7
#define KP_PIGHIDE_AY   10
#define KP_PIGHIDE_BW   9
#define KP_PIGHIDE_BH   8
/* pigmatch: cell 14x10, anchor=(7,9), ref body 10x8 */
#define KP_PIGMATCH_CW   14
#define KP_PIGMATCH_CH   10
#define KP_PIGMATCH_AX   7
#define KP_PIGMATCH_AY   9
#define KP_PIGMATCH_BW   10
#define KP_PIGMATCH_BH   8
/* box: cell 12x9, anchor=(6,8), ref body 10x8 */
#define KP_BOX_CW   12
#define KP_BOX_CH   9
#define KP_BOX_AX   6
#define KP_BOX_AY   8
#define KP_BOX_BW   10
#define KP_BOX_BH   8
/* bomb: cell 12x11, anchor=(6,7), ref body 6x8 */
#define KP_BOMB_CW   12
#define KP_BOMB_CH   11
#define KP_BOMB_AX   6
#define KP_BOMB_AY   7
#define KP_BOMB_BW   6
#define KP_BOMB_BH   8
/* boom: cell 26x28, anchor=(13,15), ref body 11x11 */
#define KP_BOOM_CW   26
#define KP_BOOM_CH   28
#define KP_BOOM_AX   13
#define KP_BOOM_AY   15
#define KP_BOOM_BW   11
#define KP_BOOM_BH   11
/* cannon: cell 28x15, anchor=(14,13), ref body 12x9 */
#define KP_CANNON_CW   28
#define KP_CANNON_CH   15
#define KP_CANNON_AX   14
#define KP_CANNON_AY   13
#define KP_CANNON_BW   12
#define KP_CANNON_BH   9
/* door: cell 24x29, anchor=(12,28), ref body 23x28 */
#define KP_DOOR_CW   24
#define KP_DOOR_CH   29
#define KP_DOOR_AX   12
#define KP_DOOR_AY   28
#define KP_DOOR_BW   23
#define KP_DOOR_BH   28
/* pickups: cell 24x14, anchor=(12,6), ref body 12x10 */
#define KP_PICKUPS_CW   24
#define KP_PICKUPS_CH   14
#define KP_PICKUPS_AX   12
#define KP_PICKUPS_AY   6
#define KP_PICKUPS_BW   12
#define KP_PICKUPS_BH   10
/* dialogue.png: rows = HELLO,HI,EXCLAIM,QUESTION,ATTACK,BOOM,DEAD,NO,WTF,LOSER;
 * cols = in0,in1,in2,out0,out1 (34x16 native) */
#define KP_DLG_FW 34
#define KP_DLG_FH 16
/* livebars.png: half-size live bar; slots below are half-res too */
#define KP_LBS_HX0 11
#define KP_LBS_HY0 8
#define KP_LBS_HX1 16
#define KP_LBS_HY1 8
#define KP_LBS_HX2 22
#define KP_LBS_HY2 8
/* livebar heart slot centres (native px) */
#define KP_LB_HX0 22
#define KP_LB_HY0 17
#define KP_LB_HX1 33
#define KP_LB_HY1 17
#define KP_LB_HX2 44
#define KP_LB_HY2 17
/* numbers.png: 6x8 digits in order 1234567890 (digit d -> col d? d-1 : 9) */
#define KP_BALL_W 7
#define KP_BALL_H 7
/* wallfeat.png: 32x32 cells; row 0 = solid-wall features, row 1 = bg features */
#endif
