/* GENERATED by mote bake from over.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound over = mote_sfx_bake(mote, &over_sfx); */
#ifndef MOTE_SFX_over_H
#define MOTE_SFX_over_H
#include "mote_api.h"

static const MoteSfx over_sfx = {
    1,  /* wave */
    0.3,0.06,-0.16,-0.04, 0.5,0,
    0,0, 0,0.25,0.2,0.45,
    0.7,-0.05,0.1, 0,0, 0,0, 0,0,
};

#endif
