/* GENERATED by mote bake (img2tex) from pieces.png — do not edit. */
#ifndef MOTE_IMG_pieces_H
#define MOTE_IMG_pieces_H
#include "mote_2d.h"

static const uint16_t pieces_pal[7] = { 0x39ca,0xa26d,0xbb0d,0xd42f,0xdcf1,0xe5b3,0xf81f };
static const uint8_t pieces_idx[50] = {
  102,102,102,0,0,102,102,102,102,102,5,0,96,85,85,102,102,102,102,102,5,48,96,48,0,3,67,70,0,19,0,0,
  0,83,0,0,0,0,0,0,4,69,0,80,6,96,1,48,51,34,
};
static const MoteImage pieces_img = { 0, 20, 5, 0xF81F, 0, 1, pieces_idx, pieces_pal };  /* 4bpp indexed, 7 colours */
#define pieces_W 20
#define pieces_H 5

#endif