/* GENERATED by mote bake (img2tex) from piecesh.png — do not edit. */
#ifndef MOTE_IMG_piecesh_H
#define MOTE_IMG_piecesh_H
#include "mote_2d.h"

static const uint16_t piecesh_pal[5] = { 0x39ca,0xd42f,0xdcf1,0xe5b3,0xf81f };
static const uint8_t piecesh_idx[15] = {
  68,64,0,4,68,3,3,51,48,68,3,17,0,18,16,
};
static const MoteImage piecesh_img = { 0, 10, 3, 0xF81F, 0, 1, piecesh_idx, piecesh_pal };  /* 4bpp indexed, 5 colours */
#define piecesh_W 10
#define piecesh_H 3

#endif