/* GENERATED by mote bake from pigdie.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound pigdie = mote_sfx_bake(mote, &pigdie_sfx); */
#ifndef MOTE_SFX_pigdie_H
#define MOTE_SFX_pigdie_H
#include "mote_api.h"

static const MoteSfx pigdie_sfx = {
    1,  /* wave */
    0.52,0.12,-0.34,0, 0.5,0,
    0.3,0.6, 0,0.1,0.3,0.22,
    0.85,0,0, 0,0, 0,0, 0,0,
};

#endif
