/* GENERATED by mote bake (img2tex) from shelfa.png — do not edit. */
#ifndef MOTE_IMG_shelfa_H
#define MOTE_IMG_shelfa_H
#include "mote_2d.h"

static const uint16_t shelfa_pal[7] = { 0x39ca,0xa26d,0xbb0d,0xd490,0xe5b3,0xeef7,0xf81f };
static const uint8_t shelfa_idx[96] = {
  96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,69,69,85,84,84,68,68,
  68,69,85,69,68,68,68,68,68,69,85,84,84,68,68,85,1,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,
  34,34,34,34,34,34,34,34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};
static const MoteImage shelfa_img = { 0, 48, 4, 0xF81F, 0, 1, shelfa_idx, shelfa_pal };  /* 4bpp indexed, 7 colours */
#define shelfa_W 48
#define shelfa_H 4

#endif