/* GENERATED by mote bake (img2tex) from shelfa.png — do not edit. */
#ifndef MOTE_IMG_shelfa_H
#define MOTE_IMG_shelfa_H
#include "mote_2d.h"

static const uint16_t shelfa_pal[5] = { 0x39ca,0x6acc,0xa26d,0xbb0d,0xf81f };
static const uint8_t shelfa_idx[96] = {
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,51,51,51,51,51,51,51,
  51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,50,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,68,68,4,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,64,68,68,
};
static const MoteImage shelfa_img = { 0, 48, 4, 0xF81F, 0, 1, shelfa_idx, shelfa_pal };  /* 4bpp indexed, 5 colours */
#define shelfa_W 48
#define shelfa_H 4

#endif