/* GENERATED by mote bake from swing.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound swing = mote_sfx_bake(mote, &swing_sfx); */
#ifndef MOTE_SFX_swing_H
#define MOTE_SFX_swing_H
#include "mote_api.h"

static const MoteSfx swing_sfx = {
    3,  /* wave */
    0.42,0,-0.3,0, 0.5,0,
    0,0, 0,0.04,0,0.1,
    0.55,-0.1,0.1, 0.1,0, 0,0, 0,0,
};

#endif
