/* GENERATED by mote bake from buy.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound buy = mote_sfx_bake(mote, &buy_sfx); */
#ifndef MOTE_SFX_buy_H
#define MOTE_SFX_buy_H
#include "mote_api.h"

static const MoteSfx buy_sfx = {
    0,  /* wave */
    0.36,0,0.04,0, 0.4,0,
    0,0, 0,0.07,0.2,0.16,
    0.9,0,0, 0,0, 0,0, 0.5,0.26,
};

#endif
