/* GENERATED by mote bake from door.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound door = mote_sfx_bake(mote, &door_sfx); */
#ifndef MOTE_SFX_door_H
#define MOTE_SFX_door_H
#include "mote_api.h"

static const MoteSfx door_sfx = {
    3,  /* wave */
    0.13,0,-0.07,0, 0.5,0,
    0,0, 0,0.035,0.18,0.09,
    0.32,-0.06,0.12, 0,0, 0,0, 0,0,
};

#endif
