/* GENERATED by mote bake from key.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound key = mote_sfx_bake(mote, &key_sfx); */
#ifndef MOTE_SFX_key_H
#define MOTE_SFX_key_H
#include "mote_api.h"

static const MoteSfx key_sfx = {
    0,  /* wave */
    0.42,0,0.04,0, 0.28,0,
    0,0, 0,0.04,0.25,0.1,
    0.9,0,0, 0,0, 0,0, 0.3,0.4,
};

#endif
