/* GENERATED by mote bake from locked.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound locked = mote_sfx_bake(mote, &locked_sfx); */
#ifndef MOTE_SFX_locked_H
#define MOTE_SFX_locked_H
#include "mote_api.h"

static const MoteSfx locked_sfx = {
    0,  /* wave */
    0.14,0,-0.02,0, 0.5,0,
    0,0, 0,0.06,0.2,0.1,
    0.45,-0.05,0.15, 0,0, 0,0, 0.55,0.02,
};

#endif
