/* GENERATED by assets/make_props.py — prop sprite metadata for both
 * sheets (0 = props_sheet.png extracted, 1 = props_auth.png authored). */
#ifndef DRAFT_PROPS_META_H
#define DRAFT_PROPS_META_H
#include <stdint.h>

typedef struct { uint8_t sheet; uint16_t fx; uint8_t fy, fw, fh; } PropDef;

enum {
    P_BUSH, P_CHEST, P_CAMPFIRE, P_SHELF_BIG, P_SHELF_SMALL, P_BED_BLUE, P_BED_RED, P_TABLE, P_CHAIR, P_SOFA, P_COUNTER, P_STOVE, P_TUB, P_TOILET, P_DESK, P_MAP_TABLE, P_WASHER, P_BARREL, P_GOLD_PILE, P_WORKBENCH, P_CHEST_OPEN, P_TERMINAL, P_BREAKER, P_PLANT, P_COUNT
};

static const PropDef k_props[P_COUNT] = {
    { 0,   0,  8, 24, 24 },  /* bush */
    { 0,  24, 16, 20, 16 },  /* chest */
    { 0,  44, 12, 20, 20 },  /* campfire */
    { 0,  64,  6, 32, 26 },  /* shelf_big */
    { 0,  96,  6, 30, 26 },  /* shelf_small */
    { 1,   0,  2, 24, 30 },  /* bed_blue */
    { 1,  24,  2, 24, 30 },  /* bed_red */
    { 1,  48, 12, 28, 20 },  /* table */
    { 1,  76, 18, 12, 14 },  /* chair */
    { 1,  88, 12, 34, 20 },  /* sofa */
    { 1, 122, 18, 32, 14 },  /* counter */
    { 1, 154, 10, 20, 22 },  /* stove */
    { 1, 174, 10, 36, 22 },  /* tub */
    { 1, 210, 14, 14, 18 },  /* toilet */
    { 1, 224, 12, 30, 20 },  /* desk */
    { 1, 254, 14, 26, 18 },  /* map_table */
    { 1, 280, 10, 18, 22 },  /* washer */
    { 1, 298, 12, 16, 20 },  /* barrel */
    { 1, 314, 20, 20, 12 },  /* gold_pile */
    { 1, 334, 16, 30, 16 },  /* workbench */
    { 1, 364, 16, 20, 16 },  /* chest_open */
    { 1, 384, 14, 16, 18 },  /* terminal */
    { 1, 400, 14, 14, 18 },  /* breaker */
    { 1, 414, 16, 12, 16 },  /* plant */
};

#endif
