/* GENERATED by assets/make_props.py — prop sprite metadata for both
 * sheets (0 = props_sheet.png extracted, 1 = props_auth.png authored). */
#ifndef DRAFT_PROPS_META_H
#define DRAFT_PROPS_META_H
#include <stdint.h>

typedef struct { uint8_t sheet; uint16_t fx; uint8_t fy, fw, fh; } PropDef;

enum {
    P_BUSH, P_CHEST, P_CAMPFIRE, P_SHELF_BIG, P_SHELF_SMALL, P_BED_BLUE, P_BED_RED, P_TABLE, P_CHAIR, P_SOFA, P_COUNTER, P_STOVE, P_TUB, P_TOILET, P_DESK, P_MAP_TABLE, P_WASHER, P_BARREL, P_GOLD_PILE, P_WORKBENCH, P_CHEST_OPEN, P_TERMINAL, P_BREAKER, P_RUG, P_PAINTING, P_PAINTING_V, P_WINDOW, P_WINDOW_V, P_LAMP, P_CRATE, P_BENCH, P_CANDLE, P_PLANT, P_SAFE, P_KEYPAD, P_CLOCK, P_GLOBE, P_PIANO, P_LECTERN, P_WINERACK, P_CHESSBOARD, P_SLOTS, P_STATUE, P_PLATE, P_SCALES, P_LEVER, P_LEVER_ON, P_ARMCHAIR, P_FIREPLACE, P_ARMOUR, P_MIRROR, P_HARP, P_BANNER, P_BANNER_V, P_FERN, P_PEDESTAL, P_SNOOKER, P_RACK, P_RACK_V, P_BLACKBOARD, P_BLACKBOARD_V, P_HATCH_PIT, P_HATCH_LID, P_BOOKSTACK, P_COUNT
};

static const PropDef k_props[P_COUNT] = {
    { 0,   0,  8, 24, 24 },  /* bush */
    { 0,  24, 16, 20, 16 },  /* chest */
    { 0,  44, 12, 20, 20 },  /* campfire */
    { 0,  64,  6, 32, 26 },  /* shelf_big */
    { 0,  96,  6, 30, 26 },  /* shelf_small */
    { 1,   0,  2, 24, 30 },  /* bed_blue */
    { 1,  24,  2, 24, 30 },  /* bed_red */
    { 1,  48, 12, 28, 20 },  /* table */
    { 1,  76, 18, 12, 14 },  /* chair */
    { 1,  88, 12, 34, 20 },  /* sofa */
    { 1, 122, 18, 32, 14 },  /* counter */
    { 1, 154, 10, 20, 22 },  /* stove */
    { 1, 174, 12, 28, 20 },  /* tub */
    { 1, 202, 14, 14, 18 },  /* toilet */
    { 1, 216, 12, 30, 20 },  /* desk */
    { 1, 246, 14, 26, 18 },  /* map_table */
    { 1, 272, 10, 18, 22 },  /* washer */
    { 1, 290, 12, 16, 20 },  /* barrel */
    { 1, 306, 20, 20, 12 },  /* gold_pile */
    { 1, 326, 16, 30, 16 },  /* workbench */
    { 1, 356, 16, 20, 16 },  /* chest_open */
    { 1, 376, 14, 16, 18 },  /* terminal */
    { 1, 392, 14, 14, 18 },  /* breaker */
    { 1, 406, 12, 28, 20 },  /* rug */
    { 1, 434, 24, 16,  8 },  /* painting */
    { 1, 450, 16,  8, 16 },  /* painting_v */
    { 1, 458, 24, 16,  8 },  /* window */
    { 1, 474, 16,  8, 16 },  /* window_v */
    { 1, 482, 10, 10, 22 },  /* lamp */
    { 1, 492, 18, 14, 14 },  /* crate */
    { 1, 506, 20, 24, 12 },  /* bench */
    { 1, 530, 16,  8, 16 },  /* candle */
    { 1, 538, 16, 12, 16 },  /* plant */
    { 1, 550, 16, 16, 16 },  /* safe */
    { 1, 566, 16, 14, 16 },  /* keypad */
    { 1, 580,  4, 14, 28 },  /* clock */
    { 1, 594, 14, 14, 18 },  /* globe */
    { 1, 608, 12, 28, 20 },  /* piano */
    { 1, 636, 16, 14, 16 },  /* lectern */
    { 1, 650, 14, 20, 18 },  /* winerack */
    { 1, 670, 16, 18, 16 },  /* chessboard */
    { 1, 688,  8, 18, 24 },  /* slots */
    { 1, 706, 12, 12, 20 },  /* statue */
    { 1, 718, 22, 12, 10 },  /* plate */
    { 1, 730, 18, 16, 14 },  /* scales */
    { 1, 746, 16, 12, 16 },  /* lever */
    { 1, 758, 16, 12, 16 },  /* lever_on */
    { 1, 770, 16, 16, 16 },  /* armchair */
    { 1, 786, 16, 24, 16 },  /* fireplace */
    { 1, 810, 10, 14, 22 },  /* armour */
    { 1, 824, 12, 12, 20 },  /* mirror */
    { 1, 836, 12, 16, 20 },  /* harp */
    { 1, 852, 24, 16,  8 },  /* banner */
    { 1, 868, 16,  8, 16 },  /* banner_v */
    { 1, 876, 14, 12, 18 },  /* fern */
    { 1, 888, 14, 10, 18 },  /* pedestal */
    { 1, 898,  0, 56, 32 },  /* snooker */
    { 1, 954, 24, 16,  8 },  /* rack */
    { 1, 970, 16,  8, 16 },  /* rack_v */
    { 1, 978, 24, 16,  8 },  /* blackboard */
    { 1, 994, 16,  8, 16 },  /* blackboard_v */
    { 1, 1002, 18, 16, 14 },  /* hatch_pit */
    { 1, 1018, 18, 16, 14 },  /* hatch_lid */
    { 1, 1034, 22, 12, 10 },  /* bookstack */
};

#endif
