/* GENERATED by mote bake from row.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound row = mote_sfx_bake(mote, &row_sfx); */
#ifndef MOTE_SFX_row_H
#define MOTE_SFX_row_H
#include "mote_api.h"

static const MoteSfx row_sfx = {
    0,  /* wave */
    0.28,0,0.09,0, 0.42,0,
    0,0, 0.01,0.2,0.35,0.28,
    0.9,0,0, 0,0, 0,0, 0.26,0.3,
};

#endif
