/* GENERATED by mote bake from star.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound star = mote_sfx_bake(mote, &star_sfx); */
#ifndef MOTE_SFX_star_H
#define MOTE_SFX_star_H
#include "mote_api.h"

static const MoteSfx star_sfx = {
    2,  /* wave */
    0.38,0,0.1,0, 0.5,0,
    0,0, 0,0.1,0.3,0.2,
    1,0,0, 0,0, 0,0, 0.28,0.32,
};

#endif
