/* GENERATED by mote bake (img2tex) from walls_red.png — do not edit. */
#ifndef MOTE_IMG_walls_red_H
#define MOTE_IMG_walls_red_H
#include "mote_2d.h"

static const uint16_t walls_red_pal[5] = { 0x0000,0x4943,0x79c4,0x9245,0xb2e7 };
static const uint8_t walls_red_idx[192] = {
  20,68,68,68,20,68,68,68,68,68,68,68,19,51,50,51,19,51,51,51,51,51,50,51,19,51,51,51,19,35,51,51,
  51,51,51,51,17,17,17,17,17,17,17,17,17,17,17,17,68,68,20,68,68,68,20,68,68,68,68,68,51,50,19,51,
  51,51,19,35,51,50,51,51,51,51,19,51,35,51,19,51,51,51,51,51,17,17,17,17,17,17,17,17,17,17,17,17,
  0,0,0,0,0,0,0,0,68,68,68,68,0,0,0,0,0,0,0,0,50,51,51,51,0,0,0,0,0,0,0,0,
  51,51,51,35,0,0,0,0,0,0,0,0,17,17,17,17,0,0,0,0,0,0,0,0,68,68,68,68,0,0,0,0,
  0,0,0,0,51,51,51,51,0,0,0,0,0,0,0,0,51,51,35,51,0,0,0,0,0,0,0,0,17,17,17,17,
};
static const MoteImage walls_red_img = { 0, 24, 16, 0xF81F, 1, 1, walls_red_idx, walls_red_pal };  /* 4bpp indexed, 5 colours */
#define walls_red_W 24
#define walls_red_H 16

#endif