/* GENERATED by mote bake from win.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound win = mote_sfx_bake(mote, &win_sfx); */
#ifndef MOTE_SFX_win_H
#define MOTE_SFX_win_H
#include "mote_api.h"

static const MoteSfx win_sfx = {
    0,  /* wave */
    0.22,0,0.1,0.01, 0.46,0,
    0.18,0.22, 0.02,0.45,0.4,0.55,
    0.85,0,0, 0,0, 0,0, 0.3,0.26,
};

#endif
