/* GENERATED by mote bake from fire.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound fire = mote_sfx_bake(mote, &fire_sfx); */
#ifndef MOTE_SFX_fire_H
#define MOTE_SFX_fire_H
#include "mote_api.h"

static const MoteSfx fire_sfx = {
    0,  /* wave */
    0.22,0,-0.22,0, 0.5,0,
    0,0, 0,0.06,0.5,0.3,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
