/* GENERATED by mote bake from ping.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound ping = mote_sfx_bake(mote, &ping_sfx); */
#ifndef MOTE_SFX_ping_H
#define MOTE_SFX_ping_H
#include "mote_api.h"

static const MoteSfx ping_sfx = {
    0,  /* wave */
    0.72,0,-0.38,0, 0.4,0,
    0,0, 0,0.02,0.1,0.12,
    1,0,0, 0.12,0, 0,0, 0,0,
};

#endif
