/* GENERATED by mote bake from bust.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound bust = mote_sfx_bake(mote, &bust_sfx); */
#ifndef MOTE_SFX_bust_H
#define MOTE_SFX_bust_H
#include "mote_api.h"

static const MoteSfx bust_sfx = {
    1,  /* wave */
    0.3,0.05,-0.14,0, 0,0,
    0.12,0.14, 0,0.15,0.2,0.44,
    0.6,-0.05,0.2, 0,0, 0.1,0, 0.35,-0.35,
};

#endif
