/* GENERATED by mote bake from hurt.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound hurt = mote_sfx_bake(mote, &hurt_sfx); */
#ifndef MOTE_SFX_hurt_H
#define MOTE_SFX_hurt_H
#include "mote_api.h"

static const MoteSfx hurt_sfx = {
    0,  /* wave */
    0.31,0.1,-0.44,0, 0.35,0,
    0,0, 0,0.03,0.32,0.14,
    0.85,0,0.1, 0.05,0, 0,0, 0,0,
};

#endif
