/* GENERATED by mote bake from shoot.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shoot = mote_sfx_bake(mote, &shoot_sfx); */
#ifndef MOTE_SFX_shoot_H
#define MOTE_SFX_shoot_H
#include "mote_api.h"

static const MoteSfx shoot_sfx = {
    3,  /* wave */
    0.6,0,-0.42,0, 0,0,
    0,0, 0,0.04,0.55,0.17,
    0.92,-0.12,0.1, 0.22,0, 0,0, 0,0,
};

#endif
