/* GENERATED by mote bake from shotgun.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shotgun = mote_sfx_bake(mote, &shotgun_sfx); */
#ifndef MOTE_SFX_shotgun_H
#define MOTE_SFX_shotgun_H
#include "mote_api.h"

static const MoteSfx shotgun_sfx = {
    3,  /* wave */
    0.4,0,-0.26,0, 0,0,
    0,0, 0,0.09,0.6,0.32,
    0.68,-0.22,0.25, 0.06,0, 0.12,-0.02, 0,0,
};

#endif
