/* GENERATED by mote bake from smg.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound smg = mote_sfx_bake(mote, &smg_sfx); */
#ifndef MOTE_SFX_smg_H
#define MOTE_SFX_smg_H
#include "mote_api.h"

static const MoteSfx smg_sfx = {
    3,  /* wave */
    0.54,0,-0.5,0, 0,0,
    0,0, 0,0.02,0.42,0.11,
    0.9,-0.1,0.1, 0.26,0, 0,0, 0,0,
};

#endif
