/* GENERATED by mote bake from win.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound win = mote_sfx_bake(mote, &win_sfx); */
#ifndef MOTE_SFX_win_H
#define MOTE_SFX_win_H
#include "mote_api.h"

static const MoteSfx win_sfx = {
    0,  /* wave */
    0.42,0,0.05,0, 0.24,0,
    0,0, 0,0.16,0.4,0.4,
    0.95,0,0.1, 0.04,0, 0,0, 0.42,0.45,
};

#endif
