/* GENERATED by mote bake from boom.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boom = mote_sfx_bake(mote, &boom_sfx); */
#ifndef MOTE_SFX_boom_H
#define MOTE_SFX_boom_H
#include "mote_api.h"

static const MoteSfx boom_sfx = {
    3,  /* wave */
    0.15,0,-0.1,0, 0,0,
    0.18,0.2, 0,0.2,0.5,0.62,
    0.36,-0.08,0.4, 0,0, 0.24,-0.02, 0,0,
};

#endif
