/* GENERATED by assets/extract_cars.py — per-car opaque art size in the
 * cars2 sheet (cell 28x60, 8 cols). Drives draw + physics-box sizing. */
#ifndef CARS2_META_H
#define CARS2_META_H
#define CARS2_N 54
#define CARS2_COLS 8
static const unsigned char cars2_aw[CARS2_N] = {22,22,23,23,21,22,21,23,22,20,18,20,21,20,20,20,23,22,24,24,23,22,21,24,23,23,23,22,22,21,21,23,22,23,25,23,26,23,22,23,23,26,21,22,23,23,22,24,26,26,26,26,26,26};
static const unsigned char cars2_ah[CARS2_N] = {47,49,50,49,47,48,47,47,48,46,46,45,45,46,45,46,45,43,49,49,46,43,40,43,44,44,44,47,44,42,44,50,42,44,43,44,45,43,44,46,45,45,45,44,49,50,45,47,47,49,50,47,47,49};
#endif
