/* GENERATED by mote bake from cash.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound cash = mote_sfx_bake(mote, &cash_sfx); */
#ifndef MOTE_SFX_cash_H
#define MOTE_SFX_cash_H
#include "mote_api.h"

static const MoteSfx cash_sfx = {
    0,  /* wave */
    0.65,0,0,0, 0.2,0,
    0,0, 0,0.06,0.45,0.26,
    1,0,0.1, 0.08,0, 0,0, 0.56,0.38,
};

#endif
