/* GENERATED by mote bake from crash.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound crash = mote_sfx_bake(mote, &crash_sfx); */
#ifndef MOTE_SFX_crash_H
#define MOTE_SFX_crash_H
#include "mote_api.h"

static const MoteSfx crash_sfx = {
    3,  /* wave */
    0.33,0,-0.28,0, 0,0,
    0,0, 0,0.05,0.48,0.26,
    0.82,-0.2,0.3, 0.1,0, 0.3,-0.05, 0,0,
};

#endif
