/* GENERATED by mote bake from phone.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound phone = mote_sfx_bake(mote, &phone_sfx); */
#ifndef MOTE_SFX_phone_H
#define MOTE_SFX_phone_H
#include "mote_api.h"

static const MoteSfx phone_sfx = {
    0,  /* wave */
    0.58,0,0,0, 0.5,0,
    0.6,0.7, 0.02,0.42,0,0.12,
    0.85,0,0.1, 0,0, 0,0, 0,0,
};

#endif
