/* GENERATED by mote bake from punch.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound punch = mote_sfx_bake(mote, &punch_sfx); */
#ifndef MOTE_SFX_punch_H
#define MOTE_SFX_punch_H
#include "mote_api.h"

static const MoteSfx punch_sfx = {
    3,  /* wave */
    0.17,0,-0.34,0, 0,0,
    0,0, 0,0.02,0.5,0.11,
    0.4,-0.1,0.2, 0,0, 0,0, 0,0,
};

#endif
