/* GENERATED by mote bake from siren.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound siren = mote_sfx_bake(mote, &siren_sfx); */
#ifndef MOTE_SFX_siren_H
#define MOTE_SFX_siren_H
#include "mote_api.h"

static const MoteSfx siren_sfx = {
    0,  /* wave */
    0.29,0.15,0,0, 0.3,0,
    0.52,0.07, 0.05,0.75,0.1,0.24,
    0.7,0,0.15, 0.05,0, 0,0, 0,0,
};

#endif
