/* GENERATED by mote bake from siren_hi.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound siren_hi = mote_sfx_bake(mote, &siren_hi_sfx); */
#ifndef MOTE_SFX_siren_hi_H
#define MOTE_SFX_siren_hi_H
#include "mote_api.h"

static const MoteSfx siren_hi_sfx = {
    0,  /* wave */
    0.41,0,0,0, 0.35,0,
    0,0, 0.04,0.39,0,0.16,
    0.9,0,0.1, 0,0, 0,0, 0,0,
};

#endif
