/* GENERATED by mote bake from shot_plasma.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_plasma = mote_sfx_bake(mote, &shot_plasma_sfx); */
#ifndef MOTE_SFX_shot_plasma_H
#define MOTE_SFX_shot_plasma_H
#include "mote_api.h"

static const MoteSfx shot_plasma_sfx = {
    1,  /* wave */
    0.3,0,-0.08,0, 0.5,0,
    0.12,0.45, 0,0.07,0.2,0.15,
    0.45,-0.05,0.3, 0,0, 0.1,-0.01, 0,0,
};

#endif
