/* GENERATED by mote bake from shot_orb.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_orb = mote_sfx_bake(mote, &shot_orb_sfx); */
#ifndef MOTE_SFX_shot_orb_H
#define MOTE_SFX_shot_orb_H
#include "mote_api.h"

static const MoteSfx shot_orb_sfx = {
    2,  /* wave */
    0.15,0,-0.1,0, 0.5,0,
    0,0, 0,0.04,0.7,0.2,
    0.6,0,0, 0,0, 0,0, 0,0,
};

#endif
