/* GENERATED by mote bake from shot_rail.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_rail = mote_sfx_bake(mote, &shot_rail_sfx); */
#ifndef MOTE_SFX_shot_rail_H
#define MOTE_SFX_shot_rail_H
#include "mote_api.h"

static const MoteSfx shot_rail_sfx = {
    0,  /* wave */
    0.2,0,-0.24,0, 0.5,0,
    0,0, 0,0.05,0.5,0.18,
    0.45,0,0.3, 0.02,0, 0,0, 0,0,
};

#endif
