/* GENERATED by mote bake from shot_fire.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_fire = mote_sfx_bake(mote, &shot_fire_sfx); */
#ifndef MOTE_SFX_shot_fire_H
#define MOTE_SFX_shot_fire_H
#include "mote_api.h"

static const MoteSfx shot_fire_sfx = {
    2,  /* wave */
    0.14,0,0,0, 0.5,0,
    0.45,0.85, 0,0.05,0.5,0.2,
    0.6,0,0, 0,0, 0,0, 0,0,
};

#endif
