/* GENERATED by mote bake from splat.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound splat = mote_sfx_bake(mote, &splat_sfx); */
#ifndef MOTE_SFX_splat_H
#define MOTE_SFX_splat_H
#include "mote_api.h"

static const MoteSfx splat_sfx = {
    3,  /* wave */
    0.17,0,-0.34,0, 0.5,0,
    0,0, 0,0.02,0.55,0.13,
    0.32,-0.12,0.12, 0,0, 0,0, 0,0,
};

#endif
