/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound boom = mote_sfx_bake(mote, &boom_sfx); */
#ifndef MOTE_SFX_boom_H
#define MOTE_SFX_boom_H
#include "mote_api.h"

static const MoteSfx boom_sfx = {
    3,  /* wave */
    0.3,0,-0.07,0, 0,0,
    0,0, 0,0.26,0.4,0.5,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
