/* GENERATED by obj2rig from examples/tanks/assets/tank.obj — do not edit. */
#ifndef MOTE_RIG_tank_H
#define MOTE_RIG_tank_H
#include "mote_anim3d.h"

static const MeshVert tank_body_v[8] = {
    { -95,   6,-127},    {  95,  76,-127},    {  95,   6,-127},    { -95,  76,-127},
    {  95,  76, 127},    {  95,   6, 127},    { -95,  76, 127},    { -95,   6, 127},
};
static const MeshFace tank_body_f[12] = {
    {  0,  1,  2,    0,   0,-127},
    {  0,  3,  1,    0,   0,-127},
    {  2,  4,  5,  127,   0,   0},
    {  2,  1,  4,  127,   0,   0},
    {  5,  6,  7,    0,   0, 127},
    {  5,  4,  6,    0,   0, 127},
    {  7,  3,  0, -127,   0,   0},
    {  7,  6,  3, -127,   0,   0},
    {  3,  4,  1,    0, 127,   0},
    {  3,  6,  4,    0, 127,   0},
    {  7,  2,  5,    0,-127,   0},
    {  7,  0,  2,    0,-127,   0},
};
static const Mesh tank_body_m = { tank_body_v, tank_body_f, 0, 8, 12, 0xE71C, 0.400000f, 0.554617f, 0 };

static const MeshVert tank_turret_v[8] = {
    { -60,  64, -60},    {  60, 127, -60},    {  60,  64, -60},    { -60, 127, -60},
    {  60, 127,  73},    {  60,  64,  73},    { -60, 127,  73},    { -60,  64,  73},
};
static const MeshFace tank_turret_f[12] = {
    {  0,  1,  2,    0,   0,-127},
    {  0,  3,  1,    0,   0,-127},
    {  2,  4,  5,  127,   0,   0},
    {  2,  1,  4,  127,   0,   0},
    {  5,  6,  7,    0,   0, 127},
    {  5,  4,  6,    0,   0, 127},
    {  7,  3,  0, -127,   0,   0},
    {  7,  6,  3, -127,   0,   0},
    {  3,  4,  1,    0, 127,   0},
    {  3,  6,  4,    0, 127,   0},
    {  7,  2,  5,    0,-127,   0},
    {  7,  0,  2,    0,-127,   0},
};
static const Mesh tank_turret_m = { tank_turret_v, tank_turret_f, 0, 8, 12, 0xF7BE, 0.400000f, 0.498999f, 0 };

static const MeshVert tank_barrel_v[8] = {
    {  -9,  52,   4},    {   9,  71,   4},    {   9,  52,   4},    {  -9,  71,   4},
    {   9,  71, 127},    {   9,  52, 127},    {  -9,  71, 127},    {  -9,  52, 127},
};
static const MeshFace tank_barrel_f[12] = {
    {  0,  1,  2,    0,   0,-127},
    {  0,  3,  1,    0,   0,-127},
    {  2,  4,  5,  127,   0,   0},
    {  2,  1,  4,  127,   0,   0},
    {  5,  6,  7,    0,   0, 127},
    {  5,  4,  6,    0,   0, 127},
    {  7,  3,  0, -127,   0,   0},
    {  7,  6,  3, -127,   0,   0},
    {  3,  4,  1,    0, 127,   0},
    {  3,  6,  4,    0, 127,   0},
    {  7,  2,  5,    0,-127,   0},
    {  7,  0,  2,    0,-127,   0},
};
static const Mesh tank_barrel_m = { tank_barrel_v, tank_barrel_f, 0, 8, 12, 0x7BD0, 0.620000f, 0.710950f, 0 };

static const MoteRigPart tank_parts[3] = {
    { &tank_body_m, 1, -1, {0.0000f,0.0000f,0.0000f} },  /* body */
    { &tank_turret_m, 1, 0, {0.0000f,0.3000f,0.0200f} },  /* turret */
    { &tank_barrel_m, 1, 1, {0.0000f,0.3000f,0.1000f} },  /* barrel */
};
static const MoteRig tank_rig = { tank_parts, 3, 36 };

#endif
