/* GENERATED by mote bake from claimbig.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound claimbig = mote_sfx_bake(mote, &claimbig_sfx); */
#ifndef MOTE_SFX_claimbig_H
#define MOTE_SFX_claimbig_H
#include "mote_api.h"

static const MoteSfx claimbig_sfx = {
    2,  /* wave */
    0.36,0,0,0, 0.5,0,
    0,0, 0,0.1,0.18,0.34,
    1,0,0, 0,0, 0,0, 0.62,0.55,
};

#endif
