/* GENERATED by mote bake from claim.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound claim = mote_sfx_bake(mote, &claim_sfx); */
#ifndef MOTE_SFX_claim_H
#define MOTE_SFX_claim_H
#include "mote_api.h"

static const MoteSfx claim_sfx = {
    2,  /* wave */
    0.42,0,0,0, 0.5,0,
    0,0, 0,0.07,0.1,0.22,
    1,0,0, 0,0, 0,0, 0.55,0.5,
};

#endif
