/* GENERATED by mote bake from cut.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound cut = mote_sfx_bake(mote, &cut_sfx); */
#ifndef MOTE_SFX_cut_H
#define MOTE_SFX_cut_H
#include "mote_api.h"

static const MoteSfx cut_sfx = {
    3,  /* wave */
    0.5,0,-0.35,0, 0.5,0,
    0,0, 0,0.02,0.3,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
