/* GENERATED by mote bake from spawn.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound spawn = mote_sfx_bake(mote, &spawn_sfx); */
#ifndef MOTE_SFX_spawn_H
#define MOTE_SFX_spawn_H
#include "mote_api.h"

static const MoteSfx spawn_sfx = {
    0,  /* wave */
    0.3,0,0.12,0, 0.5,0,
    0,0, 0,0.05,0.2,0.14,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
