/* GENERATED by mote bake (img2tex) from anvil.png — do not edit. */
#ifndef MOTE_IMG_anvil_H
#define MOTE_IMG_anvil_H
#include "mote_2d.h"

static const uint16_t anvil_pal[7] = { 0x18c3,0x2124,0x39e7,0x5aeb,0x8430,0xb5b6,0xf81f };
static const uint8_t anvil_idx[64] = {
  102,0,17,17,17,17,0,6,97,52,69,85,85,85,84,49,19,68,68,67,51,51,48,22,97,0,50,34,33,16,6,102,
  102,102,4,67,51,6,102,102,102,102,21,68,67,22,102,102,102,97,51,34,34,33,102,102,102,20,68,67,51,51,6,102,
};
static const MoteImage anvil_img = { 0, 16, 8, 0xF81F, 0, 1, anvil_idx, anvil_pal };  /* 4bpp indexed, 7 colours */
#define anvil_W 16
#define anvil_H 8

#endif