/* GENERATED by mote bake (img2tex) from Chain.png — do not edit. */
#ifndef MOTE_IMG_Chain_H
#define MOTE_IMG_Chain_H
#include "mote_2d.h"

static const uint16_t Chain_pal[4] = { 0x2124,0x39e7,0x5aeb,0xf81f };
static const uint8_t Chain_idx[32] = {
  51,50,19,51,51,32,33,51,51,50,19,51,51,32,33,51,51,50,19,51,51,32,33,51,51,50,19,51,51,32,33,51,
};
static const MoteImage Chain_img = { 0, 8, 8, 0xF81F, 0, 1, Chain_idx, Chain_pal };  /* 4bpp indexed, 4 colours */
#define Chain_W 8
#define Chain_H 8

#endif