/* GENERATED by mote bake from chop.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound chop = mote_sfx_bake(mote, &chop_sfx); */
#ifndef MOTE_SFX_chop_H
#define MOTE_SFX_chop_H
#include "mote_api.h"

static const MoteSfx chop_sfx = {
    3,  /* wave */
    0.17,0,-0.22,0, 0.5,0,
    0,0, 0,0.04,0.3,0.18,
    0.5,0,0.1, 0,0, 0,0, 0,0,
};

#endif
