/* GENERATED by mote bake from craft.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound craft = mote_sfx_bake(mote, &craft_sfx); */
#ifndef MOTE_SFX_craft_H
#define MOTE_SFX_craft_H
#include "mote_api.h"

static const MoteSfx craft_sfx = {
    0,  /* wave */
    0.4,0,0.05,0, 0.45,0,
    0,0, 0,0.08,0.15,0.18,
    1,0,0, 0,0, 0,0, 0.5,0.26,
};

#endif
