/* GENERATED by mote bake from dig.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound dig = mote_sfx_bake(mote, &dig_sfx); */
#ifndef MOTE_SFX_dig_H
#define MOTE_SFX_dig_H
#include "mote_api.h"

static const MoteSfx dig_sfx = {
    3,  /* wave */
    0.24,0,-0.28,0, 0.5,0,
    0,0, 0,0.04,0.1,0.14,
    0.45,0,0.2, 0,0, 0,0, 0,0,
};

#endif
