/* GENERATED by mote bake from dig_stone.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound dig_stone = mote_sfx_bake(mote, &dig_stone_sfx); */
#ifndef MOTE_SFX_dig_stone_H
#define MOTE_SFX_dig_stone_H
#include "mote_api.h"

static const MoteSfx dig_stone_sfx = {
    3,  /* wave */
    0.4,0.1,-0.34,0, 0.5,0,
    0,0, 0,0.03,0.2,0.12,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
