/* GENERATED by mote bake from door.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound door = mote_sfx_bake(mote, &door_sfx); */
#ifndef MOTE_SFX_door_H
#define MOTE_SFX_door_H
#include "mote_api.h"

static const MoteSfx door_sfx = {
    0,  /* wave */
    0.2,0,0.04,0, 0.3,0,
    0,0, 0,0.03,0.1,0.07,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
