/* GENERATED by mote bake from jump.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound jump = mote_sfx_bake(mote, &jump_sfx); */
#ifndef MOTE_SFX_jump_H
#define MOTE_SFX_jump_H
#include "mote_api.h"

static const MoteSfx jump_sfx = {
    0,  /* wave */
    0.27,0,0.19,0, 0.35,0,
    0,0, 0,0.03,0,0.11,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
