/* GENERATED by mote bake from kill.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound kill = mote_sfx_bake(mote, &kill_sfx); */
#ifndef MOTE_SFX_kill_H
#define MOTE_SFX_kill_H
#include "mote_api.h"

static const MoteSfx kill_sfx = {
    3,  /* wave */
    0.3,0,-0.36,0, 0.5,0,
    0,0, 0,0.05,0.4,0.3,
    0.6,-0.1,0.2, 0,0, 0,0, 0,0,
};

#endif
