/* GENERATED by mote bake (img2tex) from Lantern.png — do not edit. */
#ifndef MOTE_IMG_Lantern_H
#define MOTE_IMG_Lantern_H
#include "mote_2d.h"

static const uint16_t Lantern_pal[10] = { 0x2124,0x38e4,0x39e7,0x5965,0x5aeb,0x8430,0xeba2,0xf81f,0xfd02,0xfe44 };
static const uint8_t Lantern_idx[64] = {
  119,116,39,119,119,64,66,119,119,116,39,119,119,64,66,119,119,116,39,119,119,34,32,119,114,32,0,7,85,84,68,84,
  112,17,49,7,112,19,97,7,112,54,131,39,114,104,150,39,114,105,134,39,112,24,99,7,84,69,85,68,114,34,34,39,
};
static const MoteImage Lantern_img = { 0, 8, 16, 0xF81F, 0, 1, Lantern_idx, Lantern_pal };  /* 4bpp indexed, 10 colours */
#define Lantern_W 8
#define Lantern_H 16

#endif