/* GENERATED by mote bake (img2tex) from Oak Wood Chest.png — do not edit. */
#ifndef MOTE_IMG_Oak Wood Chest_H
#define MOTE_IMG_Oak Wood Chest_H
#include "mote_2d.h"

static const uint16_t Oak Wood Chest_pal[10] = { 0x2124,0x38e4,0x39e7,0x5965,0x5aeb,0x8430,0x8a46,0xbb69,0xe4ed,0xf81f };
static const uint8_t Oak Wood Chest_idx[128] = {
  153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,153,147,51,51,51,51,57,153,
  145,55,120,136,136,135,115,57,56,55,119,119,119,119,115,131,56,22,119,102,102,119,99,131,23,22,102,102,102,102,97,113,
  51,51,49,34,34,19,51,19,55,136,135,37,66,120,136,113,17,17,17,4,66,17,17,17,23,22,102,0,0,102,97,113,
  56,23,118,102,102,103,113,131,56,54,119,119,119,119,99,131,55,19,49,51,51,17,51,129,23,22,103,119,119,118,97,113,
};
static const MoteImage Oak Wood Chest_img = { 0, 16, 16, 0xF81F, 0, 1, Oak Wood Chest_idx, Oak Wood Chest_pal };  /* 4bpp indexed, 10 colours */
#define Oak Wood Chest_W 16
#define Oak Wood Chest_H 16

#endif