/* GENERATED by mote bake (img2tex) from Oak Wood Chair.png — do not edit. */
#ifndef MOTE_IMG_Oak Wood Chair_H
#define MOTE_IMG_Oak Wood Chair_H
#include "mote_2d.h"

static const uint16_t Oak Wood Chair_pal[6] = { 0x38e4,0x5965,0x8a46,0xbb69,0xe4ed,0xf81f };
static const uint8_t Oak Wood Chair_idx[128] = {
  17,85,85,85,20,21,85,85,20,21,85,85,20,21,85,85,19,5,85,85,20,5,85,85,3,5,85,85,2,5,85,85,
  2,0,1,21,4,68,67,65,19,51,51,49,18,0,2,0,19,5,19,5,19,21,19,21,3,21,2,21,2,5,2,5,
  85,85,85,17,85,85,81,65,85,85,81,65,85,85,81,65,85,85,80,49,85,85,80,65,85,85,80,48,85,85,80,32,
  81,16,0,32,20,52,68,64,19,51,51,49,0,32,0,33,80,49,80,49,81,49,81,49,81,32,81,48,80,32,80,32,
};
static const MoteImage Oak Wood Chair_img = { 0, 8, 32, 0xF81F, 0, 1, Oak Wood Chair_idx, Oak Wood Chair_pal };  /* 4bpp indexed, 6 colours */
#define Oak Wood Chair_W 8
#define Oak Wood Chair_H 32

#endif