/* GENERATED by mote bake (img2tex) from Oak Wood Table.png — do not edit. */
#ifndef MOTE_IMG_Oak Wood Table_H
#define MOTE_IMG_Oak Wood Table_H
#include "mote_2d.h"

static const uint16_t Oak Wood Table_pal[6] = { 0x38e4,0x5965,0x8a46,0xbb69,0xe4ed,0xf81f };
static const uint8_t Oak Wood Table_idx[192] = {
  1,17,17,17,1,1,17,17,17,0,0,17,4,68,52,68,68,68,68,67,68,68,52,65,3,51,51,51,51,51,51,51,
  51,51,51,48,80,1,0,17,17,17,0,17,16,0,16,5,85,2,5,2,32,85,85,2,32,80,32,85,85,2,0,35,
  21,85,85,81,50,0,32,85,85,19,2,49,85,85,85,85,19,32,33,85,85,19,1,21,85,85,85,85,81,0,33,85,
  85,19,5,85,85,85,85,85,85,80,49,85,85,19,21,85,85,85,85,85,85,80,33,85,85,19,21,85,85,85,85,85,
  85,81,33,85,85,18,21,85,85,85,85,85,85,81,49,85,85,19,21,85,85,85,85,85,85,81,48,85,85,18,5,85,
  85,85,85,85,85,81,48,85,85,2,5,85,85,85,85,85,85,80,32,85,85,2,5,85,85,85,85,85,85,80,32,85,
};
static const MoteImage Oak Wood Table_img = { 0, 24, 16, 0xF81F, 0, 1, Oak Wood Table_idx, Oak Wood Table_pal };  /* 4bpp indexed, 6 colours */
#define Oak Wood Table_W 24
#define Oak Wood Table_H 16

#endif