/* GENERATED by mote bake from place.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound place = mote_sfx_bake(mote, &place_sfx); */
#ifndef MOTE_SFX_place_H
#define MOTE_SFX_place_H
#include "mote_api.h"

static const MoteSfx place_sfx = {
    0,  /* wave */
    0.34,0,-0.1,0, 0.4,0,
    0,0, 0,0.02,0.1,0.09,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
