/* GENERATED by extract_sheets.py — per-frame head offsets for the hair overlay. */
#ifndef PLAYER_META_H
#define PLAYER_META_H
#define PLAYER_FRAMES 9
static const int8_t player_head_dx[PLAYER_FRAMES] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static const int8_t player_head_dy[PLAYER_FRAMES] = { 0, 0, -1, 0, -1, 0, 0, 0, 0 };
#endif
