/* GENERATED by mote bake from roar.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound roar = mote_sfx_bake(mote, &roar_sfx); */
#ifndef MOTE_SFX_roar_H
#define MOTE_SFX_roar_H
#include "mote_api.h"

static const MoteSfx roar_sfx = {
    3,  /* wave */
    0.12,0.02,-0.04,0, 0.5,0,
    0.4,0.3, 0,0.25,0.5,0.5,
    0.4,0,0.3, 0,0, 0,0, 0,0,
};

#endif
