/* GENERATED by mote bake from splash.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound splash = mote_sfx_bake(mote, &splash_sfx); */
#ifndef MOTE_SFX_splash_H
#define MOTE_SFX_splash_H
#include "mote_api.h"

static const MoteSfx splash_sfx = {
    3,  /* wave */
    0.19,0,-0.1,0, 0.5,0,
    0,0, 0,0.1,0.1,0.26,
    0.32,-0.05,0.25, 0,0, 0,0, 0,0,
};

#endif
