/* GENERATED by mote bake (img2tex) from Torch.png — do not edit. */
#ifndef MOTE_IMG_Torch_H
#define MOTE_IMG_Torch_H
#include "mote_2d.h"

static const uint16_t Torch_pal[9] = { 0x38e4,0x5965,0x8a46,0xbb69,0xe4ed,0xeba2,0xf81f,0xfd02,0xfe44 };
static const uint8_t Torch_idx[128] = {
  102,101,102,102,102,101,102,102,102,101,102,102,102,102,86,102,102,87,86,102,102,87,86,102,102,87,86,102,102,101,117,102,
  101,120,117,102,101,120,117,102,102,88,117,102,102,87,133,102,87,136,135,86,87,136,135,86,101,120,133,102,102,88,135,86,
  87,117,135,86,87,117,135,86,102,87,135,86,101,120,117,102,101,36,85,102,101,36,85,102,17,53,117,102,102,87,83,17,
  102,19,22,102,102,19,22,102,51,18,102,102,102,102,33,51,102,3,22,102,102,96,102,102,0,102,102,102,102,102,102,0,
};
static const MoteImage Torch_img = { 0, 32, 8, 0xF81F, 0, 1, Torch_idx, Torch_pal };  /* 4bpp indexed, 9 colours */
#define Torch_W 32
#define Torch_H 8

#endif