/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound hit = mote_sfx_bake(mote, &hit_sfx); */
#ifndef MOTE_SFX_hit_H
#define MOTE_SFX_hit_H
#include "mote_api.h"

static const MoteSfx hit_sfx = {
    3,  /* wave */
    0.32,0,-0.1,0, 0.5,0,
    0,0, 0,0.01,0.3,0.12,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
