/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound levelup = mote_sfx_bake(mote, &levelup_sfx); */
#ifndef MOTE_SFX_levelup_H
#define MOTE_SFX_levelup_H
#include "mote_api.h"

static const MoteSfx levelup_sfx = {
    0,  /* wave */
    0.42,0,0,0, 0.5,0,
    0,0, 0,0.1,0.45,0.34,
    1,0,0, 0,0, 0,0, 0.55,0.5,
};

#endif
