/* GENERATED by mote bake from boom_big.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boom_big = mote_sfx_bake(mote, &boom_big_sfx); */
#ifndef MOTE_SFX_boom_big_H
#define MOTE_SFX_boom_big_H
#include "mote_api.h"

static const MoteSfx boom_big_sfx = {
    3,  /* wave */
    0.18,0,-0.12,0, 0.5,0,
    0,0, 0,0.15,0.6,0.55,
    0.6,-0.15,0.25, 0,0, 0.15,-0.02, 0,0,
};

#endif
