/* GENERATED by mote bake from death.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound death = mote_sfx_bake(mote, &death_sfx); */
#ifndef MOTE_SFX_death_H
#define MOTE_SFX_death_H
#include "mote_api.h"

static const MoteSfx death_sfx = {
    3,  /* wave */
    0.24,0,-0.1,-0.02, 0.5,0,
    0.3,0.4, 0,0.12,0.5,0.45,
    0.55,-0.12,0.3, 0,0, 0.2,-0.03, 0,0,
};

#endif
