/* GENERATED by mote bake from dirt.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound dirt = mote_sfx_bake(mote, &dirt_sfx); */
#ifndef MOTE_SFX_dirt_H
#define MOTE_SFX_dirt_H
#include "mote_api.h"

static const MoteSfx dirt_sfx = {
    3,  /* wave */
    0.16,0,-0.2,0, 0.5,0,
    0,0, 0,0.05,0.2,0.12,
    0.4,-0.1,0.1, 0,0, 0,0, 0,0,
};

#endif
