/* GENERATED by mote bake from laser.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound laser = mote_sfx_bake(mote, &laser_sfx); */
#ifndef MOTE_SFX_laser_H
#define MOTE_SFX_laser_H
#include "mote_api.h"

static const MoteSfx laser_sfx = {
    1,  /* wave */
    0.55,0.1,-0.3,0, 0.5,0,
    0.4,0.6, 0,0.08,0.2,0.14,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
