/* GENERATED by mote bake from reload.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound reload = mote_sfx_bake(mote, &reload_sfx); */
#ifndef MOTE_SFX_reload_H
#define MOTE_SFX_reload_H
#include "mote_api.h"

static const MoteSfx reload_sfx = {
    0,  /* wave */
    0.5,0,0,0, 0.15,0,
    0,0, 0,0.03,0.1,0.05,
    1,0,0, 0.2,0, 0,0, 0.6,0.05,
};

#endif
