/* GENERATED by mote bake from rope_hit.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound rope_hit = mote_sfx_bake(mote, &rope_hit_sfx); */
#ifndef MOTE_SFX_rope_hit_H
#define MOTE_SFX_rope_hit_H
#include "mote_api.h"

static const MoteSfx rope_hit_sfx = {
    0,  /* wave */
    0.62,0,-0.35,0, 0.2,0,
    0,0, 0,0.02,0.3,0.06,
    1,0,0, 0.15,0, 0,0, 0,0,
};

#endif
