/* GENERATED by mote bake from rope.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound rope = mote_sfx_bake(mote, &rope_sfx); */
#ifndef MOTE_SFX_rope_H
#define MOTE_SFX_rope_H
#include "mote_api.h"

static const MoteSfx rope_sfx = {
    0,  /* wave */
    0.22,0,0.35,0, 0.4,0,
    0,0, 0,0.05,0.15,0.1,
    0.9,0,0, 0.05,0, 0,0, 0,0,
};

#endif
