/* GENERATED by mote bake from shot_auto.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shot_auto = mote_sfx_bake(mote, &shot_auto_sfx); */
#ifndef MOTE_SFX_shot_auto_H
#define MOTE_SFX_shot_auto_H
#include "mote_api.h"

static const MoteSfx shot_auto_sfx = {
    0,  /* wave */
    0.36,0,-0.28,0, 0.3,0,
    0,0, 0,0.03,0.2,0.07,
    0.9,0,0, 0.06,0, 0,0, 0,0,
};

#endif
