/* GENERATED by mote bake from shotgun.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound shotgun = mote_sfx_bake(mote, &shotgun_sfx); */
#ifndef MOTE_SFX_shotgun_H
#define MOTE_SFX_shotgun_H
#include "mote_api.h"

static const MoteSfx shotgun_sfx = {
    3,  /* wave */
    0.32,0,-0.3,0, 0.5,0,
    0,0, 0,0.06,0.5,0.16,
    0.85,-0.1,0.15, 0,0, 0.08,-0.02, 0,0,
};

#endif
