/* GENERATED by mote bake from ack.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound ack = mote_sfx_bake(mote, &ack_sfx); */
#ifndef MOTE_SFX_ack_H
#define MOTE_SFX_ack_H
#include "mote_api.h"

static const MoteSfx ack_sfx = {
    0,  /* wave */
    0.26,0,0.04,0, 0.38,0,
    0,0, 0,0.03,0.1,0.06,
    0.55,0,0.35, 0.05,0, 0,0, 0.75,0.22,
};

#endif
