/* GENERATED by mote bake from boom_small.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boom_small = mote_sfx_bake(mote, &boom_small_sfx); */
#ifndef MOTE_SFX_boom_small_H
#define MOTE_SFX_boom_small_H
#include "mote_api.h"

static const MoteSfx boom_small_sfx = {
    3,  /* wave */
    0.3,0,-0.28,0, 0.5,0,
    0,0, 0,0.1,0.4,0.3,
    0.8,-0.15,0.2, 0,0, 0.1,-0.02, 0,0,
};

#endif
