/* GENERATED by assets/extract_buildings.py — per-building sprite slots
 * in buildings.png. Sprites anchor to the BOTTOM of the footprint;
 * BM_YOFF < 0 means the art stands taller than the footprint. */
#define BM_ROW_H 32
static const uint8_t BM_X[11] = { 0, 24, 40, 64, 80, 104, 120, 136, 152, 160, 168 };
static const uint8_t BM_W[11] = { 24, 16, 24, 16, 23, 16, 16, 16, 8, 8, 8 };
static const uint8_t BM_H[11] = { 23, 12, 15, 10, 22, 15, 13, 13, 7, 7, 11 };
static const int8_t BM_YOFF[11] = { 1, 4, 1, 6, -6, 1, 3, 3, 1, 1, -3 };
static const int8_t BM_XOFF[11] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
