/* GENERATED by mote bake from cannon.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound cannon = mote_sfx_bake(mote, &cannon_sfx); */
#ifndef MOTE_SFX_cannon_H
#define MOTE_SFX_cannon_H
#include "mote_api.h"

static const MoteSfx cannon_sfx = {
    1,  /* wave */
    0.25,0,-0.15,0, 0.5,0,
    0,0, 0,0.08,0.3,0.18,
    0.7,-0.1,0.2, 0,0, 0.1,-0.02, 0,0,
};

#endif
