/* GENERATED by mote bake from cash.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound cash = mote_sfx_bake(mote, &cash_sfx); */
#ifndef MOTE_SFX_cash_H
#define MOTE_SFX_cash_H
#include "mote_api.h"

static const MoteSfx cash_sfx = {
    2,  /* wave */
    0.45,0,0,0, 0.5,0,
    0,0, 0,0.06,0.1,0.2,
    1,0,0, 0,0, 0,0, 0.55,0.45,
};

#endif
