/* GENERATED by mote bake from cash.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound cash = mote_sfx_bake(mote, &cash_sfx); */
#ifndef MOTE_SFX_cash_H
#define MOTE_SFX_cash_H
#include "mote_api.h"

static const MoteSfx cash_sfx = {
    0,  /* wave */
    0.5,0,0,0, 0.42,0,
    0,0, 0,0.06,0.35,0.2,
    0.72,0,0.4, 0,0, 0,0, 0.6,0.32,
};

#endif
