/* GENERATED by mote bake from click.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound click = mote_sfx_bake(mote, &click_sfx); */
#ifndef MOTE_SFX_click_H
#define MOTE_SFX_click_H
#include "mote_api.h"

static const MoteSfx click_sfx = {
    0,  /* wave */
    0.3,0,0,0, 0.3,0,
    0,0, 0,0.012,0.05,0.035,
    0.55,0,0.3, 0.12,0, 0,0, 0,0,
};

#endif
