/* GENERATED by mote bake from denied.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound denied = mote_sfx_bake(mote, &denied_sfx); */
#ifndef MOTE_SFX_denied_H
#define MOTE_SFX_denied_H
#include "mote_api.h"

static const MoteSfx denied_sfx = {
    0,  /* wave */
    0.2,0.06,-0.1,0, 0.2,0,
    0,0, 0,0.1,0.05,0.15,
    0.44,0,0.5, 0,0, 0,0, 0.5,-0.3,
};

#endif
