/* GENERATED by mote bake from flame.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound flame = mote_sfx_bake(mote, &flame_sfx); */
#ifndef MOTE_SFX_flame_H
#define MOTE_SFX_flame_H
#include "mote_api.h"

static const MoteSfx flame_sfx = {
    3,  /* wave */
    0.1,0,0.03,0, 0,0,
    0,0, 0.06,0.2,0,0.22,
    0.27,0,0.4, 0,0, 0,0, 0,0,
};

#endif
