/* GENERATED by mote bake from flame.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound flame = mote_sfx_bake(mote, &flame_sfx); */
#ifndef MOTE_SFX_flame_H
#define MOTE_SFX_flame_H
#include "mote_api.h"

static const MoteSfx flame_sfx = {
    1,  /* wave */
    0.24,0.85,0.35,0, 0.5,0,
    0.2,0.6, 0.02,0.2,0.2,0.35,
    1,0,0, 0,0, 0.1,0.02, 0,0,
};

#endif
