/* GENERATED by mote bake (img2tex) from grass_at.png — do not edit. */
#ifndef MOTE_IMG_grass_at_H
#define MOTE_IMG_grass_at_H
#include "mote_2d.h"

static const uint16_t grass_at_pal[6] = { 0x2a24,0x3244,0x3aa5,0x42e6,0x4326,0x5a86 };
static const uint8_t grass_at_idx[128] = {
  34,34,34,34,34,82,34,2,34,18,34,34,50,34,34,34,34,33,34,34,34,34,36,34,34,52,82,34,35,66,34,34,
  34,34,34,34,34,37,34,34,34,34,34,34,18,34,18,34,34,34,34,37,34,36,34,34,34,36,34,34,35,35,16,34,
  34,34,34,18,34,2,34,33,34,34,34,34,34,34,34,34,34,34,34,34,36,18,34,34,34,53,34,82,34,66,34,18,
  18,34,34,34,34,34,36,34,35,34,34,34,34,32,81,32,34,34,34,37,34,34,34,34,36,66,34,34,34,34,34,34,
};
static const MoteImage grass_at_img = { 0, 8, 32, 0xF81F, 1, 1, grass_at_idx, grass_at_pal };  /* 4bpp indexed, 6 colours */
#define grass_at_W 8
#define grass_at_H 32

#endif