/* GENERATED by mote bake from mg.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound mg = mote_sfx_bake(mote, &mg_sfx); */
#ifndef MOTE_SFX_mg_H
#define MOTE_SFX_mg_H
#include "mote_api.h"

static const MoteSfx mg_sfx = {
    3,  /* wave */
    0.42,0.12,-0.34,0, 0,0,
    0,0, 0,0.045,0.18,0.11,
    0.58,0,0.4, 0.08,0, 0,0, 0,0,
};

#endif
