/* GENERATED by mote bake from mg.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound mg = mote_sfx_bake(mote, &mg_sfx); */
#ifndef MOTE_SFX_mg_H
#define MOTE_SFX_mg_H
#include "mote_api.h"

static const MoteSfx mg_sfx = {
    0,  /* wave */
    0.42,0,-0.24,0, 0.35,0,
    0,0, 0,0.05,0.25,0.12,
    1,0,0, 0.05,0, 0,0, 0,0,
};

#endif
