/* GENERATED by mote bake from place.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound place = mote_sfx_bake(mote, &place_sfx); */
#ifndef MOTE_SFX_place_H
#define MOTE_SFX_place_H
#include "mote_api.h"

static const MoteSfx place_sfx = {
    0,  /* wave */
    0.22,0.06,-0.3,0, 0.35,0,
    0,0, 0,0.07,0.32,0.14,
    0.5,0,0.5, 0,0, 0,0, 0,0,
};

#endif
