/* GENERATED by mote bake from ready.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound ready = mote_sfx_bake(mote, &ready_sfx); */
#ifndef MOTE_SFX_ready_H
#define MOTE_SFX_ready_H
#include "mote_api.h"

static const MoteSfx ready_sfx = {
    0,  /* wave */
    0.36,0,0,0, 0.4,0,
    0,0, 0,0.12,0.2,0.2,
    0.68,0,0.4, 0,0, 0,0, 0.55,0.3,
};

#endif
