/* GENERATED by mote bake from rocket.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound rocket = mote_sfx_bake(mote, &rocket_sfx); */
#ifndef MOTE_SFX_rocket_H
#define MOTE_SFX_rocket_H
#include "mote_api.h"

static const MoteSfx rocket_sfx = {
    0,  /* wave */
    0.4,0,-0.22,0, 0.4,0,
    0,0, 0,0.05,0.2,0.12,
    1,0,0, 0.05,0, 0,0, 0,0,
};

#endif
