/* GENERATED by mote bake from rocket.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound rocket = mote_sfx_bake(mote, &rocket_sfx); */
#ifndef MOTE_SFX_rocket_H
#define MOTE_SFX_rocket_H
#include "mote_api.h"

static const MoteSfx rocket_sfx = {
    3,  /* wave */
    0.19,0,0.1,0, 0,0,
    0,0, 0.03,0.15,0.05,0.2,
    0.36,0,0.45, 0.04,0, 0,0, 0,0,
};

#endif
