/* GENERATED by mote bake from tesla.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound tesla = mote_sfx_bake(mote, &tesla_sfx); */
#ifndef MOTE_SFX_tesla_H
#define MOTE_SFX_tesla_H
#include "mote_api.h"

static const MoteSfx tesla_sfx = {
    2,  /* wave */
    0.52,0,-0.1,0, 0.5,0,
    0.15,0.5, 0,0.06,0.15,0.14,
    1,0,0, 0,0, 0.08,-0.01, 0.3,0.35,
};

#endif
