/* GENERATED by mote bake from tesla.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound tesla = mote_sfx_bake(mote, &tesla_sfx); */
#ifndef MOTE_SFX_tesla_H
#define MOTE_SFX_tesla_H
#include "mote_api.h"

static const MoteSfx tesla_sfx = {
    1,  /* wave */
    0.56,0.14,-0.4,0, 0,0,
    0.16,0.6, 0,0.06,0.3,0.15,
    0.72,0,0.35, 0.1,0, 0.16,-0.04, 0,0,
};

#endif
