/*
 * Mote VR — where the console's parts are, in model space.
 *
 * GENERATED by vr/tools/gen_vr_chassis.py from studio/assets/thumby_color.png
 * and studio/assets/screen.cfg. Do not edit; re-run the tool.
 *
 * Metres, life size, origin at the centre of the slab, +X right, +Y up, +Z out
 * of the screen towards the player. The button positions are the same
 * normalised photo coordinates the phone shell hit-tests against
 * (platform/android/mote_shell.c), converted to model space, so a press lands
 * on the button you can see in both.
 */
#ifndef MOTE_VR_CHASSIS_LAYOUT_H
#define MOTE_VR_CHASSIS_LAYOUT_H

#define MOTE_VR_CHASSIS_W    0.051600f    /* 51.6 mm */
#define MOTE_VR_CHASSIS_H    0.029968f    /* 30.0 mm */
#define MOTE_VR_CHASSIS_T    0.011600f    /* 11.6 mm */
#define MOTE_VR_CHASSIS_HALF 0.005800f    /* front face z */

/* The LCD's 128x128 active square. */
#define MOTE_VR_SCREEN_L  -0.007623f
#define MOTE_VR_SCREEN_R  0.008345f
#define MOTE_VR_SCREEN_B  -0.006736f
#define MOTE_VR_SCREEN_T  0.009233f

/* Button discs, for the press-feedback glow. x, y, radius. Order matches
 * MoteBtnId's UP..MENU only loosely — see mote_vr_render.c. */
#define MOTE_VR_BTN_A_X +0.020701f
#define MOTE_VR_BTN_A_Y +0.001729f
#define MOTE_VR_BTN_A_R 0.003199f
#define MOTE_VR_BTN_B_X +0.015128f
#define MOTE_VR_BTN_B_Y -0.000309f
#define MOTE_VR_BTN_B_R 0.003199f
#define MOTE_VR_BTN_MENU_X -0.015677f
#define MOTE_VR_BTN_MENU_Y -0.008700f
#define MOTE_VR_BTN_MENU_R 0.002580f
#define MOTE_VR_BTN_DPAD_X -0.017896f
#define MOTE_VR_BTN_DPAD_Y +0.000860f
#define MOTE_VR_BTN_DPAD_R 0.005934f

#endif /* MOTE_VR_CHASSIS_LAYOUT_H */
