#!/usr/bin/env python3
"""Extract the alternate car art (3 source images) into the game spritesheet.

Cars are auto-segmented from the light background, kept at their RELATIVE sizes
(one global scale), centred in a fixed grid, and measured — per-car art sizes go
to src/cars2_meta.h so the game can size each car's draw + PHYSICS BOX exactly.

Outputs: assets/cars2.png (grid sheet, transparent bg) + src/cars2_meta.h
"""
import numpy as np
from PIL import Image
from scipy import ndimage

SRC = ["/tmp/5bd02cd1-41b6-4fc2-b39c-0c7d66662c38.png",
       "/tmp/ChatGPT Image Jul 1, 2026, 10_39_55 PM.png",
       "/tmp/10a1e8a0-ccd0-4da4-8e12-07b0a35deaa0.png",
       "/tmp/2d8fea45-54bf-47c2-b514-8dcf20eae31b.png"]
CW, CH = 28, 60            # sheet cell size (width x height), cars face up
COLS   = 8
TARGET_MEDIAN_H = 46.0     # median car -> 46 px tall in the cell

cars = []                  # list of RGBA crops (source resolution)
for path in SRC:
    im = np.asarray(Image.open(path).convert("RGB")).astype(int)
    bg = np.median(im[2:20, 2:20].reshape(-1, 3), axis=0)
    dist = np.abs(im - bg).sum(axis=2)
    mask = dist > 60
    mask = ndimage.binary_closing(mask, structure=np.ones((5, 5)))
    # pure WHITE on the cars (roofs, POLICE text, ambulance body) is close to the light
    # background and gets keyed — refill anything ENCLOSED by car pixels
    mask = ndimage.binary_fill_holes(mask)
    lab, n = ndimage.label(mask)
    boxes = []
    for sl in ndimage.find_objects(lab):
        h, w = sl[0].stop - sl[0].start, sl[1].stop - sl[1].start
        if h < 60 or w < 30:  continue                    # specks
        boxes.append((sl[0].start, sl[1].start, sl[0].stop, sl[1].stop))
    # row-major order: cluster by y centre
    boxes.sort(key=lambda b: (b[0] + b[2]) // 2)
    rows, cur = [], [boxes[0]]
    for b in boxes[1:]:
        if abs(((b[0]+b[2])//2) - ((cur[0][0]+cur[0][2])//2)) < 120: cur.append(b)
        else: rows.append(cur); cur = [b]
    rows.append(cur)
    for row in rows:
        row.sort(key=lambda b: b[1])
        for (y0, x0, y1, x1) in row:
            crop = im[y0:y1, x0:x1]
            m    = mask[y0:y1, x0:x1]
            rgba = np.dstack([crop, np.where(m, 255, 0)]).astype(np.uint8)
            cars.append(Image.fromarray(rgba, "RGBA"))
    print(f"{path.split('/')[-1][:24]:24s} -> {sum(len(r) for r in rows)} cars")

# some source cars face DOWN — flip them so every car faces up (sheet index order)
ROT180 = {18, 19, 21}
for i in ROT180:
    cars[i] = cars[i].rotate(180)

hs = sorted(c.size[1] for c in cars)
scale = TARGET_MEDIAN_H / hs[len(hs)//2]
N = len(cars); ROWS = (N + COLS - 1) // COLS
sheet = Image.new("RGBA", (COLS*CW, ROWS*CH), (0, 0, 0, 0))
aw, ah = [], []
for i, c in enumerate(cars):
    w, h = max(1, round(c.size[0]*scale)), max(1, round(c.size[1]*scale))
    if h > CH-2: w = max(1, round(w*(CH-2)/h)); h = CH-2   # clamp the longest trucks
    if w > CW-2: h = max(1, round(h*(CW-2)/w)); w = CW-2
    r = c.resize((w, h), Image.LANCZOS)
    # harden alpha (LANCZOS softens edges; keep a crisp colour-key silhouette)
    a = np.asarray(r)[:, :, 3]
    rr = np.asarray(r).copy(); rr[:, :, 3] = np.where(a > 110, 255, 0)
    r = Image.fromarray(rr, "RGBA")
    x = (i % COLS)*CW + (CW - w)//2
    y = (i // COLS)*CH + (CH - h)//2
    sheet.paste(r, (x, y))
    aw.append(w); ah.append(h)
sheet.save("/home/maustin/thumby-color/mote/games/grandthumbauto/assets/cars2.png")

with open("/home/maustin/thumby-color/mote/games/grandthumbauto/src/cars2_meta.h", "w") as f:
    f.write("/* GENERATED by assets/extract_cars.py — per-car opaque art size in the\n"
            " * cars2 sheet (cell %dx%d, %d cols). Drives draw + physics-box sizing. */\n"
            "#ifndef CARS2_META_H\n#define CARS2_META_H\n" % (CW, CH, COLS))
    f.write("#define CARS2_N %d\n#define CARS2_COLS %d\n" % (N, COLS))
    f.write("static const unsigned char cars2_aw[CARS2_N] = {%s};\n" % ",".join(map(str, aw)))
    f.write("static const unsigned char cars2_ah[CARS2_N] = {%s};\n" % ",".join(map(str, ah)))
    f.write("#endif\n")
print(f"sheet: {N} cars, {COLS}x{ROWS} cells of {CW}x{CH} -> assets/cars2.png + src/cars2_meta.h")
