#!/usr/bin/env python3
"""
Bake one paint colour per car type from cars2.png into src/carcolors.h.

The 54 cars in this game are distinguished by their PAINT, not their shape:
seven mesh silhouettes cover all of them, so identity has to come from colour.
Rather than pick 54 colours by hand and have them drift from the sprite sheet,
take each cell's dominant body colour straight from the art.

"Dominant body colour" deliberately ignores two things: transparent padding,
and the dark pixels that are windows, tyres and shadow. What is left is the
paint. Greys survive because the darkness cut is on value, not saturation --
a silver car should stay silver.
"""
import os
from collections import Counter
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SHEET = os.path.join(HERE, "cars2.png")
OUT = os.path.join(HERE, "..", "src", "carcolors.h")

CW, CH = 28, 60          # cell size, matching CAR_CW/CAR_CH in game.c
COLS = 8                 # the sheet is 8 cells wide
N = 54                   # 54 car types

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def dominant(img, cx, cy, shift=4):
    """Most common body colour in a cell, after quantizing to 16-level buckets.

    Anti-aliasing spreads one paint colour across many adjacent-but-distinct
    RGB values (a navy body edge might sample as (35,74,118), (36,76,120),
    (34,73,117), ...), splitting its vote against flat single-colour details
    like a light bar or door decal that stay exactly one RGB value throughout.
    Without quantizing, a small flat highlight can outvote the actual paint.
    Bucketing by the top 4 bits per channel merges the paint's near-duplicates
    back into one bucket before counting; the reported colour is the average
    of the pixels in the winning bucket, not the bucket's quantized corner.
    """
    cell = img.crop((cx, cy, cx + CW, cy + CH)).convert("RGBA")
    counts = Counter()
    sums = {}
    for r, g, b, a in cell.getdata():
        if a < 128:
            continue                      # transparent padding
        if r + g + b < 150:
            continue                      # windows, tyres, shadow
        key = (r >> shift, g >> shift, b >> shift)
        counts[key] += 1
        s = sums.setdefault(key, [0, 0, 0, 0])
        s[0] += r; s[1] += g; s[2] += b; s[3] += 1
    if not counts:
        return (160, 160, 170)            # a car that is all glass: grey it
    best = counts.most_common(1)[0][0]
    s = sums[best]
    return (s[0] // s[3], s[1] // s[3], s[2] // s[3])

def main():
    img = Image.open(SHEET)
    cols = []
    for i in range(N):
        r, g, b = dominant(img, (i % COLS) * CW, (i // COLS) * CH)
        cols.append(rgb565(r, g, b))
    with open(OUT, "w") as f:
        f.write("/* Generated by assets/make_carcolors.py -- do not edit.\n"
                " * One RGB565 paint colour per car type, sampled from cars2.png.\n"
                " * All 54 cars share seven mesh silhouettes; this is what tells\n"
                " * them apart. Re-run the script if the sheet changes. */\n")
        f.write("#ifndef CARCOLORS_H\n#define CARCOLORS_H\n\n")
        f.write("static const uint16_t CAR_COL[%d] = {\n" % N)
        for i in range(0, N, 8):
            f.write("    " + ", ".join("0x%04X" % c for c in cols[i:i+8]) + ",\n")
        f.write("};\n\n#endif /* CARCOLORS_H */\n")
    print("wrote %s (%d colours)" % (os.path.normpath(OUT), N))

if __name__ == "__main__":
    main()
