#!/usr/bin/env python3
"""Author src/bld_night.h: a NIGHT PALETTE for each building atlas.

Lights a scattered share of the windows and drops the walls around them.

The facades go uniformly dark after sunset because mote_pipe shades a face as
0.25 + 0.75*max(0, n.sun) and a sun below the horizon parks everything on the
0.25 ambient floor. This lights a scattered share of the windows instead.

It costs almost nothing because the atlases are 8bpp PALETTE-INDEXED: the night
image reuses the same `*_idx` pixel data and only swaps `palette`. Per atlas
that is one small array plus one MoteImage -- about 70 bytes of flash, and no
GAME_RAM at all, since game.c re-points the existing g_bmesh textures rather
than keeping a second set.

WHICH index lights is chosen per atlas below, by eye from the art: it has to be
a window shade, not wall shading. HOW MUCH it lights is then derived, not
guessed -- the strength falls as the index's share of the facade rises, so a
shade covering one window in ten goes bright while one covering a third of the
wall only lifts. Lighting a large-area index hard turned bld_tower into yellow
stripes, which is what that rule exists to prevent.

The lit colour is near-white on purpose. Everything is multiplied by 0.25 after
dark, so (255,235,180) arrives as roughly (64,59,45) -- a warm glow against
walls that land near black. Anything dimmer reads as dirt.

ONE-SHOT-ish: safe to re-run, it regenerates the header from the art.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # the game dir
SRC, ASSETS = os.path.join(ROOT, "src"), os.path.join(ROOT, "assets")

# atlas -> the palette index that is window glass (read off the art)
WINDOW = {
    "bld_brick": 4, "bld_office": 3, "bld_tower": 2, "bld_concrete": 4,
    "bld_glass": 0, "bld_painted": 1, "bld_brownstone": 2, "bld_panel": 10,
}
LIT = (255, 235, 180)          # near-white warm; x0.25 after dark

def to888(v):
    return (((v >> 11) & 31) * 255 // 31, ((v >> 5) & 63) * 255 // 63, (v & 31) * 255 // 31)
def to565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def facade_share(name, pal, idx):
    """What fraction of the FACADE cell (the left 32x32) uses this entry."""
    from PIL import Image
    im = Image.open(os.path.join(ASSETS, name + ".png")).convert("RGB").crop((0, 0, 32, 32))
    rgb = [to888(p) for p in pal]
    px, hit = im.load(), 0
    for y in range(32):
        for x in range(32):
            c = px[x, y]
            if min(range(len(pal)), key=lambda i: sum((a-b)**2 for a, b in zip(c, rgb[i]))) == idx:
                hit += 1
    return hit / 1024.0

out = ["/* GENERATED by assets/make_bldnight.py — do not edit. */",
       "#ifndef MOTE_BLD_NIGHT_H", "#define MOTE_BLD_NIGHT_H", ""]
for name, widx in WINDOW.items():
    h = open(os.path.join(SRC, name + ".h")).read()
    m = re.search(rf"{name}_pal\[(\d+)\]\s*=\s*\{{(.*?)\}};", h, re.S)
    pal = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{4})", m.group(2))]
    share = facade_share(name, pal, widx)
    # a shade covering a tenth of the wall goes bright; a third of it only lifts.
    # The floor is high because everything is multiplied by 0.25 after dark --
    # a gentle lift simply disappears.
    k = max(0.35, min(0.95, 1.00 - share * 1.4))
    r, g, b = to888(pal[widx])
    lit = to565(int(r + (LIT[0]-r)*k), int(g + (LIT[1]-g)*k), int(b + (LIT[2]-b)*k))
    # And DARKEN everything that is not a window. The engine already multiplies
    # by 0.25 after dark, which caps how bright a lit window can get, so the only
    # way to make one read is to drop the wall around it. Walls at 0.68 against a
    # near-white window is the contrast that was missing when the first version
    # lit the glass and left the brickwork where it was.
    np_ = [to565(*(int(c*0.68) for c in to888(v))) for v in pal]
    np_[widx] = lit
    out.append(f"/* {name}: window idx {widx} covers {share*100:.0f}% of the facade -> lift {k:.2f} */")
    out.append(f"static const uint16_t {name}_npal[{len(np_)}] = {{ " +
               ",".join("0x%04x" % c for c in np_) + " };")
    mi = re.search(rf"static const MoteImage {name}_img = \{{(.*?)\}};", h).group(1)
    out.append(f"static const MoteImage {name}_night = {{{mi.rsplit(',', 1)[0]}, {name}_npal }};")
    out.append("")
out += ["#endif", ""]
open(os.path.join(SRC, "bld_night.h"), "w").write("\n".join(out))
print("wrote src/bld_night.h")
