/* GENERATED by mote bake from alert.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound alert = mote_sfx_bake(mote, &alert_sfx); */
#ifndef MOTE_SFX_alert_H
#define MOTE_SFX_alert_H
#include "mote_api.h"

static const MoteSfx alert_sfx = {
    1,  /* wave */
    0.26,0.08,-0.28,0, 0,0,
    0.2,0.3, 0,0.05,0.4,0.14,
    0.6,0,0.2, 0.04,0, 0,0, 0.3,-0.3,
};

#endif
