/* GENERATED by mote bake from autocannon.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound autocannon = mote_sfx_bake(mote, &autocannon_sfx); */
#ifndef MOTE_SFX_autocannon_H
#define MOTE_SFX_autocannon_H
#include "mote_api.h"

static const MoteSfx autocannon_sfx = {
    3,  /* wave */
    0.359265,0,-0.44707,0, 0.5,0,
    0,0, 0,0.059314,0,0.172693,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
