/* GENERATED by Mote Studio (img2tex) from games/wolfmote/assets/blood.png. */
#ifndef MOTE_IMG_blood_H
#define MOTE_IMG_blood_H
#include "mote_2d.h"

static const uint16_t blood_pal[15] = {0xf81f,0x6882,0x7082,0x6862,0x7882,0x90a3,0x90c3,0x98c3,0x88a3,0x6062,0x7062,0x5861,0x5041,0x5841,0x8082,};
static const uint8_t blood_idx[64] = {
0,0,0,0,0,0,0,0,0,0,18,34,49,34,0,0,0,36,86,117,132,36,66,0,2,69,118,102,118,41,146,32,
10,40,119,119,120,188,205,48,0,36,232,136,66,221,221,0,0,0,49,49,18,59,208,0,0,0,0,0,0,0,0,0,

};
static const MoteImage blood_img = { 0, 16, 8, 0xF81F, 0, 1, blood_idx, blood_pal };  /* 4bpp indexed, 15 colours */
#define blood_W 16
#define blood_H 8

#endif
