/* GENERATED by mote bake (img2tex) from blood.png — do not edit. */
#ifndef MOTE_IMG_blood_H
#define MOTE_IMG_blood_H
#include "mote_2d.h"

static const uint16_t blood_pal[15] = { 0x5041,0x5841,0x5861,0x6062,0x6862,0x6882,0x7062,0x7082,0x7882,0x8082,0x88a3,0x90a3,0x90c3,0x98c3,0xf81f };
static const uint8_t blood_idx[64] = {
  238,238,238,238,238,238,238,238,238,238,87,119,69,119,238,238,238,120,188,219,168,120,135,238,231,139,220,204,220,115,55,126,
  230,122,221,221,218,32,1,78,238,120,154,170,135,17,17,238,238,238,69,69,87,66,30,238,238,238,238,238,238,238,238,238,
};
static const MoteImage blood_img = { 0, 16, 8, 0xF81F, 0, 1, blood_idx, blood_pal };  /* 4bpp indexed, 15 colours */
#define blood_W 16
#define blood_H 8

#endif