/* GENERATED by mote bake from boom.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boom = mote_sfx_bake(mote, &boom_sfx); */
#ifndef MOTE_SFX_boom_H
#define MOTE_SFX_boom_H
#include "mote_api.h"

static const MoteSfx boom_sfx = {
    3,  /* wave */
    0.14,0,-0.09,0, 0,0,
    0.15,0.2, 0,0.15,0.55,0.5,
    0.34,-0.08,0.35, 0,0, 0.22,-0.02, 0,0,
};

#endif
