/* GENERATED by Mote Studio (img2tex) from games/wolfmote/assets/cannonb.png. */
#ifndef MOTE_IMG_cannonb_H
#define MOTE_IMG_cannonb_H
#include "mote_2d.h"

static const uint16_t cannonb_pal[30] = {0xf81f,0x4209,0x422a,0x4a6b,0x528b,0x39e9,0x4a4b,0x52ac,0x5aed,0x632e,0x4229,0x73b0,0x7bf1,0x8c52,0x9cd5,0x8c73,0x630d,0xb5b8,0xbdd9,0x9cf5,0x8412,0x6b4e,0xbdf9,0xa515,0x9493,0x7bd0,0x630e,0x5acc,0x4a4a,0x528c,};
static const uint8_t cannonb_idx[144] = {
0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,2,3,4,4,3,2,5,0,0,0,0,6,7,8,9,9,8,
7,3,5,0,0,10,7,9,11,12,12,11,9,7,2,0,0,3,8,11,13,14,14,15,11,16,4,1,1,4,9,12,
14,17,18,19,20,21,7,1,1,4,9,12,14,18,22,23,20,21,7,1,5,3,8,11,15,19,23,24,25,26,4,1,
0,2,7,9,11,20,20,25,21,27,28,0,0,5,3,7,16,21,21,26,27,4,5,0,0,0,1,2,4,29,7,4,
28,1,0,0,0,0,0,0,1,1,2,1,0,0,0,0,
};
static const MoteImage cannonb_img = { 0, 12, 12, 0xF81F, 0, 2, cannonb_idx, cannonb_pal };  /* 8bpp indexed, 30 colours */
#define cannonb_W 12
#define cannonb_H 12

#endif
