/* GENERATED by mote bake (img2tex) from cannonb.png — do not edit. */
#ifndef MOTE_IMG_cannonb_H
#define MOTE_IMG_cannonb_H
#include "mote_2d.h"

static const uint16_t cannonb_pal[26] = { 0x18e4,0x2104,0x2105,0x2125,0x2946,0x2966,0x3186,0x3187,0x31a7,0x39c7,0x39c8,0x39e8,0x4208,0x4209,0x4a4a,0x4a6a,0x528b,0x52ab,0x5acc,0x5aec,0x630d,0x6b4e,0x6b6e,0x8411,0x8431,0xf81f };
static const uint8_t cannonb_idx[144] = {
  25,25,25,25,25,0,0,0,25,25,25,25,25,25,25,2,4,5,5,4,2,0,25,25,25,25,3,5,8,11,11,9,
  6,4,0,25,25,1,5,11,14,16,16,14,11,6,3,25,25,4,8,14,18,21,21,19,15,10,4,0,0,5,11,16,
  21,23,23,22,17,12,5,1,1,5,11,16,21,23,24,22,17,13,5,1,0,4,9,14,19,22,22,20,15,10,5,0,
  25,2,6,11,15,17,17,15,13,7,3,25,25,0,4,7,10,12,13,10,7,4,0,25,25,25,0,3,4,5,5,5,
  3,0,25,25,25,25,25,25,1,1,2,1,25,25,25,25,
};
static const MoteImage cannonb_img = { 0, 12, 12, 0xF81F, 0, 2, cannonb_idx, cannonb_pal };  /* 8bpp indexed, 26 colours */
#define cannonb_W 12
#define cannonb_H 12

#endif