/* GENERATED by mote bake (img2tex) from cannonb.png — do not edit. */
#ifndef MOTE_IMG_cannonb_H
#define MOTE_IMG_cannonb_H
#include "mote_2d.h"

static const uint16_t cannonb_pal[30] = { 0x39e9,0x4209,0x4229,0x422a,0x4a4a,0x4a4b,0x4a6b,0x528b,0x528c,0x52ac,0x5acc,0x5aed,0x630d,0x630e,0x632e,0x6b4e,0x73b0,0x7bd0,0x7bf1,0x8412,0x8c52,0x8c73,0x9493,0x9cd5,0x9cf5,0xa515,0xb5b8,0xbdd9,0xbdf9,0xf81f };
static const uint8_t cannonb_idx[144] = {
  29,29,29,29,29,1,1,1,29,29,29,29,29,29,29,3,6,7,7,6,3,0,29,29,29,29,5,9,11,14,14,11,
  9,6,0,29,29,2,9,14,16,18,18,16,14,9,3,29,29,6,11,16,20,23,23,21,16,12,7,1,1,7,14,18,
  23,26,27,24,19,15,9,1,1,7,14,18,23,27,28,25,19,15,9,1,0,6,11,16,21,24,25,22,17,13,7,1,
  29,3,9,14,16,19,19,17,15,10,4,29,29,0,6,9,12,15,15,13,10,7,0,29,29,29,1,3,7,8,9,7,
  4,1,29,29,29,29,29,29,1,1,3,1,29,29,29,29,
};
static const MoteImage cannonb_img = { 0, 12, 12, 0xF81F, 0, 2, cannonb_idx, cannonb_pal };  /* 8bpp indexed, 30 colours */
#define cannonb_W 12
#define cannonb_H 12

#endif