/* GENERATED by mote bake from chain.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound chain = mote_sfx_bake(mote, &chain_sfx); */
#ifndef MOTE_SFX_chain_H
#define MOTE_SFX_chain_H
#include "mote_api.h"

static const MoteSfx chain_sfx = {
    3,  /* wave */
    0.34,0,-0.1,0, 0.5,0,
    0,0, 0,0.02,0.35,0.09,
    1,0,0, 0.05,0, 0,0, 0,0,
};

#endif
