/* GENERATED by mote bake from death.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound death = mote_sfx_bake(mote, &death_sfx); */
#ifndef MOTE_SFX_death_H
#define MOTE_SFX_death_H
#include "mote_api.h"

static const MoteSfx death_sfx = {
    1,  /* wave */
    0.34,0,-0.28,0, 0.5,0,
    0,0, 0.02,0.08,0.1,0.3,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
