/* GENERATED by mote bake from door.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound door = mote_sfx_bake(mote, &door_sfx); */
#ifndef MOTE_SFX_door_H
#define MOTE_SFX_door_H
#include "mote_api.h"

static const MoteSfx door_sfx = {
    1,  /* wave */
    0.16,0,0.07,0, 0.5,0,
    0,0, 0.03,0.26,0,0.26,
    0.62,0,0, 0,0, 0,0, 0,0,
};

#endif
