/* GENERATED by mote bake (img2tex) from fireball.png — do not edit. */
#ifndef MOTE_IMG_fireball_H
#define MOTE_IMG_fireball_H
#include "mote_2d.h"

static const uint16_t fireball_pal[41] = { 0xc1e1,0xc201,0xca01,0xca02,0xca21,0xca22,0xca42,0xd201,0xd222,0xd242,0xd2c3,0xd2c4,0xd2e4,0xd325,0xd345,0xd365,0xd366,0xd386,0xda62,0xda82,0xda83,0xdaa3,0xdb86,0xdbe7,0xdc08,0xdc28,0xe282,0xe2a3,0xe448,0xe469,0xe489,0xe4ca,0xe4ea,0xe50b,0xed6c,0xed8c,0xedad,0xf68f,0xf6b0,0xf6d0,0xf81f };
static const uint8_t fireball_idx[144] = {
  40,40,40,40,40,2,2,7,40,40,40,40,40,40,40,8,19,21,21,20,9,2,40,40,40,40,18,11,13,16,16,13,
  11,26,0,40,40,5,11,15,23,28,29,24,16,12,6,40,40,20,13,23,31,34,34,32,24,14,21,2,2,21,16,28,
  34,37,38,35,30,22,10,3,2,21,16,29,34,38,39,36,30,17,10,2,1,20,13,24,32,35,36,33,25,14,21,2,
  40,5,11,16,24,30,30,25,22,12,9,40,40,1,26,11,14,22,17,14,12,27,1,40,40,40,2,9,21,10,10,21,
  9,2,40,40,40,40,40,40,2,5,4,2,40,40,40,40,
};
static const MoteImage fireball_img = { 0, 12, 12, 0xF81F, 0, 2, fireball_idx, fireball_pal };  /* 8bpp indexed, 41 colours */
#define fireball_W 12
#define fireball_H 12

#endif