/* GENERATED by Mote Studio (img2tex) from games/wolfmote/assets/fireball.png. */
#ifndef MOTE_IMG_fireball_H
#define MOTE_IMG_fireball_H
#include "mote_2d.h"

static const uint16_t fireball_pal[41] = {0xf81f,0xca01,0xd201,0xd222,0xda82,0xdaa3,0xda83,0xd242,0xda62,0xd2c4,0xd325,0xd366,0xe282,0xc1e1,0xca22,0xd365,0xdbe7,0xe448,0xe469,0xdc08,0xd2e4,0xca42,0xe4ca,0xed6c,0xe4ea,0xd345,0xf68f,0xf6b0,0xed8c,0xe489,0xdb86,0xd2c3,0xca02,0xf6d0,0xedad,0xd386,0xc201,0xe50b,0xdc28,0xe2a3,0xca21,};
static const uint8_t fireball_idx[144] = {
0,0,0,0,0,1,1,2,0,0,0,0,0,0,0,3,4,5,5,6,7,1,0,0,0,0,8,9,10,11,11,10,
9,12,13,0,0,14,9,15,16,17,18,19,11,20,21,0,0,6,10,16,22,23,23,24,19,25,5,1,1,5,11,17,
23,26,27,28,29,30,31,32,1,5,11,18,23,27,33,34,29,35,31,1,36,6,10,19,24,28,34,37,38,25,5,1,
0,14,9,11,19,29,29,38,30,20,7,0,0,36,12,9,25,30,35,25,20,39,36,0,0,0,1,7,5,31,31,5,
7,1,0,0,0,0,0,0,1,14,40,1,0,0,0,0,
};
static const MoteImage fireball_img = { 0, 12, 12, 0xF81F, 0, 2, fireball_idx, fireball_pal };  /* 8bpp indexed, 41 colours */
#define fireball_W 12
#define fireball_H 12

#endif
