/* GENERATED by mote bake (img2tex) from key.png — do not edit. */
#ifndef MOTE_IMG_key_H
#define MOTE_IMG_key_H
#include "mote_2d.h"

static const uint16_t key_pal[14] = { 0x8b22,0xa3c3,0xb444,0xdda7,0xe5c7,0xe5e7,0xede7,0xee07,0xf627,0xf628,0xf647,0xf648,0xf81f,0xfe68 };
static const uint8_t key_idx[72] = {
  204,204,204,204,204,204,204,90,124,204,204,204,196,44,197,204,204,204,199,192,199,182,109,92,197,204,19,133,104,108,204,105,
  76,204,101,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,204,
  204,204,204,204,204,204,204,204,
};
static const MoteImage key_img = { 0, 12, 12, 0xF81F, 0, 1, key_idx, key_pal };  /* 4bpp indexed, 14 colours */
#define key_W 12
#define key_H 12

#endif