/* GENERATED by Mote Studio (img2tex) from games/wolfmote/assets/plasmab.png. */
#ifndef MOTE_IMG_plasmab_H
#define MOTE_IMG_plasmab_H
#include "mote_2d.h"

static const uint16_t plasmab_pal[38] = {0xf81f,0x22bc,0x2adc,0x331d,0x333d,0x335d,0x2afc,0x22bb,0x2b1d,0x3b5c,0x43bc,0x4bdc,0x4bfc,0x4bbc,0x333e,0x229b,0x645d,0x6cbd,0x647d,0x53fc,0x3b7c,0x7d1d,0x8dbe,0x95be,0x7d3d,0xb69f,0xb6bf,0x95de,0x74dd,0x541c,0xbedf,0x74fd,0x855d,0x6c9d,0x2adb,0x437c,0x335f,0x22dc,};
static const uint8_t plasmab_idx[144] = {
0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,2,3,4,5,4,6,7,0,0,0,0,8,9,10,11,12,13,
9,14,15,0,0,7,9,11,16,17,17,18,19,20,2,0,0,4,10,16,21,22,23,24,18,11,4,7,7,4,12,17,
22,25,26,27,28,29,9,7,7,5,12,17,23,26,30,27,31,29,9,7,7,4,13,18,24,27,27,32,33,11,4,7,
0,34,20,19,18,28,31,33,29,35,6,0,0,7,14,9,11,29,29,11,20,36,15,0,0,0,7,6,4,9,9,4,
6,1,0,0,0,0,0,0,1,7,1,37,0,0,0,0,
};
static const MoteImage plasmab_img = { 0, 12, 12, 0xF81F, 0, 2, plasmab_idx, plasmab_pal };  /* 8bpp indexed, 38 colours */
#define plasmab_W 12
#define plasmab_H 12

#endif
