/* GENERATED by mote bake (img2tex) from plasmab.png — do not edit. */
#ifndef MOTE_IMG_plasmab_H
#define MOTE_IMG_plasmab_H
#include "mote_2d.h"

static const uint16_t plasmab_pal[38] = { 0x229b,0x22bb,0x22bc,0x22dc,0x2adb,0x2adc,0x2afc,0x2b1d,0x331d,0x333d,0x333e,0x335d,0x335f,0x3b5c,0x3b7c,0x437c,0x43bc,0x4bbc,0x4bdc,0x4bfc,0x53fc,0x541c,0x645d,0x647d,0x6c9d,0x6cbd,0x74dd,0x74fd,0x7d1d,0x7d3d,0x855d,0x8dbe,0x95be,0x95de,0xb69f,0xb6bf,0xbedf,0xf81f };
static const uint8_t plasmab_idx[144] = {
  37,37,37,37,37,2,2,2,37,37,37,37,37,37,37,5,8,9,11,9,6,1,37,37,37,37,7,13,16,18,19,17,
  13,10,0,37,37,1,13,18,22,25,25,23,20,14,5,37,37,9,16,22,28,31,32,29,23,18,9,1,1,9,19,25,
  31,34,35,33,26,21,13,1,1,11,19,25,32,35,36,33,27,21,13,1,1,9,17,23,29,33,33,30,24,18,9,1,
  37,4,14,20,23,26,27,24,21,15,6,37,37,1,10,13,18,21,21,18,14,12,0,37,37,37,1,6,9,13,13,9,
  6,2,37,37,37,37,37,37,2,1,2,3,37,37,37,37,
};
static const MoteImage plasmab_img = { 0, 12, 12, 0xF81F, 0, 2, plasmab_idx, plasmab_pal };  /* 8bpp indexed, 38 colours */
#define plasmab_W 12
#define plasmab_H 12

#endif