/* GENERATED by mote bake from secret.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound secret = mote_sfx_bake(mote, &secret_sfx); */
#ifndef MOTE_SFX_secret_H
#define MOTE_SFX_secret_H
#include "mote_api.h"

static const MoteSfx secret_sfx = {
    3,  /* wave */
    0.08,0,0.02,0, 0,0,
    0.3,0.1, 0.05,0.5,0.2,0.4,
    0.22,0,0.3, 0,0, 0.2,-0.01, 0,0,
};

#endif
