/* GENERATED by mote bake from step.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound step = mote_sfx_bake(mote, &step_sfx); */
#ifndef MOTE_SFX_step_H
#define MOTE_SFX_step_H
#include "mote_api.h"

static const MoteSfx step_sfx = {
    3,  /* wave */
    0.12,0,-0.3,0, 0,0,
    0,0, 0,0.01,0.2,0.05,
    0.3,0,0.1, 0,0, 0,0, 0,0,
};

#endif
