/* GENERATED by Mote Studio — 20x8 level, 1 layers. The map is one byte
 * per cell, each bit a layer; it is const (lives in flash, zero SRAM). */
#ifndef MOTE_LEVEL_level1_H
#define MOTE_LEVEL_level1_H
#include "mote_api.h"
#include "ground.tiles.h"

#define level1_COLS 20
#define level1_ROWS 8
static const uint8_t level1_map[160] = {
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,
0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
};
static const MoteAutotile *level1_tiles[1] = { &ground_at };  /* layer order = bit order */
static inline void level1_draw(const MoteApi *m){ m->scene2d_set_autotile_layers(level1_map, level1_COLS, level1_ROWS, level1_tiles, 1); }

#endif
