/* GENERATED by Mote Studio — 20x8 level, 1 layers. The map is one byte
 * per cell, each bit a layer; it is const (lives in flash, zero SRAM). */
#ifndef MOTE_LEVEL_level3_H
#define MOTE_LEVEL_level3_H
#include "mote_api.h"
#include "ground.tiles.h"

#define level3_COLS 20
#define level3_ROWS 8
static const uint8_t level3_map[160] = {
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,
0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
};
static const MoteAutotile *level3_tiles[1] = { &ground_at };  /* layer order = bit order */
static inline void level3_draw(const MoteApi *m){ m->scene2d_set_autotile_layers(level3_map, level3_COLS, level3_ROWS, level3_tiles, 1); }

#endif
