/* GENERATED by Mote Studio — 20x8 level, 1 layers. The map is one byte
 * per cell, each bit a layer; it is const (lives in flash, zero SRAM). */
#ifndef MOTE_LEVEL_level2_H
#define MOTE_LEVEL_level2_H
#include "mote_api.h"
#include "ground.tiles.h"

#define level2_COLS 20
#define level2_ROWS 8
static const uint8_t level2_map[160] = {
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,
0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
};
static const MoteAutotile *level2_tiles[1] = { &ground_at };  /* layer order = bit order */
static inline void level2_draw(const MoteApi *m){ m->scene2d_set_autotile_layers(level2_map, level2_COLS, level2_ROWS, level2_tiles, 1); }

#endif
