/* GENERATED by obj2mesh — do not edit. */
#ifndef MESHES_GEN_H
#define MESHES_GEN_H
#include "r3d_mesh.h"

extern const Mesh mesh_fighter;
extern const Mesh mesh_viper;
extern const Mesh mesh_canister;
extern const Mesh mesh_station;
extern const Mesh mesh_beacon;

#endif
