/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_dock = mote_sfx_bake(mote, &sfx_dock_sfx); */
#ifndef MOTE_SFX_sfx_dock_H
#define MOTE_SFX_sfx_dock_H
#include "mote_api.h"

static const MoteSfx sfx_dock_sfx = {
    0,  /* wave */
    0.475024,0,0.329056,0, 0.5,0,
    0,0, 0,0.353415,0,0.320731,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
