/* GENERATED by Mote Studio — SFX recipe (assets/sfx_sc_engage.sfx). */
#ifndef MOTE_SFX_sfx_sc_engage_H
#define MOTE_SFX_sfx_sc_engage_H
#include "mote_api.h"

static const MoteSfx sfx_sc_engage_sfx = {
    2,
    0.25,0,0.2,0, 0.5,0,
    0,0, 0.03,0.08,0.3,0.24,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
