/* GENERATED by Mote Studio — SFX recipe (assets/sfx_ui_select.sfx). */
#ifndef MOTE_SFX_sfx_ui_select_H
#define MOTE_SFX_sfx_ui_select_H
#include "mote_api.h"

static const MoteSfx sfx_ui_select_sfx = {
    0,
    0.85,0,0,0, 0.5,0,
    0,0, 0,0.02,0.3,0.08,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
