/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_lock_warn = mote_sfx_bake(mote, &sfx_lock_warn_sfx); */
#ifndef MOTE_SFX_sfx_lock_warn_H
#define MOTE_SFX_sfx_lock_warn_H
#include "mote_api.h"

static const MoteSfx sfx_lock_warn_sfx = {
    0,  /* wave */
    0.347518,0,0,0, 0.479462,0,
    0,0, 0,0.0626678,0,0.144373,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
