/* GENERATED by Mote Studio — SFX recipe (assets/sfx_ui_move.sfx). */
#ifndef MOTE_SFX_sfx_ui_move_H
#define MOTE_SFX_sfx_ui_move_H
#include "mote_api.h"

static const MoteSfx sfx_ui_move_sfx = {
    0,
    0.6,0,0,0, 0.5,0,
    0,0, 0,0.01,0.2,0.05,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
