/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_enemy_shield_hit = mote_sfx_bake(mote, &sfx_enemy_shield_hit_sfx); */
#ifndef MOTE_SFX_sfx_enemy_shield_hit_H
#define MOTE_SFX_sfx_enemy_shield_hit_H
#include "mote_api.h"

static const MoteSfx sfx_enemy_shield_hit_sfx = {
    3,  /* wave */
    0.4151,0,0.000921629,0, 0.5,0,
    0,0, 0,0.223248,0.335205,0.556934,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
