/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_jump = mote_sfx_bake(mote, &sfx_jump_sfx); */
#ifndef MOTE_SFX_sfx_jump_H
#define MOTE_SFX_sfx_jump_H
#include "mote_api.h"

static const MoteSfx sfx_jump_sfx = {
    0,  /* wave */
    0.163121,0.0780142,0.286052,-0.205674, 0.183685,0.142993,
    0.529551,0.0661939, 0.371158,0.345154,0.378251,0.241135,
    0.747045,0.394799,0.687943, 0.477541,0.0354609, 0.664303,0.574468, 0.526495,0.326245,
};

#endif
