/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_flak = mote_sfx_bake(mote, &wpn_flak_sfx); */
#ifndef MOTE_SFX_wpn_flak_H
#define MOTE_SFX_wpn_flak_H
#include "mote_api.h"

static const MoteSfx wpn_flak_sfx = {
    3,  /* wave */
    0.371082,0,-0.0929504,0, 0.5,0,
    0.264752,0.0118286, 0,0.202771,0.426294,0.455969,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
