/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_pulse_l = mote_sfx_bake(mote, &wpn_pulse_l_sfx); */
#ifndef MOTE_SFX_wpn_pulse_l_H
#define MOTE_SFX_wpn_pulse_l_H
#include "mote_api.h"

static const MoteSfx wpn_pulse_l_sfx = {
    1,  /* wave */
    0.543735,0.263733,-0.200946,0, 0.248227,0.380615,
    0.349882,0.146572, 0,0.375887,0.0820038,0.153003,
    1,0,0, 0,0, 0.210402,0, 0.12766,0,
};

#endif
