/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_plasma = mote_sfx_bake(mote, &wpn_plasma_sfx); */
#ifndef MOTE_SFX_wpn_plasma_H
#define MOTE_SFX_wpn_plasma_H
#include "mote_api.h"

static const MoteSfx wpn_plasma_sfx = {
    1,  /* wave */
    0.515289,0,0.390845,0, 0.581543,0.13844,
    0.148819,0.38703, 0.00543823,0.243982,0.455093,0.306757,
    0.333789,0,0.0253601, 0,0, 0,0, 0.671695,-0.0755249,
};

#endif
