/* GENERATED by Mote Studio — SFX recipe (assets/wpn_homing.sfx). */
#ifndef MOTE_SFX_wpn_homing_H
#define MOTE_SFX_wpn_homing_H
#include "mote_api.h"

static const MoteSfx wpn_homing_sfx = {
    3,
    0.36,0,0.26,0, 0.5,0,
    0.08,0.3, 0.02,0.05,0.3,0.24,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
