/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_railgun = mote_sfx_bake(mote, &wpn_railgun_sfx); */
#ifndef MOTE_SFX_wpn_railgun_H
#define MOTE_SFX_wpn_railgun_H
#include "mote_api.h"

static const MoteSfx wpn_railgun_sfx = {
    3,  /* wave */
    0.852539,0,0.234912,0, 0.226685,0.00101319,
    0.306702,0.570026, 0.184491,0.417676,0.369583,0.37449,
    0.922192,0,0.214264, 0,0, 0,0, 0.547729,0.235864,
};

#endif
