/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_beam = mote_sfx_bake(mote, &wpn_beam_sfx); */
#ifndef MOTE_SFX_wpn_beam_H
#define MOTE_SFX_wpn_beam_H
#include "mote_api.h"

static const MoteSfx wpn_beam_sfx = {
    1,  /* wave */
    0.503601,0.199927,-0.189001,0, 0.283234,0.0374756,
    0,0, 0,0.621749,0.090445,0.217432,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
