/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_lance = mote_sfx_bake(mote, &wpn_lance_sfx); */
#ifndef MOTE_SFX_wpn_lance_H
#define MOTE_SFX_wpn_lance_H
#include "mote_api.h"

static const MoteSfx wpn_lance_sfx = {
    3,  /* wave */
    0.669342,0,-0.253711,0, 0.311584,0.0338745,
    0.34523,0.408215, 0.0473389,0.448645,0.162964,0.316904,
    0.675488,0,0.998383, 0,0, 0,0, 0.00196533,0.165955,
};

#endif
