/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_ion = mote_sfx_bake(mote, &wpn_ion_sfx); */
#ifndef MOTE_SFX_wpn_ion_H
#define MOTE_SFX_wpn_ion_H
#include "mote_api.h"

static const MoteSfx wpn_ion_sfx = {
    3,  /* wave */
    0.35813,0,-0.0405151,0, 0.5,0,
    0.588593,0.115704, 0,0.3995,0.470837,0.479965,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
