/* GENERATED by mote bake from age.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound age = mote_sfx_bake(mote, &age_sfx); */
#ifndef MOTE_SFX_age_H
#define MOTE_SFX_age_H
#include "mote_api.h"

static const MoteSfx age_sfx = {
    1,  /* wave */
    0.16,0.03,0,0.08, 0.5,0,
    0,0, 0.2,0.6,0.4,0.9,
    0.3,0.05,0, 0,0, 0,0, 0,0,
};

#endif
