/* GENERATED by mote bake from bless.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound bless = mote_sfx_bake(mote, &bless_sfx); */
#ifndef MOTE_SFX_bless_H
#define MOTE_SFX_bless_H
#include "mote_api.h"

static const MoteSfx bless_sfx = {
    1,  /* wave */
    0.55,0.08,0,0, 0.5,0,
    0,0, 0.01,0.18,0.16,0.3,
    1,0,0, 0,0, 0,0, 0.62,0.12,
};

#endif
