/* GENERATED by mote bake from boom.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound boom = mote_sfx_bake(mote, &boom_sfx); */
#ifndef MOTE_SFX_boom_H
#define MOTE_SFX_boom_H
#include "mote_api.h"

static const MoteSfx boom_sfx = {
    3,  /* wave */
    0.14,-0.05,-0.4,0, 0.5,0,
    0,0, 0,0.06,0.1,0.7,
    0.22,-0.05,0.3, 0,0, 0,0, 0,0,
};

#endif
