/* GENERATED by mote bake from build.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound build = mote_sfx_bake(mote, &build_sfx); */
#ifndef MOTE_SFX_build_H
#define MOTE_SFX_build_H
#include "mote_api.h"

static const MoteSfx build_sfx = {
    0,  /* wave */
    0.34,-0.08,0,0, 0.5,0,
    0,0, 0,0.05,0.03,0.1,
    1,0,0, 0,0, 0,0, 0.4,0.06,
};

#endif
