/* GENERATED by mote bake from curse.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound curse = mote_sfx_bake(mote, &curse_sfx); */
#ifndef MOTE_SFX_curse_H
#define MOTE_SFX_curse_H
#include "mote_api.h"

static const MoteSfx curse_sfx = {
    2,  /* wave */
    0.28,-0.1,0,0.22, 0.5,0,
    0,0, 0.02,0.22,0.14,0.4,
    0.4,-0.1,0, 0,0, 0,0, 0,0,
};

#endif
