/* GENERATED by mote bake from deny.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound deny = mote_sfx_bake(mote, &deny_sfx); */
#ifndef MOTE_SFX_deny_H
#define MOTE_SFX_deny_H
#include "mote_api.h"

static const MoteSfx deny_sfx = {
    2,  /* wave */
    0.18,0,0,0, 0.5,0,
    0,0, 0,0.05,0.04,0.08,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
