/* GENERATED by mote bake (img2tex) from dryflora.png — do not edit. */
#ifndef MOTE_IMG_dryflora_H
#define MOTE_IMG_dryflora_H
#include "mote_2d.h"

static const uint16_t dryflora_pal[4] = { 0x93a6,0xa408,0xb489,0xf81f };
static const uint8_t dryflora_idx[64] = {
  51,51,51,51,51,51,51,51,51,51,19,51,51,51,51,51,49,51,19,51,51,17,18,51,51,19,49,51,49,33,17,19,
  51,19,49,51,49,17,33,3,51,49,49,51,50,17,17,3,51,49,49,51,51,17,0,51,51,51,51,51,51,51,51,51,
};
static const MoteImage dryflora_img = { 0, 16, 8, 0xF81F, 0, 1, dryflora_idx, dryflora_pal };  /* 4bpp indexed, 4 colours */
#define dryflora_W 16
#define dryflora_H 8

#endif