/* GENERATED by mote bake from fall.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound fall = mote_sfx_bake(mote, &fall_sfx); */
#ifndef MOTE_SFX_fall_H
#define MOTE_SFX_fall_H
#include "mote_api.h"

static const MoteSfx fall_sfx = {
    1,  /* wave */
    0.3,-0.14,0,0, 0.5,0,
    0,0, 0.01,0.24,0.2,0.6,
    0.5,-0.1,0, 0,0, 0,0, 0,0,
};

#endif
