/* GENERATED by mote bake from fire.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound fire = mote_sfx_bake(mote, &fire_sfx); */
#ifndef MOTE_SFX_fire_H
#define MOTE_SFX_fire_H
#include "mote_api.h"

static const MoteSfx fire_sfx = {
    3,  /* wave */
    0.3,0.02,0,0, 0.5,0,
    0,0, 0.02,0.3,0.15,0.4,
    0.35,0.12,0.2, 0.06,0, 0,0, 0,0,
};

#endif
