/* GENERATED by mote bake from found.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound found = mote_sfx_bake(mote, &found_sfx); */
#ifndef MOTE_SFX_found_H
#define MOTE_SFX_found_H
#include "mote_api.h"

static const MoteSfx found_sfx = {
    1,  /* wave */
    0.36,0.1,0,0, 0.5,0,
    0,0, 0.01,0.14,0.14,0.22,
    1,0,0, 0,0, 0,0, 0.55,0.1,
};

#endif
