/* GENERATED by mote bake from freeze.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound freeze = mote_sfx_bake(mote, &freeze_sfx); */
#ifndef MOTE_SFX_freeze_H
#define MOTE_SFX_freeze_H
#include "mote_api.h"

static const MoteSfx freeze_sfx = {
    1,  /* wave */
    0.72,0.05,0,0.3, 0.5,0,
    0,0, 0.02,0.16,0.1,0.3,
    1,0,0, 0.3,0, 0,0, 0,0,
};

#endif
