/* GENERATED by mote bake (img2tex) from hot.png — do not edit. */
#ifndef MOTE_IMG_hot_H
#define MOTE_IMG_hot_H
#include "mote_2d.h"

static const uint16_t hot_pal[6] = { 0x18a3,0x2904,0x7164,0xf809,0xfd00,0xff64 };
static const uint8_t hot_idx[128] = {
  68,67,52,68,34,33,18,34,51,51,51,51,17,17,17,17,51,51,51,51,17,17,17,17,53,85,85,83,16,0,0,1,
  51,51,51,51,17,17,17,17,51,51,51,51,17,17,17,17,67,52,68,68,33,18,34,34,51,51,51,51,17,17,17,17,
  51,51,51,51,17,17,17,17,68,67,52,68,34,33,18,34,51,51,51,51,17,17,17,17,51,51,51,51,17,17,17,17,
  53,85,85,83,16,0,0,1,51,51,51,51,17,17,17,17,51,51,51,51,17,17,17,17,68,51,68,68,34,17,34,34,
};
static const MoteImage hot_img = { 0, 16, 16, 0xF81F, 1, 1, hot_idx, hot_pal };  /* 4bpp indexed, 6 colours */
#define hot_W 16
#define hot_H 16

#endif