/* GENERATED by mote bake (img2tex) from hot.png — do not edit. */
#ifndef MOTE_IMG_hot_H
#define MOTE_IMG_hot_H
#include "mote_2d.h"

static const uint16_t hot_pal[5] = { 0x5aa9,0x792a,0xf809,0xfd00,0xff64 };
static const uint8_t hot_idx[128] = {
  51,50,35,51,34,33,18,34,34,34,34,34,17,17,17,17,34,34,34,34,17,17,17,17,36,68,68,66,16,0,0,1,
  34,34,34,34,17,17,17,17,34,34,34,34,17,17,17,17,50,35,51,51,33,18,34,34,34,34,34,34,17,17,17,17,
  34,34,34,34,17,17,17,17,51,50,35,51,34,33,18,34,34,34,34,34,17,17,17,17,34,34,34,34,17,17,17,17,
  36,68,68,66,16,0,0,1,34,34,34,34,17,17,17,17,34,34,34,34,17,17,17,17,51,34,51,51,34,17,34,34,
};
static const MoteImage hot_img = { 0, 16, 16, 0xF81F, 1, 1, hot_idx, hot_pal };  /* 4bpp indexed, 5 colours */
#define hot_W 16
#define hot_H 16

#endif