/* GENERATED by mote bake (img2tex) from ore.png — do not edit. */
#ifndef MOTE_IMG_ore_H
#define MOTE_IMG_ore_H
#include "mote_2d.h"

static const uint16_t ore_pal[9] = { 0x194a,0x2d7f,0x5aa9,0xaa86,0xc618,0xf81f,0xfd00,0xff64,0xff9d };
static const uint8_t ore_idx[128] = {
  85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,
  85,51,51,85,85,34,34,85,85,51,51,85,85,34,34,85,83,67,99,5,82,66,130,5,83,67,115,5,82,66,18,5,
  83,51,51,5,82,34,34,5,83,51,51,5,82,34,34,5,83,99,48,5,82,130,32,5,83,115,48,5,82,18,32,5,
  85,0,0,85,85,0,0,85,85,0,0,85,85,0,0,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,
};
static const MoteImage ore_img = { 0, 32, 8, 0xF81F, 0, 1, ore_idx, ore_pal };  /* 4bpp indexed, 9 colours */
#define ore_W 32
#define ore_H 8

#endif