/* GENERATED by mote bake from quake.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound quake = mote_sfx_bake(mote, &quake_sfx); */
#ifndef MOTE_SFX_quake_H
#define MOTE_SFX_quake_H
#include "mote_api.h"

static const MoteSfx quake_sfx = {
    3,  /* wave */
    0.08,0,-0.05,0, 0.5,0,
    0,0, 0.05,0.5,0.3,0.8,
    0.12,0,0.1, 0,0, 0,0, 0,0,
};

#endif
