/* GENERATED by mote bake (img2tex) from rocks.png — do not edit. */
#ifndef MOTE_IMG_rocks_H
#define MOTE_IMG_rocks_H
#include "mote_2d.h"

static const uint16_t rocks_pal[5] = { 0x194a,0x5aa9,0xc618,0xf81f,0xff9d };
static const uint8_t rocks_idx[128] = {
  51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,35,51,
  51,51,51,51,51,51,51,51,51,51,51,51,51,51,17,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,49,51,
  51,34,34,51,51,51,33,3,51,52,67,51,50,19,51,3,50,17,17,3,51,33,17,3,51,33,16,51,49,19,50,51,
  50,17,17,3,50,17,16,51,50,17,17,3,51,48,49,19,51,0,0,3,48,0,3,51,0,0,0,3,51,51,51,48,
};
static const MoteImage rocks_img = { 0, 32, 8, 0xF81F, 0, 1, rocks_idx, rocks_pal };  /* 4bpp indexed, 5 colours */
#define rocks_W 32
#define rocks_H 8

#endif