/* GENERATED by mote bake from splash.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound splash = mote_sfx_bake(mote, &splash_sfx); */
#ifndef MOTE_SFX_splash_H
#define MOTE_SFX_splash_H
#include "mote_api.h"

static const MoteSfx splash_sfx = {
    3,  /* wave */
    0.45,-0.12,0,0, 0.5,0,
    0,0, 0.01,0.1,0.06,0.25,
    0.45,-0.15,0.15, 0,0, 0,0, 0,0,
};

#endif
