/* GENERATED by authoring/techtree.py — do not edit.
 *
 * WHERE EACH RUNG SITS when the tree is drawn by dependency depth rather than by era:
 * one row below its deepest prerequisite, so every link is a single step between
 * adjacent layers. The column order is the one that minimises crossings, found by
 * barycentre sweeps and then exhaustive swaps — 10 crossings over 11 layers.
 *
 * Indexed by TECH_*; entry 0 is TECH_NONE and unused. */
#ifndef MOTEBOX_TECH_LAYOUT_H
#define MOTEBOX_TECH_LAYOUT_H
#define TT_LAYERS 11
#define TT_WIDE   5
static const uint8_t TT_LAYER[] = { 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 2, 4, 4, 3, 4, 5, 5, 5, 5, 6, 7, 6, 7, 7, 8, 8, 7, 8, 9, 9, 10 };
static const uint8_t TT_COL[]   = { 0, 2, 0, 1, 2, 1, 3, 0, 2, 4, 3, 1, 3, 0, 2, 0, 1, 2, 1, 0, 0, 3, 2, 1, 0, 3, 1, 0, 1, 2, 0, 2, 1, 0, 1, 0 };
static const uint8_t TT_ROWN[TT_LAYERS] = { 3, 4, 5, 4, 3, 4, 2, 4, 3, 2, 1 };
#endif
