/* GENERATED by mote bake from thunder.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound thunder = mote_sfx_bake(mote, &thunder_sfx); */
#ifndef MOTE_SFX_thunder_H
#define MOTE_SFX_thunder_H
#include "mote_api.h"

static const MoteSfx thunder_sfx = {
    3,  /* wave */
    0.65,-0.35,0,0, 0.5,0,
    0,0, 0,0.03,0.05,0.45,
    1,0,0, 0.2,-0.05, 0,0, 0,0,
};

#endif
