/* GENERATED by mote bake from titan.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound titan = mote_sfx_bake(mote, &titan_sfx); */
#ifndef MOTE_SFX_titan_H
#define MOTE_SFX_titan_H
#include "mote_api.h"

static const MoteSfx titan_sfx = {
    2,  /* wave */
    0.1,0.01,-0.06,0.05, 0.5,0,
    0,0, 0.06,0.45,0.3,0.7,
    0.18,0,0.1, 0,0, 0,0, 0,0,
};

#endif
