/* GENERATED by mote bake (img2tex) from ui_symbols.png — do not edit. */
#ifndef MOTE_IMG_ui_symbols_H
#define MOTE_IMG_ui_symbols_H
#include "mote_2d.h"

static const uint16_t ui_symbols_pal[5] = { 0x2d7f,0x83b3,0xc618,0xf809,0xf81f };
static const uint8_t ui_symbols_idx[128] = {
  68,68,68,68,68,68,68,68,68,68,17,17,68,68,68,68,68,68,0,0,68,67,51,68,68,68,68,17,68,34,34,68,
  68,68,68,0,68,52,68,52,68,17,17,65,66,68,66,36,68,68,64,64,68,52,68,52,65,68,65,65,66,68,36,36,
  68,0,4,64,68,67,51,68,68,17,20,68,66,66,68,36,64,68,4,68,68,68,52,68,68,65,68,68,66,36,68,36,
  64,68,4,68,68,67,51,68,68,17,20,68,68,34,34,68,68,0,68,68,68,68,52,68,68,65,68,68,68,68,68,68,
};
static const MoteImage ui_symbols_img = { 0, 32, 8, 0xF81F, 0, 1, ui_symbols_idx, ui_symbols_pal };  /* 4bpp indexed, 5 colours */
#define ui_symbols_W 32
#define ui_symbols_H 8

#endif