/* GENERATED by mote bake from war.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound war = mote_sfx_bake(mote, &war_sfx); */
#ifndef MOTE_SFX_war_H
#define MOTE_SFX_war_H
#include "mote_api.h"

static const MoteSfx war_sfx = {
    2,  /* wave */
    0.22,0.02,0,0.12, 0.5,0,
    0,0, 0.03,0.3,0.22,0.35,
    0.6,0,0, 0,0, 0,0, 0,0,
};

#endif
