import wave, array, sys, os
src, out, name, macro = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
w = wave.open(src); sr = w.getframerate()
a = array.array('h'); a.frombytes(w.readframes(w.getnframes()))
if w.getnchannels() == 2: a = array.array('h', [(a[i]+a[i+1])//2 for i in range(0,len(a),2)])
assert sr == 22050 and w.getsampwidth() == 2, (sr, w.getsampwidth())
with open(out, 'w') as f:
    f.write("/* Cue-tip strike, %s: mono 22050 Hz s16.\n"
            " * The recording is the player's own, taken 1.14x deeper -- played slower, so\n"
            " * every partial moves down together and the ring-out lengthens with it -- with\n"
            " * the 9 kHz and up rolled off and the rumble below 50 Hz gone. Nothing is\n"
            " * truncated: the decay runs to silence, which is most of what makes it sound\n"
            " * like a table in a room. Only the half second of lead-in silence is dropped.\n"
            " * Auto-generated by tools/bake_pcm.py -- do not hand-edit. */\n" % os.path.basename(src))
    f.write("#ifndef %s_H\n#define %s_H\n#include <stdint.h>\n" % (macro, macro))
    f.write("#define %s_LEN %d\n" % (macro, len(a)))
    f.write("static const int16_t %s[%s_LEN] = {\n" % (name, macro))
    for i in range(0, len(a), 16):
        f.write("    " + ",".join(str(v) for v in a[i:i+16]) + ",\n")
    f.write("};\n#endif\n")
print("%s: %d samples, %.3f s, %d KB" % (out, len(a), len(a)/22050, len(a)*2//1024))
