#!/usr/bin/env python3
"""city2map — convert a top-down city map IMAGE into GrandThumbAuto's tile map.

Reads a source map picture (any size), block-averages it down to an N x N tile
grid, classifies each tile by colour into the game's tile alphabet, and writes a
const flash byte array (src/city_map.h). Also writes a derived preview PNG in the
GAME's own palette so you can eyeball the classification (this is DERIVED tile
data, not the source image).

Tiles: '.' road  ',' pavement  ' ' grass  '~' water  '#'/'O'/'H' building lo/mid/hi

    python3 tools/city2map.py <source.png> <out_dir> [N]
e.g. python3 tools/city2map.py /tmp/133261.png games/grandthumbauto 256
"""
import sys, os
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

def classify(r, g, b):
    bri = (r + g + b) / 3.0
    if b > 95 and r < 48 and b >= g - 12:                       # cyan water
        return '~'
    if g > r + 14 and g > b + 8 and g > 60:                     # green park/grass
        return ' '
    if (r > 52 and g > 52 and b < g - 16) or (bri > 112 and abs(r-g) < 22 and abs(g-b) < 22):
        return ','                                             # olive slab / light grey pavement
    if g >= r - 6 and b >= r - 6 and 55 < bri < 100 and (b - r) > -8:
        return '.'                                             # cool teal-grey road
    if r >= g - 4 and bri < 120:                               # dark / brown / red building
        return 'B0'                                            # placeholder: height chosen by hash below
    return ','                                                 # fallback: pavement

def bhash(x, z):
    h = (x * 73856093 ^ z * 19349663) & 0xffffffff
    return '#' if (h & 3) == 0 else ('O' if (h & 1) else 'H')

def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(2)
    src, outdir = sys.argv[1], sys.argv[2]
    N = int(sys.argv[3]) if len(sys.argv) > 3 else 256
    im = Image.open(src).convert("RGB")
    W = N
    H = int(round(N * im.size[1] / im.size[0]))
    tiles = im.resize((W, H), Image.BOX)
    px = tiles.load()
    grid = [['~'] * W for _ in range(H)]
    for z in range(H):
        for x in range(W):
            r, g, b = px[x, z]
            c = classify(r, g, b)
            if c == 'B0': c = bhash(x, z)
            grid[z][x] = c
    # island border = water
    for z in range(H):
        grid[z][0] = grid[z][W-1] = '~'
    for x in range(W):
        grid[0][x] = grid[H-1][x] = '~'

    # ---- derived preview in the game palette (safe to view) ----
    GAME = {'.':(70,70,78),',':(142,140,128),' ':(94,130,51),'~':(58,150,168),
            '#':(150,80,70),'O':(100,110,130),'H':(118,118,128),'B':(120,92,64)}
    prev = Image.new("RGB", (W, H))
    pp = prev.load()
    for z in range(H):
        for x in range(W): pp[x, z] = GAME[grid[z][x]]
    prev.save(os.path.join(outdir, "assets", "city.png"))

    # ---- baked flash map ----
    with open(os.path.join(outdir, "src", "city_map.h"), "w") as f:
        f.write(f"/* GENERATED by tools/city2map.py from {os.path.basename(src)} ({W}x{H}). */\n")
        f.write("#ifndef CITY_MAP_H\n#define CITY_MAP_H\n")
        f.write(f"#define CITY_W {W}\n#define CITY_H {H}\n")
        f.write("static const unsigned char city_map[CITY_W*CITY_H] = {\n")
        for z in range(H):
            f.write(" " + ",".join(str(ord(grid[z][x])) for x in range(W)) + ",\n")
        f.write("};\n#endif\n")

    # stats
    from collections import Counter
    cnt = Counter(c for row in grid for c in row)
    print(f"{W}x{H} tiles -> src/city_map.h + assets/city.png (preview)")
    for c, n in cnt.most_common():
        name = {'.':'road',',':'pavement',' ':'grass','~':'water','#':'bldg-lo','O':'bldg-mid','H':'bldg-hi'}.get(c, c)
        print(f"  {name:9s} {100*n/(W*H):5.1f}%")

if __name__ == "__main__":
    main()
