#!/usr/bin/env python3
"""citypng2map — bake an edited game-palette city PNG back into the flash tile map.

assets/city.png is 1 pixel = 1 tile in the GAME's own tile palette. Edit it in any
image editor (paint roads/water/parks/buildings with the palette colours), then run
this to regenerate src/city_map.h. Each pixel is matched to the NEAREST tile colour,
so slightly-off paint still snaps to a valid tile.

    python3 tools/citypng2map.py [assets/city.png] [game_dir]
"""
import sys, os
from PIL import Image

# game tile colour  ->  tile char   (must match the game's ground palette)
PAL = {
    (70,70,78):'.',   (142,140,128):',', (94,130,51):' ',  (58,150,168):'~',
    (150,80,70):'#',  (100,110,130):'O', (118,118,128):'H', (120,92,64):'B',
}
def nearest(r,g,b):
    best, bd = '~', 1<<60
    for (pr,pg,pb),ch in PAL.items():
        d=(r-pr)*(r-pr)+(g-pg)*(g-pg)+(b-pb)*(b-pb)
        if d<bd: bd=d; best=ch
    return best

def main():
    src    = sys.argv[1] if len(sys.argv)>1 else "games/grandthumbauto/assets/city.png"
    outdir = sys.argv[2] if len(sys.argv)>2 else "games/grandthumbauto"
    im=Image.open(src).convert("RGB"); W,H=im.size; px=im.load()
    from collections import Counter
    cnt=Counter()
    with open(os.path.join(outdir,"src","city_map.h"),"w") as f:
        f.write(f"/* GENERATED by tools/citypng2map.py from {os.path.basename(src)} ({W}x{H}). */\n")
        f.write("#ifndef CITY_MAP_H\n#define CITY_MAP_H\n")
        f.write(f"#define CITY_W {W}\n#define CITY_H {H}\n")
        f.write("static const unsigned char city_map[CITY_W*CITY_H] = {\n")
        for z in range(H):
            row=[nearest(*px[x,z]) for x in range(W)]
            for c in row: cnt[c]+=1
            f.write(" "+",".join(str(ord(c)) for c in row)+",\n")
        f.write("};\n#endif\n")
    names={'.':'road',',':'pavement',' ':'grass','~':'water','#':'bldg-lo','O':'bldg-mid','H':'bldg-hi','B':'bridge'}
    print(f"{W}x{H} tiles -> src/city_map.h")
    for c,n in cnt.most_common(): print(f"  {names.get(c,c):9s} {100*n/(W*H):5.1f}%")

if __name__=="__main__": main()
