/*
 * glyphs2font — a glyph-SHEET PNG -> MoteFont (hand-drawn / edited font).
 *
 * One PNG holds every glyph in a fixed grid: COLS columns, each cell CELLW x
 * CELLH; glyph i (codepoint FIRST+i) lives at cell (i%COLS, i/COLS). The sheet
 * is the editable source — the Studio shows the grid and edits ONE selected cell
 * in the Pixel-Art editor, then writes the single PNG back. Pixels: magenta /
 * transparent = no ink (coverage 0); else coverage = luminance * alpha/255
 * (a solid white pixel = 255, greys give AA).
 *
 * Each cell is the glyph's line-box: a glyph's ink position inside its cell sets
 * its placement (xoff/yoff). Advance is the ink's right edge + 1 px (proportional);
 * a blank cell (e.g. space) advances by a default fraction of the line height.
 *
 *   glyphs2font <name> <sheet.png> <out.h> <cols> <cellw> <cellh> <line_h> [first=32] [count=95]
 *
 * Depends on stb_image.h (-I studio/third_party); link -lm.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

int main(int argc, char **argv) {
    if (argc < 8) { fprintf(stderr, "usage: %s <name> <sheet.png> <out.h> <cols> <cellw> <cellh> <line_h> [first=32] [count=95] [meta.gsheet]\n", argv[0]); return 1; }
    const char *name = argv[1], *in = argv[2], *out = argv[3];
    int cols = atoi(argv[4]), cw = atoi(argv[5]), ch = atoi(argv[6]), line_h = atoi(argv[7]);
    int first = argc > 8 ? atoi(argv[8]) : 32;
    int count = argc > 9 ? atoi(argv[9]) : 95;
    const char *meta = argc > 10 ? argv[10] : NULL;
    if (cols < 1) cols = 16; if (cw < 1) cw = 8; if (ch < 1) ch = 8;
    if (line_h < 1) line_h = ch; if (line_h > 255) line_h = 255;
    if (first < 0) first = 0; if (count < 1) count = 1; if (first + count > 256) count = 256 - first;
    int blank_adv = line_h / 3; if (blank_adv < 2) blank_adv = 2;
    /* ttf2font parity: the sidecar's pen ORIGIN column lets xoff be negative (cursive
     * overhang) and its per-glyph ADVANCE list reproduces the real font spacing. */
    int origin = 0, has_adv = 0; static int adv[256];
    if (meta) { FILE *mf = fopen(meta, "r"); if (mf) {
        int a, b, c, d2, e2, as, ed, org;
        if (fscanf(mf, "%d %d %d %d %d %d %d %d", &a, &b, &c, &d2, &e2, &as, &ed, &org) == 8) {
            origin = org; int nn = count > 256 ? 256 : count, ok = 1;
            for (int i = 0; i < nn; i++) { int v; if (fscanf(mf, "%d", &v) != 1) { ok = 0; break; } adv[i] = v; }
            has_adv = ok;
        }
        fclose(mf); } }

    int W, H, n; unsigned char *d = stbi_load(in, &W, &H, &n, 4);
    if (!d) { fprintf(stderr, "glyphs2font: cannot load %s\n", in); return 1; }
    #define INK(px,py) ({ unsigned char *q=&d[((size_t)(py)*W+(px))*4]; \
        int mag=(q[0]>200&&q[1]<70&&q[2]>200); (q[3]>16 && !mag); })
    #define COV(px,py) ({ unsigned char *q=&d[((size_t)(py)*W+(px))*4]; \
        int mag=(q[0]>200&&q[1]<70&&q[2]>200); int c=(q[3]>16 && !mag)?((q[0]*30+q[1]*59+q[2]*11)/100)*q[3]/255:0; c>255?255:c; })

    typedef struct { int adv, w, h, xo, yo; long off; } G;
    G *gl = (G *)calloc((size_t)count, sizeof(G));

    FILE *h = fopen(out, "w"); if (!h) { perror(out); stbi_image_free(d); return 1; }
    fprintf(h, "/* GENERATED by glyphs2font from %s (%dx%d cells, line_h=%d) — edit the sheet PNG. */\n", in, cw, ch, line_h);
    fprintf(h, "#ifndef MOTE_FONT_%s_H\n#define MOTE_FONT_%s_H\n#include \"mote_2d.h\"\n\n", name, name);
    /* Pass 1: smallest LOSSLESS bit depth — 1-bit binary / 2-bit / else 4-bit. */
    int any_partial = 0, any_non2 = 0;
    for (int y = 0; y < H; y++) for (int x = 0; x < W; x++) { int n = (COV(x, y) * 15 + 127) / 255;
        if (n != 0 && n != 15) any_partial = 1;
        if (n != 0 && n != 5 && n != 10 && n != 15) any_non2 = 1; }
    int bpp = !any_partial ? 1 : (!any_non2 ? 2 : 4), maxv = (1 << bpp) - 1;

    fprintf(h, "static const uint8_t %s_cov[] = {\n", name);
    /* coverage packed MSB-first at `bpp` bits/pixel, byte-aligned per glyph. */
    long total = 0; int outcol = 0, drawn = 0;
    for (int i = 0; i < count; i++) {
        gl[i].adv = has_adv ? adv[i] : blank_adv; gl[i].off = total;
        int c0 = (i % cols) * cw, r0 = (i / cols) * ch;       /* cell origin in the sheet */
        if (c0 + cw > W || r0 + ch > H) continue;             /* cell off the sheet -> blank */
        int x0 = cw, y0 = ch, x1 = -1, y1 = -1;
        for (int y = 0; y < ch; y++) for (int x = 0; x < cw; x++)
            if (INK(c0 + x, r0 + y)) { if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; }
        if (x1 < 0) continue;                                 /* no ink -> blank glyph */
        int gw = x1 - x0 + 1, gh = y1 - y0 + 1;
        /* xoff relative to the pen origin (negative => overhangs left, connecting scripts);
         * advance from the font (sidecar) when available, else ink-derived. */
        gl[i].w = gw; gl[i].h = gh; gl[i].xo = x0 - origin; gl[i].yo = y0;
        if (!has_adv) gl[i].adv = x1 + 2;
        int acc = 0, nbits = 0, npix = 0;
        for (int y = y0; y <= y1; y++) for (int x = x0; x <= x1; x++) {
            int v = (COV(c0 + x, r0 + y) * maxv + 127) / 255; /* 8-bit -> bpp, rounded */
            acc = (acc << bpp) | v; nbits += bpp; npix++;
            while (nbits >= 8) { nbits -= 8; fprintf(h, "%d,", (acc >> nbits) & 0xFF); if ((++outcol & 31) == 0) fputc('\n', h); }
        }
        if (nbits) { fprintf(h, "%d,", (acc << (8 - nbits)) & 0xFF); if ((++outcol & 31) == 0) fputc('\n', h); }   /* flush, byte-align */
        total += (npix * bpp + 7) / 8; drawn++;               /* packed byte count */
    }
    if (total == 0) fprintf(h, "0");
    fprintf(h, "\n};\n");
    fprintf(h, "static const MoteGlyph %s_glyphs[%d] = {\n", name, count);
    for (int i = 0; i < count; i++)
        fprintf(h, "  {%d,%d,%d,%d,%d,%ld},\n", gl[i].adv, gl[i].w, gl[i].h, gl[i].xo, gl[i].yo, gl[i].off);
    fprintf(h, "};\n");
    fprintf(h, "static const MoteFont %s = { %s_cov, %s_glyphs, %d, %d, %d, %d };  /* mote->text_font(fb, &%s, ...) */\n\n#endif\n",
            name, name, name, count, first, line_h, bpp, name);
    fclose(h); stbi_image_free(d); free(gl);
    fprintf(stderr, "[glyphs2font] %s: %d/%d glyphs from %dx%d grid, line_h=%d, %d-bit, %ld cov bytes -> %s\n", name, drawn, count, cols, count / cols + 1, line_h, bpp, total, out);
    return 0;
}
