#!/usr/bin/env python3
"""ply2splat — convert a 3D Gaussian-Splatting .ply (INRIA/Postshot layout) into
a C header of `const MoteSplat[]` for the Mote splat renderer.

Each Gaussian -> position, 3x3 covariance (from log-scale + quaternion), RGB565
(from the DC spherical-harmonic term + sigmoid opacity). The scene is centred and
normalised to a friendly size, and importance-downsampled (opacity x volume) to a
target count so it fits the device's RAM/perf budget.

Usage: ply2splat.py <in.ply> <out.h> <symbol> [target_count] [scene_scale]
"""
import sys, struct, math

SH_C0 = 0.28209479177387814

def parse_header(f):
    assert f.readline().strip() == b'ply'
    fmt = f.readline().strip()
    assert b'binary_little_endian' in fmt, "only binary_little_endian supported"
    props, count = [], 0
    while True:
        line = f.readline().strip()
        if line.startswith(b'element vertex'):
            count = int(line.split()[-1])
        elif line.startswith(b'property'):
            props.append(line.split()[-1].decode())
        elif line == b'end_header':
            break
    return props, count

def main():
    inp, out, sym = sys.argv[1], sys.argv[2], sys.argv[3]
    target = int(sys.argv[4]) if len(sys.argv) > 4 else 6000
    user_scale = float(sys.argv[5]) if len(sys.argv) > 5 else 0.0

    with open(inp, 'rb') as f:
        props, n = parse_header(f)
        idx = {p: i for i, p in enumerate(props)}
        rec = struct.Struct('<%df' % len(props))
        data = f.read(rec.size * n)

    need = ['x','y','z','f_dc_0','f_dc_1','f_dc_2','opacity',
            'scale_0','scale_1','scale_2','rot_0','rot_1','rot_2','rot_3']
    for k in need:
        if k not in idx: sys.exit("missing property %s" % k)

    splats = []  # (importance, pos, scale, quat, rgb, opacity)
    for v in rec.iter_unpack(data):
        op = 1.0/(1.0+math.exp(-v[idx['opacity']]))
        if op < 0.05: continue
        sx = math.exp(v[idx['scale_0']]); sy = math.exp(v[idx['scale_1']]); sz = math.exp(v[idx['scale_2']])
        pos = (v[idx['x']], v[idx['y']], v[idx['z']])
        r = max(0.0, min(1.0, 0.5 + SH_C0*v[idx['f_dc_0']]))
        g = max(0.0, min(1.0, 0.5 + SH_C0*v[idx['f_dc_1']]))
        b = max(0.0, min(1.0, 0.5 + SH_C0*v[idx['f_dc_2']]))
        quat = (v[idx['rot_0']], v[idx['rot_1']], v[idx['rot_2']], v[idx['rot_3']])
        imp = op * (sx*sy*sz) ** (1.0/3.0)
        splats.append((imp, pos, (sx,sy,sz), quat, (r,g,b), op))

    splats.sort(key=lambda s: s[0], reverse=True)
    if len(splats) > target: splats = splats[:target]

    # centre + normalise scene to ~+-1.6 units
    xs = [s[1][0] for s in splats]; ys=[s[1][1] for s in splats]; zs=[s[1][2] for s in splats]
    cx,cy,cz = sum(xs)/len(xs), sum(ys)/len(ys), sum(zs)/len(zs)
    d = sorted(math.sqrt((s[1][0]-cx)**2+(s[1][1]-cy)**2+(s[1][2]-cz)**2) for s in splats)
    p90 = d[int(0.9*len(d))]
    sc = user_scale if user_scale > 0 else (1.6 / p90 if p90 > 0 else 1.0)

    def quat_axes(q):
        w,x,y,z = q
        nrm = math.sqrt(w*w+x*x+y*y+z*z) or 1.0
        w,x,y,z = w/nrm,x/nrm,y/nrm,z/nrm
        a0 = (1-2*(y*y+z*z), 2*(x*y+w*z),   2*(x*z-w*y))   # R columns = local axes
        a1 = (2*(x*y-w*z),   1-2*(x*x+z*z), 2*(y*z+w*x))
        a2 = (2*(x*z+w*y),   2*(y*z-w*x),   1-2*(x*x+y*y))
        return a0,a1,a2

    def rgb565(c):
        R=int(c[0]*31+0.5); G=int(c[1]*63+0.5); B=int(c[2]*31+0.5)
        return (max(0,min(31,R))<<11)|(max(0,min(63,G))<<5)|max(0,min(31,B))

    lines = []
    for _,pos,scale,quat,rgb,op in splats:
        # flip Y so a COLMAP/Y-down capture stands upright
        px=(pos[0]-cx)*sc; py=-(pos[1]-cy)*sc; pz=(pos[2]-cz)*sc
        a0,a1,a2 = quat_axes(quat)
        s0=(scale[0]*sc)**2; s1=(scale[1]*sc)**2; s2=(scale[2]*sc)**2
        cov = [
            s0*a0[0]*a0[0]+s1*a1[0]*a1[0]+s2*a2[0]*a2[0],  # xx
            s0*a0[0]*a0[1]+s1*a1[0]*a1[1]+s2*a2[0]*a2[1],  # xy
            s0*a0[0]*a0[2]+s1*a1[0]*a1[2]+s2*a2[0]*a2[2],  # xz
            s0*a0[1]*a0[1]+s1*a1[1]*a1[1]+s2*a2[1]*a2[1],  # yy
            s0*a0[1]*a0[2]+s1*a1[1]*a1[2]+s2*a2[1]*a2[2],  # yz
            s0*a0[2]*a0[2]+s1*a1[2]*a1[2]+s2*a2[2]*a2[2],  # zz
        ]
        cv = ",".join("%.5ff" % c for c in cov)
        lines.append("{{%.4ff,%.4ff,%.4ff},{%s},0x%04X,%.3ff}" % (px,py,pz,cv,rgb565(rgb),op))

    with open(out,'w') as o:
        o.write("/* generated by ply2splat from %s */\n#ifndef %s_H\n#define %s_H\n" % (inp, sym.upper(), sym.upper()))
        o.write('#include "mote_splat.h"\n')
        o.write("#define %s_COUNT %d\n" % (sym.upper(), len(lines)))
        o.write("static const MoteSplat %s[%d] = {\n" % (sym, len(lines)))
        o.write(",\n".join(lines))
        o.write("\n};\n#endif\n")
    print("wrote %d splats (of %d) to %s; scene_scale=%.4f" % (len(lines), n, out, sc))

main()
