#!/usr/bin/env python3
"""stl2ctrl — binary STL -> a C header of an indexed, decimated, smooth-shaded mesh.

Written for the Meta Quest Touch Pro controller models, which arrive as 8362
unindexed triangles each. That is far more than a visual proxy needs: the
controllers exist in CueVR so you can see where your hands are and line the cue up,
not to be inspected. So this welds vertices onto a grid, which both indexes and
decimates in one step, drops the triangles that collapse, and averages face normals
at the survivors for smooth shading.

Positions are quantised to int16 in millimetres/32, which is far finer than the
grid and keeps the header a sensible size; normals to int8. The runtime scales
back to metres.

    stl2ctrl.py <name> <in.stl> <out.h> [grid_mm=2.5]
"""
import struct, sys, collections

def load(path):
    d = open(path, 'rb').read()
    n = struct.unpack('<I', d[80:84])[0]
    tris, off = [], 84
    for _ in range(n):
        tris.append([struct.unpack_from('<3f', d, off + 12 + k * 12) for k in range(3)])
        off += 50
    return tris

def norm(a, b, c):
    u = (b[0]-a[0], b[1]-a[1], b[2]-a[2])
    v = (c[0]-a[0], c[1]-a[1], c[2]-a[2])
    n = (u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0])
    l = (n[0]*n[0]+n[1]*n[1]+n[2]*n[2]) ** 0.5
    return (n[0]/l, n[1]/l, n[2]/l) if l > 1e-12 else (0.0, 1.0, 0.0)

def main():
    name, src, dst = sys.argv[1], sys.argv[2], sys.argv[3]
    grid = float(sys.argv[4]) if len(sys.argv) > 4 else 2.5
    tris = load(src)

    # Weld onto a grid: this is the decimation. Keep the mean of the members so a
    # welded corner sits where the surface actually was, not at the cell centre.
    acc = collections.OrderedDict()
    def key(v): return (round(v[0]/grid), round(v[1]/grid), round(v[2]/grid))
    for t in tris:
        for v in t:
            k = key(v)
            if k not in acc: acc[k] = [0.0, 0.0, 0.0, 0, [0.0, 0.0, 0.0]]
            e = acc[k]
            e[0] += v[0]; e[1] += v[1]; e[2] += v[2]; e[3] += 1
    order = {k: i for i, k in enumerate(acc)}

    idx, kept = [], 0
    for t in tris:
        a, b, c = (order[key(v)] for v in t)
        if a == b or b == c or a == c:
            continue                      # collapsed by the weld
        n = norm(*t)
        for j in (a, b, c):
            e = list(acc.values())[0]     # placeholder, replaced below
        idx.append((a, b, c, n))
        kept += 1
    # accumulate normals at the surviving corners
    vals = list(acc.values())
    for a, b, c, n in idx:
        for j in (a, b, c):
            vn = vals[j][4]
            vn[0] += n[0]; vn[1] += n[1]; vn[2] += n[2]

    verts = []
    for e in vals:
        p = (e[0]/e[3], e[1]/e[3], e[2]/e[3])
        n = e[4]
        l = (n[0]*n[0]+n[1]*n[1]+n[2]*n[2]) ** 0.5
        n = (n[0]/l, n[1]/l, n[2]/l) if l > 1e-9 else (0.0, 1.0, 0.0)
        verts.append((p, n))

    with open(dst, 'w') as f:
        f.write("/* GENERATED by tools/stl2ctrl.py from %s — do not edit.\n"
                " * %d source triangles welded on a %.1f mm grid -> %d verts, %d tris.\n"
                " * Positions are int16 in 1/32 mm; normals int8. Scale to metres at use. */\n"
                % (src.split('/')[-1], len(tris), grid, len(verts), len(idx)))
        f.write("#ifndef CTRL_%s_H\n#define CTRL_%s_H\n#include <stdint.h>\n\n" % (name.upper(), name.upper()))
        f.write("#define %s_NV %d\n#define %s_NI %d\n" % (name.upper(), len(verts), name.upper(), len(idx)*3))
        f.write("#define %s_SCALE (1.0f / 32000.0f)   /* 1/32 mm -> metres */\n\n" % name.upper())
        f.write("static const int16_t %s_pos[] = {\n" % name)
        for i in range(0, len(verts), 6):
            row = verts[i:i+6]
            f.write("  " + " ".join("%d,%d,%d," % tuple(int(round(c*32)) for c in v[0]) for v in row) + "\n")
        f.write("};\n")
        f.write("static const int8_t %s_nrm[] = {\n" % name)
        for i in range(0, len(verts), 8):
            row = verts[i:i+8]
            f.write("  " + " ".join("%d,%d,%d," % tuple(max(-127, min(127, int(round(c*127)))) for c in v[1]) for v in row) + "\n")
        f.write("};\n")
        f.write("static const uint16_t %s_idx[] = {\n" % name)
        for i in range(0, len(idx), 8):
            row = idx[i:i+8]
            f.write("  " + " ".join("%d,%d,%d," % (a, b, c) for a, b, c, _ in row) + "\n")
        f.write("};\n#endif\n")
    print("%s: %d tris -> %d verts / %d tris" % (name, len(tris), len(verts), len(idx)))

main()
