/*
 * ttf2font — TrueType (.ttf) -> MoteFont (anti-aliased proportional bitmap font).
 *
 * Rasterises codepoints `first .. first+count-1` at `pixelsize` with stb_truetype
 * (which gives 8-bit AA coverage + real per-glyph metrics — no marker-row hacks),
 * and emits a `static const MoteFont <name>` header (see engine/render/mote_2d.h).
 * Glyph y-offsets are baked relative to the text-box TOP (ascent folded in) so the
 * engine just blits each glyph at (pen + xoff, y + yoff).
 *
 *   ttf2font <name> <in.ttf> <out.h> <pixelsize> [first=32] [count=95]
 *
 * Compiled on demand by the Studio / `mote bake` (like obj2mesh). Depends on
 * stb_truetype.h on the include path (-I studio/third_party).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

int main(int argc, char **argv) {
    if (argc < 5) {
        fprintf(stderr, "usage: %s <name> <in.ttf> <out.h> <pixelsize> [first=32] [count=95]\n", argv[0]);
        return 1;
    }
    const char *name = argv[1], *in = argv[2], *out = argv[3];
    int px = atoi(argv[4]);
    int first = argc > 5 ? atoi(argv[5]) : 32;
    int count = argc > 6 ? atoi(argv[6]) : 95;   /* 32..126 */
    if (px < 4) px = 4; if (px > 96) px = 96;
    if (first < 0) first = 0; if (first > 255) first = 255;
    if (count < 1) count = 1; if (first + count > 256) count = 256 - first;

    FILE *f = fopen(in, "rb"); if (!f) { perror(in); return 1; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char *ttf = (unsigned char *)malloc((size_t)sz);
    if (!ttf || fread(ttf, 1, (size_t)sz, f) != (size_t)sz) { fprintf(stderr, "ttf2font: read %s failed\n", in); return 1; }
    fclose(f);

    stbtt_fontinfo fi;
    if (!stbtt_InitFont(&fi, ttf, stbtt_GetFontOffsetForIndex(ttf, 0))) {
        fprintf(stderr, "ttf2font: not a valid TTF: %s\n", in); return 1;
    }
    float scale = stbtt_ScaleForPixelHeight(&fi, (float)px);
    int asc, desc, gap; stbtt_GetFontVMetrics(&fi, &asc, &desc, &gap);
    int ascent = (int)lroundf(asc * scale);
    int line_h = (int)lroundf((asc - desc + gap) * scale);
    if (line_h < 1) line_h = px;
    if (line_h > 255) line_h = 255;

    typedef struct { int adv, w, h, xo, yo; long off; } G;
    G *gl = (G *)calloc((size_t)count, sizeof(G));

    FILE *h = fopen(out, "w"); if (!h) { perror(out); return 1; }
    fprintf(h, "/* GENERATED by ttf2font from %s @ %dpx — do not edit. */\n", in, px);
    fprintf(h, "#ifndef MOTE_FONT_%s_H\n#define MOTE_FONT_%s_H\n#include \"mote_2d.h\"\n\n", name, name);

    /* Pass 1: pick the smallest LOSSLESS bit depth. A value's 4-bit quant is the
     * working level; if every level is 0/15 the font is binary -> 1-bit; if all fit
     * {0,5,10,15} -> 2-bit; else 4-bit. */
    int any_partial = 0, any_non2 = 0;
    for (int i = 0; i < count; i++) {
        int gw = 0, gh = 0, xo = 0, yo = 0;
        unsigned char *bm = stbtt_GetCodepointBitmap(&fi, scale, scale, first + i, &gw, &gh, &xo, &yo);
        if (!bm) continue;
        for (int p = 0; p < gw * gh; p++) { int n = (bm[p] * 15 + 127) / 255;
            if (n != 0 && n != 15) any_partial = 1;
            if (n != 0 && n != 5 && n != 10 && n != 15) any_non2 = 1; }
        stbtt_FreeBitmap(bm, NULL);
    }
    int bpp = !any_partial ? 1 : (!any_non2 ? 2 : 4), maxv = (1 << bpp) - 1;

    /* Pass 2: coverage packed MSB-first at `bpp` bits/pixel, byte-aligned per glyph. */
    fprintf(h, "static const uint8_t %s_cov[] = {\n", name);
    long total = 0; int col = 0;
    for (int i = 0; i < count; i++) {
        int cp = first + i;
        int aw, lsb; stbtt_GetCodepointHMetrics(&fi, cp, &aw, &lsb);
        int gw = 0, gh = 0, xo = 0, yo = 0;
        unsigned char *bm = stbtt_GetCodepointBitmap(&fi, scale, scale, cp, &gw, &gh, &xo, &yo);
        gl[i].adv = (int)lroundf(aw * scale);
        gl[i].w = gw; gl[i].h = gh; gl[i].xo = xo; gl[i].yo = ascent + yo; gl[i].off = total;
        if (bm) {
            int npix = gw * gh, acc = 0, nbits = 0;
            for (int p = 0; p < npix; p++) {
                int v = (bm[p] * maxv + 127) / 255;           /* 8-bit -> bpp, rounded */
                acc = (acc << bpp) | v; nbits += bpp;
                while (nbits >= 8) { nbits -= 8; fprintf(h, "%d,", (acc >> nbits) & 0xFF); if ((++col & 31) == 0) fputc('\n', h); }
            }
            if (nbits) { fprintf(h, "%d,", (acc << (8 - nbits)) & 0xFF); if ((++col & 31) == 0) fputc('\n', h); }   /* flush, byte-align */
            total += (npix * bpp + 7) / 8;
            stbtt_FreeBitmap(bm, NULL);
        }
    }
    if (total == 0) fprintf(h, "0");
    fprintf(h, "\n};\n");

    /* Glyph table {adv, w, h, xoff, yoff, off}. */
    fprintf(h, "static const MoteGlyph %s_glyphs[%d] = {\n", name, count);
    for (int i = 0; i < count; i++)
        fprintf(h, "  {%d,%d,%d,%d,%d,%ld},\n", gl[i].adv, gl[i].w, gl[i].h, gl[i].xo, gl[i].yo, gl[i].off);
    fprintf(h, "};\n");

    fprintf(h, "static const MoteFont %s = { %s_cov, %s_glyphs, %d, %d, %d, %d };  /* draw with mote->text_font(fb, &%s, ...) */\n\n",
            name, name, name, count, first, line_h, bpp, name);
    fprintf(h, "#endif\n");
    fclose(h);

    fprintf(stderr, "[ttf2font] %s: %d glyphs @ %dpx, line_h=%d, %d-bit, %ld cov bytes -> %s\n",
            name, count, px, line_h, bpp, total, out);
    free(gl); free(ttf);
    return 0;
}
