/* GENERATED by mote bake from sfx_charge_step.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_charge_step = mote_sfx_bake(mote, &sfx_charge_step_sfx); */
#ifndef MOTE_SFX_sfx_charge_step_H
#define MOTE_SFX_sfx_charge_step_H
#include "mote_api.h"

static const MoteSfx sfx_charge_step_sfx = {
    0,  /* wave */
    0.51773,0.106383,0.00236404,0.0969267, 0.243499,-0.446809,
    0,0, 0.527187,0.276596,0.271868,0.548463,
    0.803783,0.432624,0, 0,0.262411, -0.00236404,0, 0,-0.574468,
};

#endif
