/* GENERATED by Mote Studio — SFX recipe (assets/sfx_ui_deny.sfx). */
#ifndef MOTE_SFX_sfx_ui_deny_H
#define MOTE_SFX_sfx_ui_deny_H
#include "mote_api.h"

static const MoteSfx sfx_ui_deny_sfx = {
    0,
    0.22,0,0,0, 0.5,0,
    0,0, 0,0.02,0.2,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
