/* GENERATED by mote bake from sfx_dock.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_dock = mote_sfx_bake(mote, &sfx_dock_sfx); */
#ifndef MOTE_SFX_sfx_dock_H
#define MOTE_SFX_sfx_dock_H
#include "mote_api.h"

static const MoteSfx sfx_dock_sfx = {
    0,  /* wave */
    0.248227,0,-0.0780142,0, 0.338061,-0.739953,
    0.445755,0.0401891, 0.0756501,0.579196,0.0204773,0.470636,
    0.108747,0.0354609,0.364066, 0,-0.49409, 0.626478,0.617021, 0.00576782,-0.035461,
};

#endif
