/* GENERATED by mote bake from sfx_hit_hull.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_hit_hull = mote_sfx_bake(mote, &sfx_hit_hull_sfx); */
#ifndef MOTE_SFX_sfx_hit_hull_H
#define MOTE_SFX_sfx_hit_hull_H
#include "mote_api.h"

static const MoteSfx sfx_hit_hull_sfx = {
    3,  /* wave */
    0.237378,0,-0.338123,0, 0.5,0,
    0,0, 0,0.0848328,0,0.29115,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
