/* GENERATED by mote bake from sfx_chaff.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_chaff = mote_sfx_bake(mote, &sfx_chaff_sfx); */
#ifndef MOTE_SFX_sfx_chaff_H
#define MOTE_SFX_sfx_chaff_H
#include "mote_api.h"

static const MoteSfx sfx_chaff_sfx = {
    3,  /* wave */
    0.6,0,-0.2,0, 0.5,0,
    0,0, 0,0.02,0.3,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
