/* GENERATED by Mote Studio — SFX recipe (assets/sfx_chaff.sfx). */
#ifndef MOTE_SFX_sfx_chaff_H
#define MOTE_SFX_sfx_chaff_H
#include "mote_api.h"

static const MoteSfx sfx_chaff_sfx = {
    3,
    0.6,0,-0.2,0, 0.5,0,
    0,0, 0,0.02,0.3,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
