/* GENERATED by mote bake from sfx_explosion.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_explosion = mote_sfx_bake(mote, &sfx_explosion_sfx); */
#ifndef MOTE_SFX_sfx_explosion_H
#define MOTE_SFX_sfx_explosion_H
#include "mote_api.h"

static const MoteSfx sfx_explosion_sfx = {
    3,  /* wave */
    0.108179,0,0.0379944,0, 0.5,0,
    0,0, 0,0.362994,0.243213,0.544098,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
