/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_hit_shield = mote_sfx_bake(mote, &sfx_hit_shield_sfx); */
#ifndef MOTE_SFX_sfx_hit_shield_H
#define MOTE_SFX_sfx_hit_shield_H
#include "mote_api.h"

static const MoteSfx sfx_hit_shield_sfx = {
    2,  /* wave */
    0.284454,0,-0.175049,0, 0.200165,0.135059,
    0.472397,0.48869, 0.0111938,0.252917,0.0717163,0.369684,
    0.675415,0,0.221191, 0,0, 0,0, 0.190979,0.155334,
};

#endif
