/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_enemy_shield_hit = mote_sfx_bake(mote, &sfx_enemy_shield_hit_sfx); */
#ifndef MOTE_SFX_sfx_enemy_shield_hit_H
#define MOTE_SFX_sfx_enemy_shield_hit_H
#include "mote_api.h"

static const MoteSfx sfx_enemy_shield_hit_sfx = {
    0,  /* wave */
    0.283688,0.118203,-0.210402,0, 0.20331,-0.14707,
    0.132388,0.208038, 0.172577,0.309693,0.865248,0.444444,
    0.34279,-0.309693,0.184397, 0,-0.522459, 0.243499,-0.281324, 0.113306,-0.0610596,
};

#endif
