/* GENERATED by mote bake from sfx_ui_move.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_ui_move = mote_sfx_bake(mote, &sfx_ui_move_sfx); */
#ifndef MOTE_SFX_sfx_ui_move_H
#define MOTE_SFX_sfx_ui_move_H
#include "mote_api.h"

static const MoteSfx sfx_ui_move_sfx = {
    0,  /* wave */
    0.6,0,0,0, 0.5,0,
    0,0, 0,0.01,0.2,0.05,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
