/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_jump = mote_sfx_bake(mote, &sfx_jump_sfx); */
#ifndef MOTE_SFX_sfx_jump_H
#define MOTE_SFX_sfx_jump_H
#include "mote_api.h"

static const MoteSfx sfx_jump_sfx = {
    3,  /* wave */
    0.416076,0.260047,0.56974,0.408983, 0.529551,0.631206,
    0.316785,0.507715, 1,0.829787,0.378251,0.77305,
    0.276596,-0.035461,0.858156, 0,0.427896, 0.356974,0.130024, 0.8487,-0.33114,
};

#endif
