/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_sc_engage = mote_sfx_bake(mote, &sfx_sc_engage_sfx); */
#ifndef MOTE_SFX_sfx_sc_engage_H
#define MOTE_SFX_sfx_sc_engage_H
#include "mote_api.h"

static const MoteSfx sfx_sc_engage_sfx = {
    3,  /* wave */
    0.60181,0.420814,0.692308,0.420815, 0.434389,0.420815,
    0.538462,0.719457, 1,0.828054,0.388,0.597285,
    0.285068,-0.0678733,0.769231, 0,0.18552, -0.0678733,-0.303167, 0.809955,-0.160779,
};

#endif
