/* GENERATED by mote bake from sfx_klaxon.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_klaxon = mote_sfx_bake(mote, &sfx_klaxon_sfx); */
#ifndef MOTE_SFX_sfx_klaxon_H
#define MOTE_SFX_sfx_klaxon_H
#include "mote_api.h"

static const MoteSfx sfx_klaxon_sfx = {
    0,  /* wave */
    0.366312,0,0,0, 0.379358,0,
    0,0, 0,0.257683,0,0.174461,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
