/* GENERATED by mote bake from sfx_lock_acquire.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_lock_acquire = mote_sfx_bake(mote, &sfx_lock_acquire_sfx); */
#ifndef MOTE_SFX_sfx_lock_acquire_H
#define MOTE_SFX_sfx_lock_acquire_H
#include "mote_api.h"

static const MoteSfx sfx_lock_acquire_sfx = {
    1,  /* wave */
    0.423679,0,0,0, 0.5,0,
    0,0, 0,0.115839,0,0.0977814,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
