/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound sfx_scoop = mote_sfx_bake(mote, &sfx_scoop_sfx); */
#ifndef MOTE_SFX_sfx_scoop_H
#define MOTE_SFX_sfx_scoop_H
#include "mote_api.h"

static const MoteSfx sfx_scoop_sfx = {
    2,  /* wave */
    0.119476,0,0.234912,0, 0.750397,0.0467529,
    0.173828,0.264569, 0.138361,0.404602,0.438446,0.230127,
    0.673462,0,0.482208, 0,0, 0,0, 0.139816,0.492358,
};

#endif
