/* GENERATED by mote bake from sfx_ui_select.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound sfx_ui_select = mote_sfx_bake(mote, &sfx_ui_select_sfx); */
#ifndef MOTE_SFX_sfx_ui_select_H
#define MOTE_SFX_sfx_ui_select_H
#include "mote_api.h"

static const MoteSfx sfx_ui_select_sfx = {
    0,  /* wave */
    0.85,0,0,0, 0.5,0,
    0,0, 0,0.02,0.3,0.08,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
