/* GENERATED by mote bake from wpn_plasma.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_plasma = mote_sfx_bake(mote, &wpn_plasma_sfx); */
#ifndef MOTE_SFX_wpn_plasma_H
#define MOTE_SFX_wpn_plasma_H
#include "mote_api.h"

static const MoteSfx wpn_plasma_sfx = {
    1,  /* wave */
    0.329434,0.0428271,0.0169387,0.151514, 0.655176,-0.0598998,
    0.264449,0.429003, 0.00716187,0.293956,0.352324,0.179824,
    0.467803,0.0708985,0.105039, 0.0644824,0.241709, 0.741543,-0.601523, 0.512847,-0.208318,
};

#endif
