/* GENERATED by mote bake from wpn_mine.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_mine = mote_sfx_bake(mote, &wpn_mine_sfx); */
#ifndef MOTE_SFX_wpn_mine_H
#define MOTE_SFX_wpn_mine_H
#include "mote_api.h"

static const MoteSfx wpn_mine_sfx = {
    3,  /* wave */
    0.183789,0,0.0286499,0, 0.5,0,
    0,0, 0,0.30343,0.439905,0.4138,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
