/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_photon = mote_sfx_bake(mote, &wpn_photon_sfx); */
#ifndef MOTE_SFX_wpn_photon_H
#define MOTE_SFX_wpn_photon_H
#include "mote_api.h"

static const MoteSfx wpn_photon_sfx = {
    2,  /* wave */
    0.19104,0,-0.141943,0, 0.681946,0.171216,
    0.207626,0.071228, 0.00223389,0.480127,0.319839,0.46676,
    0.249219,0,0.45578, 0,0, 0,0, 0.362604,-0.295398,
};

#endif
