/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_autocannon = mote_sfx_bake(mote, &wpn_autocannon_sfx); */
#ifndef MOTE_SFX_wpn_autocannon_H
#define MOTE_SFX_wpn_autocannon_H
#include "mote_api.h"

static const MoteSfx wpn_autocannon_sfx = {
    3,  /* wave */
    0.359265,0,-0.44707,0, 0.5,0,
    0,0, 0,0.059314,0,0.172693,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
