/* GENERATED by mote bake from wpn_pulse_m.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_pulse_m = mote_sfx_bake(mote, &wpn_pulse_m_sfx); */
#ifndef MOTE_SFX_wpn_pulse_m_H
#define MOTE_SFX_wpn_pulse_m_H
#include "mote_api.h"

static const MoteSfx wpn_pulse_m_sfx = {
    0,  /* wave */
    0.598694,0.1,-0.184625,0, 0.264664,0.169067,
    0,0, 0,0.226953,0.167368,0.320703,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
