/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_missile = mote_sfx_bake(mote, &wpn_missile_sfx); */
#ifndef MOTE_SFX_wpn_missile_H
#define MOTE_SFX_wpn_missile_H
#include "mote_api.h"

static const MoteSfx wpn_missile_sfx = {
    3,  /* wave */
    0.41626,0,-0.0805603,0, 0.5,0,
    0.0449524,0.0627503, 0,0.264948,0.401318,0.519717,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
