/* GENERATED by mote bake from wpn_tractor.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_tractor = mote_sfx_bake(mote, &wpn_tractor_sfx); */
#ifndef MOTE_SFX_wpn_tractor_H
#define MOTE_SFX_wpn_tractor_H
#include "mote_api.h"

static const MoteSfx wpn_tractor_sfx = {
    1,  /* wave */
    0.44035,0,0,0, 0.5,0,
    0.330969,0.43026, 0,0.671395,0,0.0813797,
    1,0,0, 0.1,0, 0,0, 0,0,
};

#endif
