/* GENERATED by mote bake from wpn_mining.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_mining = mote_sfx_bake(mote, &wpn_mining_sfx); */
#ifndef MOTE_SFX_wpn_mining_H
#define MOTE_SFX_wpn_mining_H
#include "mote_api.h"

static const MoteSfx wpn_mining_sfx = {
    1,  /* wave */
    0.574927,0.118744,-0.163965,0, 0.0505219,0.00980835,
    0,0, 0,0.26062,0.0676941,0.00992432,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
