/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_lance = mote_sfx_bake(mote, &wpn_lance_sfx); */
#ifndef MOTE_SFX_wpn_lance_H
#define MOTE_SFX_wpn_lance_H
#include "mote_api.h"

static const MoteSfx wpn_lance_sfx = {
    2,  /* wave */
    0.683215,0.13466,-0.277642,0.0780141, 0.0687488,0.268756,
    0.0630817,0.354087, 0.160676,0.574095,0.375626,0.281324,
    0.291887,0,0.0025647, 0,-0.105, -0.688258,-0.323877, 0.283371,-0.187004,
};

#endif
