/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound wpn_blaster = mote_sfx_bake(mote, &wpn_blaster_sfx); */
#ifndef MOTE_SFX_wpn_blaster_H
#define MOTE_SFX_wpn_blaster_H
#include "mote_api.h"

static const MoteSfx wpn_blaster_sfx = {
    1,  /* wave */
    0.349882,0.218488,-0.219818,0, 0.243423,0.046936,
    0,0, 0,0.221387,0.294296,0.28623,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
