/* GENERATED by mote bake from wpn_pulse_s.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_pulse_s = mote_sfx_bake(mote, &wpn_pulse_s_sfx); */
#ifndef MOTE_SFX_wpn_pulse_s_H
#define MOTE_SFX_wpn_pulse_s_H
#include "mote_api.h"

static const MoteSfx wpn_pulse_s_sfx = {
    0,  /* wave */
    0.716312,0.514288,-0.182033,0, 0.346497,0.0279236,
    0,0, 0,0.423168,0.416076,0.3026,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
