/* GENERATED by mote bake from wpn_gauss.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_gauss = mote_sfx_bake(mote, &wpn_gauss_sfx); */
#ifndef MOTE_SFX_wpn_gauss_H
#define MOTE_SFX_wpn_gauss_H
#include "mote_api.h"

static const MoteSfx wpn_gauss_sfx = {
    1,  /* wave */
    0.432624,0.257683,0.0732861,0, 0.0228577,0.0888062,
    0.44208,0.825059, 0.00339966,0.335697,0.486069,0.142221,
    0.921631,0,0.456265, 0,0, -0.546099,-0.34279, 0.176816,0.591748,
};

#endif
