/* GENERATED by mote bake from wpn_flak.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_flak = mote_sfx_bake(mote, &wpn_flak_sfx); */
#ifndef MOTE_SFX_wpn_flak_H
#define MOTE_SFX_wpn_flak_H
#include "mote_api.h"

static const MoteSfx wpn_flak_sfx = {
    3,  /* wave */
    0.456265,0.375887,0.0591017,-0.035461, 0.5,0,
    0.271868,0.399527, 0.281324,0.349882,0.3026,0.22695,
    0.375887,-0.36643,0, 0,-0.304965, -0.0449173,-0.200946, 0,0,
};

#endif
