/* GENERATED by mote bake from wpn_ion.sfx — edit the .sfx sidecar, not this.
 *   Play: MoteSound wpn_ion = mote_sfx_bake(mote, &wpn_ion_sfx); */
#ifndef MOTE_SFX_wpn_ion_H
#define MOTE_SFX_wpn_ion_H
#include "mote_api.h"

static const MoteSfx wpn_ion_sfx = {
    1,  /* wave */
    0.319149,0.153664,-0.196222,0, 0.335907,0.0689209,
    0,0, 0,0.294885,0.166296,0.365576,
    1,0,0, 0,0, -0.531915,0, 0,0,
};

#endif
