/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound paddle = mote_sfx_bake(mote, &paddle_sfx); */
#ifndef MOTE_SFX_paddle_H
#define MOTE_SFX_paddle_H
#include "mote_api.h"

static const MoteSfx paddle_sfx = {
    0,  /* wave */
    0.42,0,-0.25,0, 0.5,0,
    0,0, 0,0.01,0.4,0.1,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
