/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound score = mote_sfx_bake(mote, &score_sfx); */
#ifndef MOTE_SFX_score_H
#define MOTE_SFX_score_H
#include "mote_api.h"

static const MoteSfx score_sfx = {
    0,  /* wave */
    0.52,0,0,0, 0.5,0,
    0,0, 0,0.07,0.4,0.28,
    1,0,0, 0,0, 0,0, 0.55,0.45,
};

#endif
