/* GENERATED by Mote Studio — sprite animations (anims/chars.anims). Clips are const ->
 * flash, 0 SRAM. The sheet reuses the atlas image from atlas.h (no duplicate pixels). */
#ifndef MOTE_ANIM_chars_H
#define MOTE_ANIM_chars_H
#include "mote_anim.h"
#include "atlas.h"

static const MoteAnimSheet chars_sheet = { &atlas_img, 12, 12 };

static const MoteAnimFrame player_walk_f[] = {{0,143,0},{1,143,0}};
static const MoteAnimClip  player_walk = {"player_walk", player_walk_f, 2, MOTE_ANIM_LOOP, 6,11};
static const MoteAnimFrame player_idle_f[] = {{0,1000,0}};
static const MoteAnimClip  player_idle = {"player_idle", player_idle_f, 1, MOTE_ANIM_LOOP, 6,11};
static const MoteAnimFrame bat_walk_f[] = {{2,125,0},{3,125,0}};
static const MoteAnimClip  bat_walk = {"bat_walk", bat_walk_f, 2, MOTE_ANIM_LOOP, 6,6};
static const MoteAnimFrame zombie_walk_f[] = {{4,200,0},{5,200,0}};
static const MoteAnimClip  zombie_walk = {"zombie_walk", zombie_walk_f, 2, MOTE_ANIM_LOOP, 6,6};
static const MoteAnimFrame skel_walk_f[] = {{6,167,0},{7,167,0}};
static const MoteAnimClip  skel_walk = {"skel_walk", skel_walk_f, 2, MOTE_ANIM_LOOP, 6,6};
static const MoteAnimFrame ghost_walk_f[] = {{8,167,0},{9,167,0}};
static const MoteAnimClip  ghost_walk = {"ghost_walk", ghost_walk_f, 2, MOTE_ANIM_LOOP, 6,6};
static const MoteAnimFrame imp_walk_f[] = {{12,111,0},{13,111,0}};
static const MoteAnimClip  imp_walk = {"imp_walk", imp_walk_f, 2, MOTE_ANIM_LOOP, 6,6};
static const MoteAnimFrame slime_walk_f[] = {{10,250,0},{11,250,0}};
static const MoteAnimClip  slime_walk = {"slime_walk", slime_walk_f, 2, MOTE_ANIM_LOOP, 6,6};
static const MoteAnimFrame boss_idle_f[] = {{14,1000,0}};
static const MoteAnimClip  boss_idle = {"boss_idle", boss_idle_f, 1, MOTE_ANIM_LOOP, 6,6};

#endif
