/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound hurt = mote_sfx_bake(mote, &hurt_sfx); */
#ifndef MOTE_SFX_hurt_H
#define MOTE_SFX_hurt_H
#include "mote_api.h"

static const MoteSfx hurt_sfx = {
    3,  /* wave */
    0.26,0,-0.16,0, 0.5,0,
    0,0, 0,0.06,0.3,0.34,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
