/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound pickup = mote_sfx_bake(mote, &pickup_sfx); */
#ifndef MOTE_SFX_pickup_H
#define MOTE_SFX_pickup_H
#include "mote_api.h"

static const MoteSfx pickup_sfx = {
    0,  /* wave */
    0.6,0,0,0, 0.5,0,
    0,0, 0,0.02,0.3,0.14,
    1,0,0, 0,0, 0,0, 0.55,0.42,
};

#endif
