/* GENERATED by Mote Studio — SFX recipe. Play: MoteSound shoot = mote_sfx_bake(mote, &shoot_sfx); */
#ifndef MOTE_SFX_shoot_H
#define MOTE_SFX_shoot_H
#include "mote_api.h"

static const MoteSfx shoot_sfx = {
    1,  /* wave */
    0.55,0,-0.34,0, 0.5,0,
    0,0, 0,0.02,0.4,0.16,
    1,0,0, 0,0, 0,0, 0,0,
};

#endif
